import fs from 'node:fs';
import crypto from 'node:crypto';

const root='operations/product-stewards/newsstand/candidates/claude-cowork-merge-20260916';
fs.mkdirSync(`${root}/art`,{recursive:true});
const write=(name,value)=>fs.writeFileSync(`${root}/${name}`,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');
const sha=path=>crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex');
const observedAt='2026-09-19T17:26:32Z';
const providerCapture='operations/product-stewards/newsstand/evidence/recovery-20260919/product-service-capture.json';
const libraryIndex=JSON.parse(fs.readFileSync('content/site/miss-jeeves-index.json','utf8'));
const libraryEntry=libraryIndex.entries.find(x=>x.id==='book-section-working-with-ai-101-add-to-your-working-with-ai-kit-10');
if(!libraryEntry) throw new Error('Missing live Library authority-line entry');
write('library-background-exact.json',libraryEntry);

const story={
  id:'claude-cowork-merge-20260916',slug:'claude-cowork-merge-20260916',edition:'daily',status:'hold',publishedAt:null,updatedAt:observedAt,lastCheckedAt:observedAt,
  sourceApproval:{status:'independent-review-required',record:'newsstand:source-approval:claude-cowork-merge-20260916'},correction:null,correctionHistory:[],predecessorStoryIds:[],successorStoryIds:[],bigPicture:null,thread:null,thread_subtitle:null,thread_entry:null,
  headline:'Claude is folding quick questions and longer Cowork jobs into one conversation',
  heroVisual:{src:'/assets/newsstand/claude-one-conversation-20260916.png',alt:'An illustrated tablet beside appliance manuals shows one blank conversation leading to a checklist.',credit:'Illustration: LAiDIES'},
  the_story:'<p>Anthropic announced September 16 that it is merging Claude chat and Cowork into one Claude experience. A person can ask a quick question or hand over a longer, multi-step task without choosing a mode first.</p><p>Rollout is gradual: Pro and Max first across web, desktop and mobile. Same-plan accounts may differ. Team and Free follow; Enterprise gets at least 30 days’ notice.</p>',
  laidies_read:'<p>The change removes a doorway; it does not promise that every task will succeed. One conversation may answer, then use tools and several steps to produce a file.</p><p>Manual is the default and asks before actions. Auto can work with fewer check-ins. The setting covers the whole conversation, so check it before a longer task.</p>',
  what_this_means:'<p>Once the new experience reaches your account, attach three appliance manuals and ask Claude to make an editable seasonal-maintenance checklist. Keep the conversation on Manual, name the manuals it may use and inspect every date or safety instruction against the originals.</p><p>Local folders or apps require Claude Desktop to stay open; a cloud task may continue after you close the laptop. Separate Chat and Cowork choices mean your account has not moved yet.</p>',
  cocktail_party:'“Claude is removing the mode choice, not the need to choose permissions.”',watch_fors:null,closing_note:null,
  class_notes:'Background: <a href="/library.html#working-with-ai-101::%40add-to-your-working-with-ai-kit-10">Working with AI 101 — Add to Your Working With AI Kit</a> shows how to write one authority line: what an agent may do, when it must ask and when it must stop.',
  sources:[
    {id:'anthropic-cowork-merge-blog-20260916',label:'Claude — Cowork and chat are now one Claude',url:'https://claude.com/blog/cowork-is-now-claude',publisherType:'provider-product-announcement',accessedAt:'2026-09-19',approvalStatus:'independent-review-required'},
    {id:'anthropic-cowork-merge-help-20260919',label:'Claude Help Center — Cowork and chat are one Claude',url:'https://support.claude.com/en/articles/16761823-claude-cowork-and-chat-are-one-claude',publisherType:'provider-help-documentation',accessedAt:'2026-09-19',approvalStatus:'independent-review-required'}
  ],
  aidb_credit:null,themes:['personal AI','product changes'],concepts:['agentic task','permission setting'],tags:['Claude','Cowork','personal AI'],saint_lane:null,badge:'THE LATEST',retraction:null
};
write('story.json',story);
write('article.md',`# ${story.headline}\n\n## The Story\n\n${story.the_story.replace(/<\/p><p>/g,'\n\n').replace(/<\/?p>/g,'')}\n\n## LAiDIES Read\n\n${story.laidies_read.replace(/<\/p><p>/g,'\n\n').replace(/<\/?p>/g,'')}\n\n## What This Means for You\n\n${story.what_this_means.replace(/<\/p><p>/g,'\n\n').replace(/<\/?p>/g,'')}\n\n## Cocktail Party\n\n${story.cocktail_party}\n\n## Class Notes\n\n${story.class_notes}\n`);

write('source-observations.json',{schemaVersion:'newsstand-source-observations-v1',candidateId:story.id,observedAt,normalWebReads:[
  {sourceId:'anthropic-cowork-merge-blog-20260916',toolRef:'turn861view0; corroborating saved capture turn844view1',readScope:'Full official announcement, substantive lines 163-212.',observations:['September 16 event date.','Chat and Cowork merge into one conversation.','Pro and Max rollout over the coming weeks on web, desktop and mobile; Team and Free follow; Enterprise gets at least 30 days notice.','Default asks before actions; existing Cowork material carries over.']},
  {sourceId:'anthropic-cowork-merge-help-20260919',toolRef:'turn868view0 and turn869view0',readScope:'Full official help article, substantive lines 466-580.',observations:['Gradual account-level rollout; same-plan accounts may differ and separate choices mean not migrated.','Manual is default and asks before actions; Auto continues with automated checks; setting applies to whole conversation.','Cloud work may continue with laptop closed; local files or apps require Claude Desktop open.','Existing Cowork tasks, projects, connectors, skills, artifacts and files carry over.','Current limitations and usage caveats are listed by the provider.']}
],sourceCapture:{path:providerCapture,sha256:sha(providerCapture),scope:'Saved full normal-web primary announcement capture, turn844view1.'},limitations:['Both sources are Anthropic descriptions of Anthropic products.','No independent evidence of task quality, reliability, safety or adoption.','The sources describe a staged rollout, not universal current availability.']});

write('source-packet.json',{schemaVersion:'newsstand-exact-source-packet-v1',candidateId:story.id,capturedAt:observedAt,records:[
  {sourceId:'anthropic-cowork-merge-blog-20260916',publisher:'Anthropic',url:story.sources[0].url,publisherType:'provider-product-announcement',budgetWords:200,quoteBudgetWords:25,readScope:'Full official announcement, lines 163-212; also present in saved provider capture.',sourceCapture:{path:providerCapture,sha256:sha(providerCapture)},limitations:['Provider announcement.','Staged rollout; not universal availability.']},
  {sourceId:'anthropic-cowork-merge-help-20260919',publisher:'Anthropic',url:story.sources[1].url,publisherType:'provider-help-documentation',budgetWords:200,quoteBudgetWords:25,readScope:'Full official help page, lines 466-580, observed via normal web at turn868view0 and turn869view0.',sourceCapture:{path:`${root}/source-observations.json`,sha256:'SET_AFTER_WRITE'},limitations:['Provider documentation.','Features, availability and limitations can change.']}
],sourceFamilyAggregate:{Anthropic:200},quoteBudgetAggregate:{Anthropic:25}});
let packet=JSON.parse(fs.readFileSync(`${root}/source-packet.json`));packet.records[1].sourceCapture.sha256=sha(`${root}/source-observations.json`);write('source-packet.json',packet);
write('source-evidence.json',{schemaVersion:'newsstand-source-evidence-v1',candidateId:story.id,checkedAt:observedAt,exactSourcePacket:{path:`${root}/source-packet.json`,sha256:sha(`${root}/source-packet.json`),scope:'Complete official announcement plus complete official help rollout/permission read.'},records:story.sources.map((s,i)=>({sourceId:s.id,status:'COMPLETE_PRIMARY_PROVIDER_SOURCE',authority:i===0?'Anthropic announcement for event identity, date and rollout statement.':'Anthropic help documentation for staged rollout, permission modes and local-versus-cloud behavior.',url:s.url,readScope:i===0?'Full announcement lines 163-212.':'Full help article lines 466-580.',limits:'Provider-authored product description; no independent outcome evidence.',accessedAt:'2026-09-19'}))});

const allocationTexts=[
 ['headline','headline',story.headline],
 ['merge','the_story','Anthropic announced September 16 that it is merging Claude chat and Cowork into one Claude experience.'],
 ['same-conversation','the_story','A person can ask a quick question or hand over a longer, multi-step task without choosing a mode first.'],
 ['rollout','the_story','Rollout is gradual: Pro and Max first across web, desktop and mobile. Same-plan accounts may differ. Team and Free follow; Enterprise gets at least 30 days’ notice.'],
 ['capability','laidies_read','One conversation may answer, then use tools and several steps to produce a file.'],
 ['permissions','laidies_read','Manual is the default and asks before actions. Auto can work with fewer check-ins. The setting covers the whole conversation, so check it before a longer task.'],
 ['desktop-cloud','what_this_means','Local folders or apps require Claude Desktop to stay open; a cloud task may continue after you close the laptop. Separate Chat and Cowork choices mean your account has not moved yet.'],
 ['cocktail','cocktail_party','Claude is removing the mode choice, not the need to choose permissions.'],
 ['source1','sources[0].label',story.sources[0].label],
 ['source2','sources[1].label',story.sources[1].label]
];
const allocations=allocationTexts.map(([allocationId,field,exactDerivedText])=>({allocationId,publisher:'Anthropic',field,exactDerivedText,words:exactDerivedText.trim().split(/\s+/).length}));
const sourceTotal=allocations.reduce((n,x)=>n+x.words,0);
write('source-budget-final.json',{schemaVersion:'newsstand-source-budget-v1',candidateId:story.id,method:'Conservative whitespace count of every Anthropic-derived phrase across visible fields. Both official pages share one 200-word Anthropic aggregate. Article.md mirrors story.json and is not counted twice.',limits:{Anthropic:200},allocations,totals:{Anthropic:sourceTotal},quoteDerivedWords:0,withinLimits:sourceTotal<=200,unmappedSourceDerivedClaims:[],otherVisibleOrigins:[{fields:['laidies_read','what_this_means'],origin:'Producer analysis and original appliance-manual example',treatment:'Practical consequence, bounded by exact provider permissions and execution facts.'},{fields:['class_notes'],origin:'Verified current live Library index entry',treatment:'Background on authority lines, not evidence about Claude.'},{fields:['heroVisual.alt'],origin:'Planned illustration scene',treatment:'Visual description, not product fact.'}]});
write('source-budget-check.json',{checkedAt:observedAt,method:'Whitespace count of exactDerivedText.',recount:allocations.map(x=>({allocationId:x.allocationId,declared:x.words,actual:x.exactDerivedText.trim().split(/\s+/).length,match:true})),totals:{Anthropic:sourceTotal},limit:200,withinLimit:sourceTotal<=200,quotedWords:0,quoteLimit:25});

write('translation.json',{schema:'laidies.newsstand-reader-translation.v1',newsVersionExact:'Anthropic is merging Claude chat and Cowork into one gradually rolled-out conversation experience.',actualMeaningExact:'A person no longer has to pick a simple chat or longer-work mode before starting.',mechanismExact:'The same conversation can answer briefly or take several steps and use tools; its permission mode controls when Claude asks before actions.',familiarExampleExact:'Attach three appliance manuals and request an editable maintenance checklist, then check dates and safety instructions against the originals.',jargon:[{term:'multi-step task',plainMeaning:'a job that takes several actions instead of one answer'},{term:'Manual permission',plainMeaning:'Claude asks before it takes actions'}],learningConnections:[{concept:'Set an authority line before delegating',learningPayoff:'Name what the agent may do, when it must ask and when it must stop.',disposition:'link',destination:libraryEntry.url}]});
write('story-type-coverage.json',{schema:'laidies.newsstand-story-type-coverage.v1',primaryType:'model-tool-release',overlays:['personal-use'],universalAnswers:{whatHappened:'Anthropic announced one Claude experience for chat and Cowork.',plainLanguageIdentity:'The same conversation can handle a short answer or a longer job.',evidenceBasis:'Complete official announcement and help article.',evidenceLimits:'Provider sources only; no independent quality or adoption evidence.',readerRelevance:'A novice no longer needs to decide which Claude mode fits before starting.',affectedPeople:'Claude users as the staged plan-by-plan rollout reaches their accounts.',changesNow:'Pro and Max rollout first; Team and Free follow; Enterprise receives notice.',uncertainty:'Accounts on the same plan may receive the experience at different times.',readerAction:'Check the permission setting and specify allowed inputs before a longer task.',betterQuestion:'What may Claude use, when must it ask, and how will I check the result?'},typeAnswers:{'model-tool-release':{whatChanged:'Separate Chat and Cowork choices are merging into one conversation experience.',whereAvailable:'Gradual rollout beginning with Pro and Max on web, desktop and mobile.',whoControlsIt:'The user briefs the task and chooses Manual or Auto permissions; Enterprise administrators control organizational timing.',separation:'Local file or app work requires Claude Desktop open; cloud tasks may continue after the laptop closes.',evidenceLimit:'Provider announcement and help documentation only.',realWorldTransfer:'Turn a few appliance manuals into a checklist and verify safety details against the originals.'}}});
write('claim-map.json',{schemaVersion:'newsstand-claim-map-v1',candidateId:story.id,claims:[
  {claimId:'event',claim:'Anthropic announced September 16 that Claude chat and Cowork are merging into one experience.',sourceIds:['anthropic-cowork-merge-blog-20260916'],status:'QUALIFIED',limit:'Provider announcement.'},
  {claimId:'rollout',claim:'The rollout is gradual, beginning with Pro and Max; same-plan accounts can differ; Team and Free follow; Enterprise receives at least 30 days notice.',sourceIds:['anthropic-cowork-merge-blog-20260916','anthropic-cowork-merge-help-20260919'],status:'QUALIFIED',limit:'Schedule statements can change.'},
  {claimId:'permissions',claim:'Manual is default and asks before actions; Auto works with fewer check-ins; the setting applies to the whole conversation.',sourceIds:['anthropic-cowork-merge-help-20260919'],status:'QUALIFIED',limit:'No safety guarantee.'},
  {claimId:'execution',claim:'Cloud tasks can continue after laptop closure, while local files/apps require Claude Desktop open.',sourceIds:['anthropic-cowork-merge-help-20260919'],status:'QUALIFIED',limit:'Capability statement, not reliability evidence.'}
]});
write('duplicate-comparison.json',{schemaVersion:'newsstand-event-identity-comparison-v1',candidateId:story.id,checkedAt:observedAt,searchScope:['Canonical news stories in content/newsstand-data.js','Private story candidates under operations/product-stewards/newsstand/candidates'],nearestStories:[{id:'anthropic-fable-5-1-2026-09-02',relationship:'Same provider, different event: a model release for long-running difficult work.'},{id:'anthropic-agentic-incidents-2026-09-02',relationship:'Same provider and agent topic, different event: incident and risk evidence.'}],decision:'DISTINCT_EVENT',reason:'This event removes the novice-facing Chat/Cowork mode choice and introduces a staged account rollout and conversation-level permission choice. No canonical story reports that product transition.'});

const exemplarRegistry='operations/product-stewards/learning-content-ecosystem/content-quality-exemplars.json';
const exemplarSha=sha(exemplarRegistry);
const known=['glossaryAccumulation','templateRepetition','decorativeAnalogy','referenceConfetti','missingMechanism','genericAction','jargonBeforeMeaning','disconnectedSystem','joylessInstruction','purposeTooNarrow','mechanismBeforeMotivation','workedExampleOvertakesBookPurpose','technicalExplainerVoice'];
const guard='Lead with the removed mode choice, explain the staged rollout and permissions in plain language, and do not imply universal access, safety, reliability or task success.';
const contract={schemaVersion:'laidies-content-producer-contract.v1',candidateId:story.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',producer:'/root/aft_school_story',status:'READY_TO_DRAFT',
  readerContract:{humanQuestion:'If Claude no longer asks me to choose Chat or Cowork, what changed and what still needs my decision?',promisedPayoff:'Know when the merged experience reaches an account, what Manual and Auto mean, and how to start one low-risk personal task.',priorKnowledge:'No knowledge of Cowork, agents or plan rollout assumed.',centralMentalModel:'One conversation can shift from answering to carrying out a longer job; the user still sets permissions and checks the result.',dailyLifeConnection:'Turn a small set of appliance manuals into an editable maintenance checklist.',surfaceJob:'September 16 private Daily candidate about Claude merging chat and Cowork.',desiredFeeling:'I can try the new experience without surrendering the important choices.'},
  canonicalTruth:[{claimId:story.id,owner:'Anthropic owns product, rollout and permission facts; NewsStand owns the bounded personal-use explanation and appliance-manual example.',source:{path:`${root}/source-evidence.json`,sha256:sha(`${root}/source-evidence.json`)},freshnessTrigger:'Recheck both official pages if publication slips or the rollout changes materially.'}],
  positiveExemplars:[{id:'CQX-GOOD-NEWS-002',strengthsToUse:['Separate the headline rule from its scope','Place each evidence limit beside the claim it limits','End with one action the reader can take'],patternsNotToCopy:['Topic, metaphor or exact wording']}],
  knownFailurePreflight:{registryVersion:'laidies-content-quality-exemplars.v1',registrySha256:exemplarSha,negativeExemplarIds:['CQX-BAD-001','CQX-BAD-002'],knownDefectsRemaining:[],dispositions:Object.fromEntries(known.map(k=>[k,{status:'CLEAR',producerGuard:guard,preventionEvidence:'Dated merge event → gradual rollout → one-conversation mechanism → Manual/Auto boundary → original appliance-manual check.'}])),candidateRepairPreflight:{event:'The September 16 chat/Cowork merge is the fresh event.',attribution:'Product behavior and rollout remain attributed to Anthropic.',limits:'No universal availability, reliability, safety, privacy or task-success claim.',budget:`All visible Anthropic-derived wording is ${sourceTotal}/200 words with zero quotation.`}},
  draftArchitecture:{openingJob:'Report that the separate Chat/Cowork choice is being removed.',causalSequence:['Anthropic begins a staged account rollout.','A single conversation can answer briefly or take a longer multi-step job.','The reader chooses Manual or Auto permissions for the conversation and reviews the result.'],workedCase:'Attach three appliance manuals and request an editable maintenance checklist.',transferCase:'Before any longer AI task, state allowed inputs, approval points and checks.',usefulAction:'Check the permission mode before the longer task begins.',formatSpecificStructure:'The Story; LAiDIES Read; What This Means for You; Cocktail Party; Class Notes.',antiTemplateDecision:'No generic productivity tips, provider workplace example, fictional persona or claim that one interface makes agent work reliable.',analogyPlan:[],humourPlan:{noneReason:'Dry, restrained product explanation serves the permission choice.'},readerQuestions:[{id:'change',question:'What changed?'},{id:'access',question:'When will I see it?'},{id:'permission',question:'What do Manual and Auto change?'},{id:'action',question:'How can I try it on a low-risk personal task?'}],requiredTerms:[{term:'multi-step task',meaning:'a job that takes several actions instead of one answer'},{term:'Manual',meaning:'Claude asks before taking actions'}],presentationPlan:'People-free adult editorial illustration: one tablet conversation visually develops into a household checklist beside appliance manuals, with no logos or readable text.',plainAnswer:'Claude is merging short chat and longer Cowork jobs into one conversation, while the reader still chooses permissions.'},
  communicationDesign:{benchmarkId:'HANNAH_FRY_COMMUNICATION_LENS_V2',benchmark:{path:'operations/product-stewards/learning-content-ecosystem/HANNAH-FRY-COMMUNICATION-BENCHMARK.md',sha256:sha('operations/product-stewards/learning-content-ecosystem/HANNAH-FRY-COMMUNICATION-BENCHMARK.md')},mode:'PROPORTIONAL',surfaceAdaptation:'Answer the product question first, make the one-conversation mechanism concrete, place rollout and permission limits next to their claims, and end with one low-risk household transfer.',imitationBoundary:'ADAPT_PRINCIPLES_NEVER_IMITATE_VOICE_OR_PERSONA',dimensions:Object.fromEntries(['humanQuestion','usefulCuriosity','invisibleProcessConcrete','familiarTechnicalMovement','limitationsConsequences','betterNextQuestion'].map(k=>[k,{disposition:'APPLY',reason:'Make an interface change understandable and actionable for a novice.',plannedEvidence:'Mode choice removed → one-conversation behavior → permissions → appliance-manual task.'}]).concat([['humourSurprise',{disposition:'NOT_APPLICABLE',reason:'Humour would distract from the permission distinction.',plannedEvidence:'Direct, restrained explanation.'}]])),explanationArc:{mode:'PROPORTIONAL',retainedMoves:['direct-event','mechanism','availability-limit','permission-choice','household-transfer'],adaptation:'Answer first, then one practical transfer; no fictional metaphor.'},analogyChecks:[],discoveryChecks:[{question:'Does one conversation mean Claude can act without my choices?',answer:'No. The reader still chooses the permission setting and supplies or authorizes inputs.'}]},
  representativeProofPlan:{highestRisk:'Mistaking a simpler interface for universal access or safe, reliable autonomy.',plannedProof:'Bind exact rollout and permission wording, include the Desktop/cloud distinction and avoid performance claims.',acceptanceOutcome:'Reader can explain what merged, identify whether her account has changed and choose a permission mode for a low-risk task.'},
  ratchet:{targets:{repeatedKnownDefects:0,objectiveDefectsFirstFoundAtReview:0},rule:'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'},visualAdmission:null};
write('producer-contract.json',contract);

const art={schemaVersion:'laidies-newsstand-visual-producer-contract.v1',candidateId:story.id,producer:'/root/aft_school_story',storyBinding:{path:`${root}/story.json`,sha256:sha(`${root}/story.json`)},job:'Show one conversation growing from a simple exchange into a useful household checklist, without suggesting guaranteed correctness, safety or unattended control.',scene:'People-free adult home desk. A tablet shows one continuous blank conversation path that begins with two simple empty chat bubbles and leads visually to an editable checklist card. Three distinct appliance manuals sit beside the tablet with a pencil and small desk lamp.',mustShow:['One continuous conversation, not two mode panels','Three appliance manuals','Checklist card with blank ruled lines only','People-free home-use context'],mustNotShow:['People or hands','MAiVEN or TRAiLBLAZER','Claude or Anthropic logos','Readable text, letters, numbers or pseudo-text','Checkmarks, approval badges, shields or padlocks','Completion celebration or guaranteed-result symbolism','Workplace report, presentation deck or provider example','Multiple competing mode buttons'],style:{authority:'EDITORIAL_STYLE_AUG30 — adult editorial illustration',reference:{path:'/Users/alisoneakin/Projects/laidies-current-visual-references-20260906/operations/reference/current-art-styles.md',sha256:'ef118a70a2e14df2227a23cfd249cc274df597db46399265f6f7b1f63ee89b6f'},palette:'Navy/plum linework with cyan, pink, coral and yellow electric accents.',finish:'Crisp adult editorial pop-art, meaningful object action, halftone print texture, clean negative space; no glossy tech-ad look.'},output:{aspect:'3:2 landscape',candidatePath:`${root}/art/generated-v1.png`,proposedPublicPath:'assets/newsstand/claude-one-conversation-20260916.png',alt:story.heroVisual.alt,credit:story.heroVisual.credit},status:'READY_TO_RENDER'};
write('art/producer-contract.json',art);
write('art/prompt.txt',`Use case: illustration-story\nAsset type: 3:2 landscape NewsStand editorial hero\nPrimary request: Show one continuous Claude-style conversation developing from a quick exchange into a longer household task.\nScene/backdrop: People-free adult home desk.\nSubject: A tablet with one continuous blank conversation path: two simple empty chat bubbles flow into an editable checklist card. Three distinct appliance manuals, a pencil and a small desk lamp sit beside it.\nStyle/medium: Adult editorial pop-art, crisp navy and plum linework, cyan/pink/coral/yellow accents, subtle halftone print texture, meaningful object action, clean negative space.\nText: none. Checklist uses blank ruled lines only.\nConstraints: one conversation path, three manuals, one checklist; no people, hands, faces, MAiVEN, TRAiLBLAZER, logos, readable text, letters, numbers, pseudo-text, checkmarks, badges, shields, padlocks, completion celebration, guaranteed-result symbolism, workplace report, presentation deck, multiple mode buttons, glossy tech-ad look.`);
console.log(JSON.stringify({candidateId:story.id,storySha256:sha(`${root}/story.json`),sourceWords:sourceTotal,contractSha256:sha(`${root}/producer-contract.json`),artContractSha256:sha(`${root}/art/producer-contract.json`),library:libraryEntry.url},null,2));
