import fs from 'node:fs';
import crypto from 'node:crypto';
import {candidateReviewText} from '../../../../../scripts/validate-newsstand-ordinary-story-candidate.mjs';
import {inspectContentProducerContract} from '../../../../../scripts/check-content-producer-contract.mjs';
import {inspectProseQualityReview} from '../../../../../scripts/check-prose-quality-admission.mjs';
import {storyParagraphs} from '../../review-runtime/protocol.mjs';
import {prepareDraft} from '../../../../../scripts/prepare-newsstand-draft.mjs';

const d='operations/product-stewards/newsstand/candidates/claude-cowork-merge-20260916/';
const read=n=>fs.readFileSync(d+n,'utf8');
const j=n=>JSON.parse(read(n));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const bind=n=>({path:d+n,sha256:sha(read(n))});
const bindPath=p=>({path:p,sha256:sha(fs.readFileSync(p))});
const write=(n,x)=>fs.writeFileSync(d+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const s=j('story.json'), c=j('producer-contract.json'), source=j('source-packet.json'), coverage=j('story-type-coverage.json'), now=new Date().toISOString();
const artAdmission=bind('art/independent-review-v2.json');
c.visualAdmission=artAdmission;
write('producer-contract.json',c);

write('review-text.json',candidateReviewText(s));
write('rendered-article.html',`<article><h1>${s.headline}</h1><figure><img src="art/generated-v1.png" alt="${s.heroVisual.alt}"><figcaption>${s.heroVisual.credit}</figcaption></figure>${s.the_story}<h2>LAiDIES Read</h2>${s.laidies_read}<h2>What This Means for You</h2>${s.what_this_means}<h2>Cocktail Party</h2><p>${s.cocktail_party}</p><h2>Class Notes</h2><p>${s.class_notes}</p></article>\n`);
write('publication-manifest.json',{schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:s.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',reviewText:bind('review-text.json'),rendered:bind('rendered-article.html'),story:bind('story.json'),heroVisual:bind('art/generated-v1.png'),visualAdmission:artAdmission});
const writerInput={...prepareDraft(c,{root:process.cwd(),reportingFrame:coverage,sourcePacket:bind('source-evidence.json')}),producerContract:bind('producer-contract.json')};
write('writer-input-current.json',writerInput);

const blogUrl=s.sources[0].url, helpUrl=s.sources[1].url;
const claims=[
 {claimId:'event',claim:'Anthropic announced September 16 that Claude chat and Cowork are merging into one experience.',candidateEvidence:[{excerpt:'Anthropic announced September 16 that it is merging Claude chat and Cowork into one Claude experience.',locator:'The Story'}],sourceIds:['anthropic-cowork-merge-blog-20260916'],sourceEvidence:[{excerpt:'Starting today, Claude Cowork and chat are merging into one Claude.',locator:blogUrl}],scopeAndFreshness:'Official September 16 announcement, fully reread September 19.'},
 {claimId:'rollout',claim:'Rollout is gradual, beginning with Pro and Max; same-plan accounts can differ; Team and Free follow; Enterprise receives at least 30 days notice.',candidateEvidence:[{excerpt:'Rollout is gradual: Pro and Max first across web, desktop and mobile. Team and Free follow; Enterprise gets at least 30 days’ notice. Same-plan accounts may differ.',locator:'The Story'}],sourceIds:['anthropic-cowork-merge-blog-20260916','anthropic-cowork-merge-help-20260919'],sourceEvidence:[{excerpt:'This is rolling out to Pro and Max plans first, in the Claude app on web, desktop, and mobile over the coming weeks to existing and new users on these plans. There’s nothing to turn on. Team and Free plans will follow soon, and Enterprise admins will hear from us at least 30 days before anything changes for their organizations.',locator:blogUrl},{excerpt:'even accounts on the same plan will see the changes at different times',locator:helpUrl}],scopeAndFreshness:'Staged provider rollout, not universal availability; reread September 19.'},
 {claimId:'permissions',claim:'Manual asks before actions; Auto reduces check-ins; the setting covers the conversation.',candidateEvidence:[{excerpt:'Anthropic says Manual asks before actions; Auto reduces check-ins. The setting covers the conversation.',locator:'LAiDIES Read'}],sourceIds:['anthropic-cowork-merge-help-20260919'],sourceEvidence:[{excerpt:'Auto: Claude keeps working without stopping to ask about each step, and automated safety checks run before it takes an action.\nManual (default): Claude asks before it takes actions, and you choose whether to allow each one.\nThe setting applies to the whole conversation.',locator:helpUrl}],scopeAndFreshness:'Permission behavior documented September 19; no safety guarantee.'},
 {claimId:'execution',claim:'Local work requires Desktop open; cloud work may continue after laptop closure.',candidateEvidence:[{excerpt:'Local work needs Claude Desktop open; cloud work may continue after the laptop closes.',locator:'What This Means'}],sourceIds:['anthropic-cowork-merge-help-20260919'],sourceEvidence:[{excerpt:'Tasks that use files or apps on your computer need Claude Desktop open.\nMore involved tasks keep running in the cloud even if you close your laptop',locator:helpUrl}],scopeAndFreshness:'Documented behavior, not evidence of reliable completion.'}
];
const sources=[
 {id:'anthropic-cowork-merge-blog-20260916',url:blogUrl,authority:'Official Anthropic announcement for event identity and rollout statement.',source:{url:blogUrl,passage:claims[0].sourceEvidence[0].excerpt,additionalPassage:claims[1].sourceEvidence[0].excerpt,passageLocator:source.records[0].readScope},limitations:source.records[0].limitations.join(' ')},
 {id:'anthropic-cowork-merge-help-20260919',url:helpUrl,authority:'Official Anthropic help documentation for permissions and execution boundaries.',source:{url:helpUrl,passage:claims[2].sourceEvidence[0].excerpt,additionalPassage:claims[3].sourceEvidence[0].excerpt,passageLocator:source.records[1].readScope},limitations:source.records[1].limitations.join(' ')},
 {id:'anthropic-cowork-rollout-help-20260919',url:helpUrl,authority:'Official Anthropic help documentation for staged account timing.',source:{url:helpUrl,passage:claims[1].sourceEvidence[1].excerpt,passageLocator:source.records[1].readScope},limitations:'Provider documentation; staged timing can change.'}
];
write('editorial-input.json',{readerJob:`${c.readerContract.humanQuestion} ${c.readerContract.promisedPayoff}`,completeArtifact:read('review-text.json'),paragraphs:storyParagraphs(s),communicationAuthority:c.communicationDesign,claims,sources,reviewBoundary:{status:'PENDING_DISTINCT_INDEPENDENT_REVIEW',instruction:'Treat Anthropic as the source for its own product and rollout. Do not infer universal availability, task success, safety, privacy or reliability. Treat the appliance-manual task as an original low-stakes illustration.'}});

write('producer-observations.json',{schemaVersion:'laidies-newsstand-producer-observations.v1',candidateId:s.id,completeTextRead:true,storySha256:sha(JSON.stringify(s)),readerAnswers:{change:'A person can ask a quick question or hand over a longer, multi-step task without choosing a mode first.',access:'Team and Free follow; Enterprise gets at least 30 days’ notice.',permission:'Anthropic says Manual asks before actions; Auto reduces check-ins.',action:'inspect every date or safety instruction against the originals'},terms:{'multi-step task':'a longer, multi-step task without choosing a mode first',Manual:'Manual asks before actions'},explainBack:'Claude is removing the need to choose Chat or Cowork first. The same conversation can answer or carry out a longer task, while I still choose permissions.',unseenTransfer:'For a different agentic tool, I should check what it may access, when it asks and whether local work needs an app left open.',unresolvedIssues:[],repairsMade:['Reduced conservative Anthropic-derived visible wording from 228 to 172 words before review.','Bound a current Library authority-line section rather than inventing an anchor.','Separated staged plan rollout from same-plan account timing.','Added the nearest alternative, best-fit task, recognizable document and provider-evidence boundary required by the model-release preflight.','Placed Manual/Auto and local/cloud boundaries beside the personal-use example.'],limitations:['Producer AI simulations; no observed human comprehension test.','Both factual sources are Anthropic-owned product pages; no independent quality or adoption evidence.','Final public asset copy, ordinary assembly, issue admission, canonical write and deployment remain outside this lane.']});

const template=JSON.parse(fs.readFileSync('operations/product-stewards/newsstand/candidates/chatgpt-sponsored-agents-20260916/producer-publication-review.json','utf8'));
template.candidateId=s.id; template.maker='/root/aft_school_story'; template.reviewer={id:'/root/aft_school_story',principalId:'/root/aft_school_story',role:'Producer exact complete prose read',modelFamily:'openai'}; template.reviewedAt=now;
template.artifact={manifest:bind('publication-manifest.json'),reviewText:bind('review-text.json'),rendered:bind('rendered-article.html')};
template.reverseBrief={humanQuestion:c.readerContract.humanQuestion,promisedPayoff:c.readerContract.promisedPayoff,centralMentalModel:c.readerContract.centralMentalModel,dailyLifeConnection:c.readerContract.dailyLifeConnection,surfaceJob:c.readerContract.surfaceJob,desiredReaderFeeling:c.readerContract.desiredFeeling};
const obs=j('producer-observations.json');
const evidence={plainClarity:'A person can ask a quick question or hand over a longer, multi-step task without choosing a mode first.',readerValue:'LAiDIES would use the longer-work option when a task has named inputs and a document to check.',laidiesVoice:'attach three appliance manuals and ask Claude to make an editable seasonal-maintenance checklist',engagingEnjoyable:'The change removes a doorway; it does not promise every task will succeed.',factualIntegrity:'Those are vendor descriptions, not proof a task will finish well.',freshnessReviewability:'Anthropic announced September 16',surfaceFit:s.headline,datedChange:'Anthropic announced September 16 that it is merging Claude chat and Cowork into one Claude experience.',consequenceAndUncertainty:'Same-plan accounts may differ.',dailyLifeConnection:'attach three appliance manuals',communicationBenchmark:'what an agent may do, when it must ask and when it must stop',explainBack:obs.explainBack,unseenTransfer:obs.unseenTransfer,usefulAction:'inspect every date or safety instruction against the originals',analogyIntegrity:'attach three appliance manuals and ask Claude to make an editable seasonal-maintenance checklist'};
for(const [k,o] of Object.entries(template.outcomes)){o.verdict='PASS';o.observation='The complete producer read keeps the removed mode choice, staged rollout, permission boundary and one low-risk household task connected without promising performance.';o.artifactEvidence=[{excerpt:evidence[k]||s.headline,locator:'complete exact story'}];}
template.outcomes.explainBack.simulatedReaderProbe={prompt:c.readerContract.humanQuestion,probeResponse:obs.explainBack,expectedEvidence:'One conversation can answer or do longer work; access is staged and permissions remain a user choice.',transferResult:'PASS'};
template.outcomes.unseenTransfer.simulatedReaderProbe={prompt:'What should I check if another AI tool also removes its mode picker?',probeResponse:obs.unseenTransfer,expectedEvidence:'Check access, permission points, local execution requirements and result review.',transferResult:'PASS'};
template.outcomes.explainBack.artifactEvidence=[{excerpt:'A person can ask a quick question or hand over a longer, multi-step task without choosing a mode first.',locator:'The Story'}];
template.outcomes.unseenTransfer.artifactEvidence=[{excerpt:'Anthropic says Manual asks before actions; Auto reduces check-ins.',locator:'LAiDIES Read'}];
template.outcomes.analogyIntegrity.artifactEvidence=[{excerpt:'attach three appliance manuals and ask Claude to make an editable seasonal-maintenance checklist',locator:'What This Means'}];
for(const [k,f] of Object.entries(template.failureFamilies)){f.present=false;f.observation=`Actual read avoids ${k}: the dated merge, rollout boundary, permission mechanism and household transfer remain connected without a performance promise.`;f.artifactLocator='complete exact story';}
const input=bind('editorial-input.json');
template.factualReview={disposition:'CLAIMS_REVIEWED',sourceBindings:[input,bind('source-packet.json'),bind('source-observations.json')],claimMap:claims.map(x=>({...x,status:'QUALIFIED',sourceBinding:input})),reviewedThrough:'2026-09-19',nextTrigger:'Material rollout, plan, permission or execution change; or publication after September 19.',correctionOwner:'NewsStand product steward'};
template.ratchet={repeatedKnownDefects:0,objectiveDefectsFirstFoundAtReview:0,reviewIssues:0,reviewCycles:1,onKnownDefect:'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'};
template.lineage={kind:'FIRST',noComparableReason:'First story on the September 16 Claude chat/Cowork product merge; prior Anthropic stories cover different model, safety and research events.'};
template.learningDisposition={disposition:'NO_NEW_DEFECT',rationale:'Rollout, permission and local-versus-cloud distinctions were resolved before independent review.'};
template.verdict='PASS';template.limitations=obs.limitations;
write('producer-publication-review.json',template);
const contractCheck=inspectContentProducerContract(c,{root:process.cwd()});
const receiptCheck=inspectProseQualityReview(template,{root:process.cwd()});
write('contract-integrity.json',contractCheck);write('producer-self-review-check.json',receiptCheck);
const errors=[...contractCheck.errors,...receiptCheck.errors]; if(errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({status:'PRODUCER_SELF_REVIEW_PASS',story:bind('story.json'),reviewText:bind('review-text.json'),producerReview:bind('producer-publication-review.json'),sourceBudget:j('source-budget-final.json').totals},null,2));
