import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const packet='operations/product-stewards/town-entry-homepage/candidates/current-cards-type-20260906',hosted=!!process.env.CARDS_ORIGIN,origin=process.env.CARDS_ORIGIN||'https://1e77d547.laidies-sunnyvaile.pages.dev',stage=fs.readFileSync('/tmp/laidies-girl-talk-stage.txt','utf8').trim(),change=JSON.parse(fs.readFileSync(packet+'/changes.json'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceSha256=sha(fs.readFileSync('index.html'));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
const fontExpected='Jost, sans-serif';
try{for(const width of[1440,390])for(const kind of hosted?['hosted']:['parent','candidate']){
 const ctx=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:2,reducedMotion:'reduce'});
 if(!hosted){await ctx.route(origin+'/assets/**',r=>{const u=new URL(r.request().url()).pathname,local=u.slice(1),p=[...change.cards,change.fairyImage].some(c=>c.path===local)?local:stage+u;return fs.existsSync(p)?r.fulfill({path:p}):r.continue();});await ctx.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':'index.html'),contentType:'text/html'}));}
 const page=await ctx.newPage();const response=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});if(kind!=='parent')assert.equal(sha(await response.body()),sourceSha256);
 await page.waitForLoadState('networkidle');await page.evaluate(()=>document.fonts.ready);await page.locator('[data-dyk-slide]').first().locator('img').evaluateAll(is=>Promise.all(is.map(i=>i.decode())));
 await page.evaluate(()=>Promise.all(['/assets/homepage/pattern-purple-computing.png','/assets/homepage/pattern-retro-print-v2.png','/assets/homepage/did-you-know-question-mark-20260906.webp','/assets/library-reader/preface-burst-v1.png'].map(src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=reject;i.src=src;}))));
 const state=await page.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height};},font=e=>{const s=getComputedStyle(e);return{family:s.fontFamily,weight:s.fontWeight,size:s.fontSize,colour:s.color,stroke:s.webkitTextStrokeWidth};},first=document.querySelector('[data-dyk-slide]');return{overflow:document.documentElement.scrollWidth>innerWidth,media:box(first.querySelector('.dyk-media')),banner:box(document.querySelector('[data-dyk]')),images:[...first.querySelectorAll('img')].map(i=>({src:i.getAttribute('src'),natural:[i.naturalWidth,i.naturalHeight],box:box(i),rendering:getComputedStyle(i).imageRendering,inside:(()=>{const r=i.getBoundingClientRect(),p=i.parentElement.getBoundingClientRect();return r.left>=p.left&&r.right<=p.right&&r.top>=p.top&&r.bottom<=p.bottom;})()})),reference:font(document.querySelector('#feature-directory-title')),needs:font(document.querySelector('#intent-title')),messages:[...document.querySelectorAll('[data-dyk-slide]')].map(s=>({message:font(s.querySelector('h3,.dyk-title')),cta:font(s.querySelector('.dyk-cta')),text:s.textContent.replace(/\s+/g,' ').trim(),href:s.getAttribute('href'),radio:s.hasAttribute('data-ksvl-start-live')})),allText:document.querySelector('main').textContent.replace(/\s+/g,' ').trim(),allLinks:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),otherImages:[...document.querySelectorAll('main img')].filter(i=>!first.contains(i)).map(i=>i.getAttribute('src')).map(v=>v.includes('11-fairy-godmother-house.webp')||v.includes('fairy-writing-desk.png')?'CURRENT_FAIRY_ART':v),bodyBackground:getComputedStyle(document.body).backgroundImage,bannerBackground:getComputedStyle(document.querySelector('[data-dyk]')).backgroundImage};});
 const checkCards=r=>{assert.deepEqual(r.images.map(i=>i.src),change.cards.map(c=>'/'+c.path));assert(r.images.every(i=>i.natural[0]===933&&i.natural[1]===1400&&i.rendering==='auto'&&i.inside));};
 assert(!state.overflow);if(kind==='parent')assert.throws(()=>checkCards(state));else{checkCards(state);assert.equal(state.needs.stroke,'0px');for(const f of[state.needs,...state.messages.flatMap(m=>[m.message,m.cta])]){assert.equal(f.family,state.reference.family);assert.equal(f.weight,state.reference.weight);assert.equal(f.stroke,'0px');}}
 const capture=async(selector,name)=>{await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));const clip=await page.locator(selector).first().evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,width:r.width,height:r.height};});await page.screenshot({path:packet+'/'+kind+'-'+width+'-'+name+'.png',fullPage:true,clip,animations:'disabled'});};
 await capture('[data-dyk]','games');await capture('#today>div:first-child','needs');await capture('#feature-directory-title','reference');
 for(let n=0;n<5;n++)await page.locator('[data-dyk-next]').click();assert((await page.locator('[data-dyk-slide]').nth(5).innerText()).includes('NewsStand'));await capture('[data-dyk]','newsstand');
 await page.locator('[data-dyk-next]').click();const fairy=page.locator('[data-dyk-slide]').nth(6);await fairy.locator('img').evaluate(i=>i.decode());state.fairy=await fairy.locator('img').evaluate(i=>({src:i.getAttribute('src'),natural:[i.naturalWidth,i.naturalHeight],position:getComputedStyle(i).objectPosition}));if(kind!=='parent'){assert.equal(state.fairy.src,'/'+change.fairyImage.path);assert.deepEqual(state.fairy.natural,[1536,1024]);assert.equal(state.fairy.position,'0% 50%');}else assert.notEqual(state.fairy.src,'/'+change.fairyImage.path);await capture('[data-dyk]','fairy');await page.locator('[data-dyk-prev]').click();await page.locator('[data-dyk-prev]').click();assert(await page.locator('[data-dyk-slide]').nth(4).isVisible());
 rows.push({kind,width,dpr:2,...state,allText:sha(state.allText),allLinks:sha(JSON.stringify(state.allLinks)),otherImages:sha(JSON.stringify(state.otherImages)),controls:true});await ctx.close();
}}finally{await browser.close();}
if(!hosted)for(const width of[1440,390]){const a=rows.find(r=>r.kind==='parent'&&r.width===width),b=rows.find(r=>r.kind==='candidate'&&r.width===width);for(const k of['media','banner','allText','allLinks','otherImages','bodyBackground','reference'])assert.deepEqual(a[k],b[k],k+' retained');assert.deepEqual(a.messages.map(m=>[m.text,m.href,m.radio]),b.messages.map(m=>[m.text,m.href,m.radio]));assert.equal(a.needs.size,b.needs.size);assert.equal(a.messages.length,8);}
const luminance=rgb=>rgb.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),contrast=(a,b)=>{const x=[luminance(a),luminance(b)].sort((a,b)=>a-b);return(x[1]+.05)/(x[0]+.05);};
const mix=(a,b,t)=>a.map((v,i)=>v*t+b[i]*(1-t)),ink=[17,24,59],backgrounds=[mix([113,55,214],ink,.6),mix([36,87,230],ink,.5)],orange=[255,155,61],lime=[183,228,43];
const contrastChecks={bannerOrange:Math.min(...backgrounds.map(b=>contrast(orange,b))),bannerLime:Math.min(...backgrounds.map(b=>contrast(lime,b))),needsBlue:Math.min(...[[255,155,61],[255,115,102],[242,84,169]].map(b=>contrast([27,48,189],b)))};
assert(contrastChecks.bannerOrange>=4.5&&contrastChecks.bannerLime>=4.5&&contrastChecks.needsBlue>=3);
fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify({status:'PASS',sourceSha256,cards:change.cards,fairyImage:change.fairyImage,retiredFairyRejected:!hosted,retiredBoardRejected:!hosted,contrastChecks,rows},null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha256,contrastChecks,rows:rows.map(r=>({width:r.width,kind:r.kind,banner:r.banner,media:r.media,cards:r.images.map(i=>i.src),overflow:r.overflow}))}));
