/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker-operating-pilot/wrangler.jsonc --include-runtime=false worker-operating-pilot/worker-configuration.d.ts` (hash: e6a254a6e40a649b1acee6391067d7e1)
interface __BaseEnv_Env {
	FROZEN_RECEIPT_SHA256: "503a473018442c5a114586584dfd015c61503283b80784095e705b04b1a57b87";
	OPERATING_HANDOFF: Workflow<Parameters<import("./src/index").OperatingHandoffPilot['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FROZEN_RECEIPT_SHA256">> {}
}
