import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root=process.cwd(),packet=root+'/operations/product-stewards/town-entry-homepage/candidates/retro-page-background-20260906',asset='assets/homepage/rewind-wallpaper-20260906.webp',hosted=!!process.env.BACKGROUND_ORIGIN,origin=process.env.BACKGROUND_ORIGIN||'https://5706ad0d.laidies-sunnyvaile.pages.dev';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=process.env.CANDIDATE_ONLY?JSON.parse(fs.readFileSync(packet+'/checks.json')).rows.filter(r=>r.kind==='parent'):[];
try{for(const width of [1440,390])for(const kind of hosted?['hosted']:process.env.CANDIDATE_ONLY?['candidate']:['parent','candidate']){const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted){await ctx.route(origin+'/assets/**',r=>{const f='/var/folders/bj/tk6944ns7gn13syvg4d93cp00000gn/T/laidies-retro-background-rg1hwjcg/public'+new URL(r.request().url()).pathname;return fs.existsSync(f)?r.fulfill({path:f}):r.continue();});await ctx.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':root+'/index.html'),contentType:'text/html'}));await ctx.route('**/'+asset,r=>r.fulfill({path:root+'/'+asset,contentType:'image/webp'}));}
const page=await ctx.newPage();const resp=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});const sourceSha256=hash(await resp.body());await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>{document.querySelectorAll('img[loading="lazy"]').forEach(i=>i.loading='eager');});await page.evaluate(()=>Promise.all([...document.images].map(i=>Promise.race([i.decode().catch(()=>null),new Promise(ok=>setTimeout(ok,5000))]))));if(kind!=='parent')await page.evaluate(src=>new Promise((ok,bad)=>{const im=new Image();im.onload=ok;im.onerror=bad;im.src=src;}),'/'+asset);
const state=await page.evaluate(()=>{const cs=getComputedStyle(document.body);return {background:cs.backgroundImage,backgroundColour:cs.backgroundColor,backgroundSize:cs.backgroundSize,attachment:cs.backgroundAttachment,overflow:document.documentElement.scrollWidth>innerWidth,bodyHeight:document.body.scrollHeight,content:document.querySelector('main').textContent,links:[...document.querySelectorAll('main a')].map(a=>[a.textContent,a.getAttribute('href')]),panels:[...document.querySelectorAll('main>section,main>.postcard-band')].map(el=>{const s=getComputedStyle(el),r=el.getBoundingClientRect();return {id:el.id,classes:el.className,width:r.width,height:r.height,background:s.backgroundImage,colour:s.backgroundColor};}),bannerImages:[...document.querySelectorAll('.dyk-media')].map(el=>{const s=getComputedStyle(el);return {outline:s.outline,background:s.backgroundImage,image:el.querySelector('img')?.getAttribute('src')};})};});
assert(!state.overflow);if(kind!=='parent'){assert(state.background.includes(asset));assert.equal(state.backgroundSize,width===390?'480px 480px':'680px 680px');assert.equal(state.attachment,'scroll');assert.equal(sourceSha256,hash(fs.readFileSync(root+'/index.html')));}
await page.screenshot({path:packet+'/'+kind+'-'+width+'-full.png',fullPage:true,animations:'disabled'});await page.locator('.dyk-slim').scrollIntoViewIfNeeded();await page.screenshot({path:packet+'/'+kind+'-'+width+'-discovery.png',animations:'disabled'});await page.locator('.reference').scrollIntoViewIfNeeded();await page.screenshot({path:packet+'/'+kind+'-'+width+'-jeeves.png',animations:'disabled'});rows.push({width,kind,sourceSha256,...state});await ctx.close();}
// Visualize a 2x2 repetition at intended desktop scale; no pixel editing of the asset.
if(!hosted){const page=await browser.newPage({viewport:{width:1360,height:1360}});await page.route('https://wallpaper.invalid/tile.webp',r=>r.fulfill({path:root+'/'+asset,contentType:'image/webp'}));await page.setContent('<body style="margin:0;background:url(https://wallpaper.invalid/tile.webp) repeat;background-size:680px 680px"></body>');await page.evaluate(()=>new Promise((ok,bad)=>{const im=new Image();im.onload=ok;im.onerror=bad;im.src='https://wallpaper.invalid/tile.webp';}));await page.screenshot({path:packet+'/tile-repeat.png'});}
}finally{await browser.close();}
if(!hosted)for(const width of [1440,390]){const a=rows.find(r=>r.width===width&&r.kind==='parent'),b=rows.find(r=>r.width===width&&r.kind==='candidate');for(const k of ['content','links','panels','bannerImages','bodyHeight'])assert.deepEqual(a[k],b[k],k+' must be preserved');assert(!a.background.includes(asset),'negative control must reject missing wallpaper');}
const result={status:'PASS',sourceSha256:hash(fs.readFileSync(root+'/index.html')),assetSha256:hash(fs.readFileSync(root+'/'+asset)),parentSha256:hash(fs.readFileSync(packet+'/parent.html')),missingWallpaperRejected:hosted?undefined:true,rows};fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha256:result.sourceSha256,rows:rows.length}));
