import fs from 'node:fs';import crypto from 'node:crypto';
import {reviewedContentSha256} from '../../../../../scripts/prepare-newsstand-service-bank.mjs';
import {enforcedFailureFamilies,inspectProseQualityReview} from '../../../../../scripts/check-prose-quality-admission.mjs';
const dir='operations/product-stewards/newsstand/candidates/curiosity-bank-20260910',ev='operations/product-stewards/newsstand/evidence/curiosity-bank-20260910';
const read=p=>fs.readFileSync(p,'utf8'),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),bind=p=>({path:p,sha256:hash(read(p))});
const draft=JSON.parse(read(dir+'/draft.json')),registryPath='operations/product-stewards/learning-content-ecosystem/content-quality-exemplars.json',registry=JSON.parse(read(registryPath));
const template=JSON.parse(read('operations/product-stewards/newsstand/evidence/service-bank-20260830/producer-receipts/paige-02-fix-one-thing.json'));
const now=new Date().toISOString();fs.mkdirSync(ev+'/producer-receipts',{recursive:true});
const notes=`# Producer full-bank inspection\n\nRoot read the exact thirty entries in draft.json and review-text.md. Activities each name a situation and a bounded act. Entries1/8/21 distinguish asking for an example, asking for a missing step and explaining back;3/9/14/24 distinguish tone comparison, changing one input, choosing a criterion and checking unsupported additions. Credit, private invitations, introductions, listening and offers keep the other person's choice. No entry requires a workplace, purchase, public post or compulsory mentoring. Dry humour is sparse; no quotation is attributed to a real person. Example speech is presented as wording to try, not a reported event.\n\nMaker pilot repair replaced forced acceptance/rejection of one AI change with conditional acceptance, since no defect or improvement may exist. Entry24 explicitly allows no additions to be found. These are original activity suggestions, not claims of measured effectiveness. No human testing, independent review, publication or useful outcome from a real reader is claimed.\n\nThe simulations in individual receipts are root-authored editorial probes with different situations. They assess portability of the instruction only. The bank still requires independent exact-prose review and dated admission.\n`;
fs.writeFileSync(ev+'/producer-notes.md',notes);
const transfers=[
['An unexplained charge appears on a phone bill.','Ask for an example of when that charge applies, then check your understanding against the bill.'],
['A neighbour found a useful repair guide you are forwarding.','Name her contribution with the link and keep private details out.'],
['An AI rewrite of an invitation sounds unlike you.','Compare the wording to the original meaning and keep only changes that help.'],
['A post claims a swimming pool has closed permanently.','Find the original notice and check whether it actually describes a temporary closure.'],
['A volunteer group is ready to agree on a rota.','Invite unanswered questions and resolve the unclear slot before agreement.'],
['Your sister is upset about a cancelled trip.','Ask whether she wants listening, ideas or help with one task before acting.'],
['A friend sends clear travel directions.','Tell her which landmark made the route easy to follow.'],
['A recipe says to prepare a pan but does not say how.','Ask for the missing preparation step and try it before continuing.'],
['An AI description for a community notice is too formal.','Change only the tone instruction and compare the new version against the same purpose.'],
['You spot a local class a friend might enjoy.','Check its availability and send the date, cost and reason it might suit her, without pressure.'],
['A group always meets in the same cafe.','Ask whether people still prefer it before treating familiarity as agreement.'],
['Two acquaintances have a shared interest in repairing bicycles.','Ask both privately before connecting them and state the specific shared interest.'],
['Someone wants to learn to crop a photo.','Show the first step and let her try it rather than only sending the finished crop.'],
['You want AI to improve a short event description.','Name one goal such as clearer location details and judge the revision against it.'],
['A neighbour cannot attend a planning discussion.','Offer to receive her question beforehand and ask permission to bring it to the group.'],
['A friend forwards a reopened venue announcement.','Check the announcement year and actual reopening date before relying on it.'],
['A book group has an old rule about meeting length.','Ask what the rule was for, then suggest a small trial only if the group wants a change.'],
['A friend asks for your packing checklist.','Remove personal details and explain which parts depend on her trip.'],
['Someone is talked over at a family planning conversation.','Invite her to finish her point in her own words.'],
['An outing depends on whether a venue has step-free access.','Write the missing question down and check with the venue before finalising the plan.'],
['You read instructions for borrowing an ebook.','Put them aside, explain the process, and revisit the step you cannot explain.'],
['A friend wants feedback on a party invitation.','Ask what she wants to keep and point to the exact wording that confused you.'],
['Guests are coming to an unfamiliar community hall.','Check that your directions include the correct entrance and time.'],
['An AI draft says you will bring dessert, which you never promised.','Remove or verify the commitment before using the draft.'],
['You send a friend a guide about online privacy settings.','Include the specific question it answered for you so she can judge its relevance.'],
['A friend has a busy week.','Offer one manageable task, agree on it and respect a decline.'],
['You disagree about which picnic location to choose.','Name information such as shade or travel time that would change each preference and check it.'],
['You found the setting that fixes a display problem.','Note the step and device/version so you or someone else can repeat it in the right situation.'],
['A group wants to book a paid workshop.','Ask privately about cost, time and access before finalising the booking.'],
['A useful question about transport was skipped during planning.','Return to that question, credit its author and identify how to get an answer.']];
const types=['paige_tip','career_life','concept_week','mme_claio','dear_miss_jeeves','whats_new_sunnyvaile','crossword','did_you_know'];const items=[],artifacts=[];
for(const [i,e] of draft.items.entries()){
 const id=`curiosity-${String(i+1).padStart(2,'0')}-${e.id}`,stem=ev+'/'+id;
 const item={id,type:'curiosity',classification:'sourced_service',headline:e.headline,summary:e.body,body:[e.body],sourceLinks:[],destination:null,destinationLabel:'Try this today',sourcePath:dir+'/brief.md',sourceId:id,sourceSha256:hash(read(dir+'/brief.md')),owner:'newsstand-daily',freshness:{lastCheckedAt:'2026-09-10',expiresAt:'2026-10-10',recheckTriggers:['Change to activity meaning, source brief, relevant product behavior or publication context; refresh before expiry without automatic date renewal.']},status:'CANDIDATE',publicEligibility:'INELIGIBLE',reviewEvidence:{accuracy:null,editorial:null,voice:null,format:null,owner:null,safety:null}};
 item.reviewedContentSha256=reviewedContentSha256(item);items.push(item);fs.writeFileSync(stem+'.md',`# ${e.headline}\n\n${e.body}\n`);
 const manifest={schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:id,surface:'NEWSSTAND_RECURRING_SERVICE_COLUMNS',contentClass:'PRACTICE',reviewText:bind(stem+'.md'),reviewedContentSha256:item.reviewedContentSha256,producerContract:bind(dir+'/producer-contract.json')};fs.writeFileSync(stem+'.manifest.json',JSON.stringify(manifest,null,2)+'\n');
 const r=structuredClone(template);r.candidateId=id;r.reviewedAt=now;r.encodedAt=now;r.producerNotes=bind(ev+'/producer-notes.md');r.artifact={reviewText:bind(stem+'.md'),manifest:bind(stem+'.manifest.json')};r.calibration.registrySha256=hash(read(registryPath));r.calibration.reviewedAt=now;
 const evidence=[{excerpt:e.body,locator:id+': complete activity'}];r.reverseBrief={humanQuestion:e.headline,promisedPayoff:'One bounded action: '+e.body.split('. ')[0]+'.',centralMentalModel:'Try a specific act, then judge the response without assuming a guaranteed outcome.',dailyLifeConnection:transfers[i][0],surfaceJob:'One optional short Daily activity, not a compulsory challenge or quotation.',desiredReaderFeeling:'Respected, curious and free to use or skip this activity.'};
 const observations={plainClarity:'The entry names the situation and tells the reader exactly what to do in ordinary language.',readerValue:'The action is small enough to try in the named situation and does not require a purchase, job role or public post.',laidiesVoice:'Direct adult wording; example speech is a suggestion, not an invented attribution. No confidence-deficit framing.',engagingEnjoyable:'The recognisable situation and specific next move give this short activity a purpose without a grand moral.',factualIntegrity:'Original advice, not a reported event, quotation, capability guarantee or empirical effectiveness claim.',freshnessReviewability:'No current provider version, legal or medical fact is asserted; recheck if the task meaning or product behavior changes.',surfaceFit:'One short headline and self-contained paragraph fit the existing Daily activity desk.',retrievalOrPractice:'The reader can practise the named act rather than merely agree with a slogan.',practiceFeedback:'The action asks the reader to notice the response, clarity or concrete result described in this entry; no forced successful outcome.',communicationBenchmark:'A human situation, specific action and retained choice provide a proportional communication arc; no imitation or decorative analogy.',unseenTransfer:'The root-authored probe applies the act to a different situation; it is editorial simulation, not a human observation.',recoveryRoute:'The reader can ask about the unresolved point, keep the original, decline an offer or skip an inapplicable activity; the instruction does not demand success.'};
 r.outcomes={};for(const [name,observation] of Object.entries(observations))r.outcomes[name]={verdict:'PASS',observation:`${e.headline} ${observation}`,artifactEvidence:evidence};r.outcomes.unseenTransfer.simulatedReaderProbe={prompt:transfers[i][0]+' How would you apply the activity?',probeResponse:transfers[i][1],expectedEvidence:'Apply the same bounded action in the new context while keeping individual choice and checking the result.'};
 r.failureFamilies={};for(const family of enforcedFailureFamilies(registry))r.failureFamilies[family]={present:false,observation:`${e.headline} The complete entry stays with one concrete action and ordinary words; no disconnected glossary, borrowed quote, effectiveness promise or extended technical explanation is present.`,artifactLocator:id+': complete activity'};
 r.factualReview={disposition:'NO_MATERIAL_CLAIMS',rationale:'Original optional activity advice and clearly proposed example wording; no measured benefit, reported event, attributed quotation or guaranteed AI behavior.',claimScan:{observation:'Read every sentence for implied facts; the entry instructs an action and observation rather than claiming a result occurred.',artifactEvidence:evidence},reviewedThrough:'2026-09-10',nextTrigger:item.freshness.recheckTriggers[0],correctionOwner:'newsstand-daily'};r.ratchet={repeatedKnownDefects:0,objectiveDefectsFirstFoundAtReview:0,reviewIssues:0,reviewCycles:0,onKnownDefect:'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'};r.lineage={kind:'FIRST',noComparableReason:'First formal review of this original activity; pilot repair and full-bank maker inspection are preserved.'};r.learningDisposition={disposition:'NO_NEW_DEFECT',rationale:'No new reusable defect found in this exact activity; conditional-result pilot repair applied before full bank.'};r.limitations=['Producer exact-prose assessment only; independent semantic admission, public rendering and dated publication remain outstanding.','Transfer is a root-authored simulation, not observed human evidence.'];
 const result=inspectProseQualityReview(r);if(result.errors.length)throw Error(id+': '+result.errors.join('; '));fs.writeFileSync(ev+'/producer-receipts/'+id+'.json',JSON.stringify(r,null,2)+'\n');artifacts.push({id,type:'curiosity',contentClass:'PRACTICE',reviewText:bind(stem+'.md'),manifest:bind(stem+'.manifest.json'),reviewedContentSha256:item.reviewedContentSha256});
}
fs.writeFileSync(dir+'/bank.json',JSON.stringify({schemaVersion:'newsstand-service-bank-v1',updatedAt:'2026-09-10',requiredTypes:types,items},null,2)+'\n');fs.writeFileSync(ev+'/index.json',JSON.stringify({artifacts,sources:[{id:'original-activity-brief',...bind(dir+'/brief.md')}]},null,2)+'\n');console.log('30 producer records encoded after full prose inspection; all integrity checks matched; no independent/public admission');
