import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root=process.cwd(),out=root+'/operations/product-stewards/town-entry-homepage/candidates/homepage-closeout-20260906';const origin=process.env.CLOSEOUT_ORIGIN||'https://9e7e828c.laidies-sunnyvaile.pages.dev',local=!process.env.CLOSEOUT_ORIGIN,stage=fs.readFileSync('/tmp/laidies-activity-spacing-stage.txt','utf8').trim();
fs.copyFileSync('_worker.js','/tmp/laidies-search-browser-worker.mjs');const {default:worker}=await import(pathToFileURL('/tmp/laidies-search-browser-worker.mjs'));let paid=0;const env={ASSETS:{fetch:async req=>{const f=stage+new URL(req.url).pathname;return fs.existsSync(f)?new Response(fs.readFileSync(f.endsWith('/content/site/miss-jeeves-index.json')?root+'/content/site/miss-jeeves-index.json':f)):new Response('',{status:404});}},AI:{run(){paid++;throw Error('Paid call')}},FAIRY_AI:{fetch(){paid++;throw Error('Paid call')}}};
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try{for(const width of [1440,390]){const context=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
if(local)await page.route('**/api/miss-jeeves',async route=>{const response=await worker.fetch(new Request(route.request().url(),{method:'POST',headers:{'content-type':'application/json'},body:route.request().postData()}),env,{});await route.fulfill({status:response.status,contentType:'application/json',body:await response.text()});});
await page.goto(origin+'/',{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);const answers=[];
for(const [q,expected] of [['Why does AI make things up?','11.6 — Hallucination: Why It Makes Things Up'],['What is a context window?','Context window'],['How do I write a better prompt?','2.3 The Brief (Not the Prompt)'],['How do I repair a leaking bicycle tyre?',null]]){
 await page.locator('#lookup').fill(q);const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/miss-jeeves')&&r.request().method()==='POST');await page.locator('#homepage-jeeves-form [type=submit]').click();const response=await responsePromise;const payload=await response.json();assert.equal(payload.mode,'site-search');assert.equal(response.request().postDataJSON().intent,'search');await page.locator('#homepage-jeeves-answer[aria-busy=false]').waitFor();
 const text=await page.locator('#homepage-jeeves-answer').innerText();if(expected)assert.equal(await page.locator('#homepage-jeeves-answer li a').first().innerText(),expected);else assert.equal(await page.locator('#homepage-jeeves-answer a').count(),0);
 assert(!/Read the full explanation\s*\.|Put it into practice\s*\./.test(text));assert.equal(page.url(),origin+'/');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#homepage-jeeves-answer').scrollIntoViewIfNeeded();const image=`${local?'candidate':'hosted'}-${width}-${answers.length+1}.png`;await page.screenshot({path:out+'/'+image});answers.push({query:q,status:response.status(),payload,text,image});
}
rows.push({width,answers,errors});assert.deepEqual(errors,[]);await context.close();console.log(local?'Candidate':'Hosted','browser checked',width);}}
finally{await b.close();fs.writeFileSync(out+'/'+(local?'browser-checks.json':'hosted-checks.json'),JSON.stringify({origin,localWorker:local,paidCalls:paid,rows},null,2));}
assert.equal(paid,0);
