import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const [target,out,mode='candidate']=process.argv.slice(2),remote=/^https?:/.test(target),root=remote?null:path.resolve(target),fixed='2026-09-06T05:30:00Z';fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.mp3':'audio/mpeg','.webp':'image/webp'};
const server=remote?null:http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),name=u.pathname==='/newsstand'?'/newsstand.html':u.pathname==='/library'?'/library.html':u.pathname;const file=path.join(root,name);if(!file.startsWith(root+'/')||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=remote?target:'http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),results=[];
try {for(const [zone,width] of [['UTC',1280],['America/Vancouver',390],['Asia/Tokyo',320]]){
const context=await browser.newContext({viewport:{width,height:900},timezoneId:zone});const page=await context.newPage();await page.clock.install({time:new Date(fixed)});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/newsstand.html#newsstand-catchup',{waitUntil:'networkidle'});const wiki=page.locator('.ns-catchup-item').filter({has:page.locator('a[href="#openai-wiki-message-board-2026-09-05"]')});await wiki.waitFor({state:'visible'});const catchupDate=await wiki.locator('time').textContent();const town=await page.locator('#ns-town-date').evaluate(el=>({text:el.textContent,dateTime:el.dateTime}));await wiki.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`catchup-${width}.png`)});await wiki.locator('a').click();await page.locator('.ns-article').waitFor({state:'visible'});const articleDate=await page.locator('#ns-reader-date').textContent();const articleText=await page.locator('.ns-article').innerText();await page.screenshot({path:path.join(out,`article-${width}.png`)});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.locator('#ns-return').click();
const archive={};
for(const day of ['2026-09-05','2026-09-06']){
 await page.locator('#ns-archive-from').fill(day);await page.locator('#ns-archive-to').fill(day);await page.locator('#ns-browse-all').click();
 archive[day]=await page.locator('#paper-counter a.ns-front-story[href]').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
 if(day==='2026-09-05'){await page.locator('#ns-reader-title').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`archive-${width}.png`)});}
}
if(mode==='candidate')for(const id of ['openai-wiki-message-board-2026-09-05','us-doj-openai-copyright-2026-09-05']){assert.ok(archive['2026-09-05'].includes('#'+id),'September 5 includes '+id);assert.ok(!archive['2026-09-06'].includes('#'+id),'September 6 excludes '+id)}
const row={zone,width,catchupDate,articleDate,town,archive,overflow,errors};results.push(row);assert.equal(overflow,false);assert.deepEqual(errors,[]);assert.ok(articleText.includes('wiki'));
if(mode==='candidate'){assert.equal(catchupDate,'September 5, 2026');assert.ok(articleDate.includes('September 5, 2026'));assert.equal(town.dateTime,'2026-09-05');assert.ok(town.text.includes('September 5, 2026'));}await context.close();}
if(mode==='incumbent')assert.ok(results.some(x=>x.catchupDate==='September 6, 2026'),'incumbent must expose wrong-day defect');fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({scope:'Actual whole-page browser at a fixed post-admission test instant; no publication/content freshness claim',fixed,mode,base,results},null,2)+'\n');console.log(JSON.stringify({mode,results}));}finally{await browser.close();if(server)await new Promise(r=>server.close(r))}
