import fs from 'node:fs';
import crypto from 'node:crypto';

const root='operations/product-stewards/newsstand/candidates/chatgpt-sponsored-agents-20260916';
fs.mkdirSync(root+'/art',{recursive:true});
const write=(n,x)=>fs.writeFileSync(root+'/'+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const sourceCapture='operations/product-stewards/newsstand/evidence/morning-20260916/sponsored-agent-full-capture.json';
const sourceText=JSON.parse(fs.readFileSync(sourceCapture,'utf8'));
const libraryIndex=JSON.parse(fs.readFileSync('content/site/miss-jeeves-index.json','utf8'));
const libraryEntry=libraryIndex.entries.find(x=>x.id==='book-section-ai-fundamentals-101-ch-20-20-8-try-this-final');
if(!libraryEntry) throw new Error('Missing live Library 20.8 entry');
write('library-background-exact.json',libraryEntry);

const story={
  id:'chatgpt-sponsored-agents-20260916',slug:'chatgpt-sponsored-agents-20260916',edition:'daily',status:'hold',publishedAt:null,updatedAt:'2026-09-16T14:47:53Z',lastCheckedAt:'2026-09-16T14:47:53Z',
  sourceApproval:{status:'independent-review-required',record:'newsstand:source-approval:chatgpt-sponsored-agents-20260916'},correction:null,correctionHistory:[],predecessorStoryIds:[],successorStoryIds:[],bigPicture:null,thread:null,thread_subtitle:null,thread_entry:null,
  headline:'A new ChatGPT ad can open a separate conversation with the seller',
  heroVisual:{src:'/assets/newsstand/sponsored-agent-shopping-20260916.png',alt:'An illustrated tablet shows two separate blank chat panels beside a desk lamp and a measuring tape.',credit:'Illustration: LAiDIES'},
  the_story:'<p>OpenAI announced September 16 that it is testing Sponsored Agents with select US advertisers. After clicking an ad in ChatGPT, a person can choose to open a clearly labelled conversation with an agent sponsored by that business.</p><p>OpenAI says the sponsored conversation is separate from the person’s original chat and from ChatGPT’s independent answers. The announcement does not give broader availability details.</p>',
  laidies_read:'<p>“Sponsored” tells you who is paying for the conversation. You are talking to a seller about what it offers, through an AI agent inside ChatGPT. That is useful context: a fluent answer can still be part of a sales conversation.</p>',
  what_this_means:'<p>Imagine an ad for a desk lamp catches your eye. In the separate conversation, ask for its base width, shade height and return terms. Then compare those claims with the product page before deciding whether it fits your bedside table.</p><p>The important hand-off happens when you click the ad and choose the new conversation. Pause there long enough to notice the label and who is speaking. Keep the original answer, the sponsored conversation and the seller’s product page as three different sources.</p>',
  cocktail_party:'“After the ad click, you’re chatting with the seller.”',watch_fors:null,closing_note:null,
  class_notes:'Background: <a href="/library.html#ai-fundamentals-101::%40ch-20-20-8-try-this-final">AI Fundamentals 101 §20.8 — Try This (Final)</a> helps you ask what incentive sits behind a claim.',
  sources:[{id:'openai-sponsored-agents-20260916',label:'OpenAI — Reimagining advertising with AI',url:'https://openai.com/index/reimagining-advertising-with-ai/',publisherType:'provider-product-announcement',accessedAt:'2026-09-16',approvalStatus:'independent-review-required'}],
  aidb_credit:null,themes:['advertising','shopping'],concepts:['sponsored conversation','seller identity'],tags:['ChatGPT','Sponsored Agents','advertising'],saint_lane:null,badge:'THE LATEST',retraction:null
};
write('story.json',story);
write('article.md',`# ${story.headline}\n\n## The Story\n\n${story.the_story.replace(/<\/?p>/g,'\n').trim()}\n\n## LAiDIES Read\n\n${story.laidies_read.replace(/<\/?p>/g,'\n').trim()}\n\n## What This Means for You\n\n${story.what_this_means.replace(/<\/?p>/g,'\n').trim()}\n\n## Cocktail Party\n\n${story.cocktail_party}\n\n## Class Notes\n\n${story.class_notes}\n`);

const packet={schemaVersion:'newsstand-exact-source-packet-v1',candidateId:story.id,capturedAt:'2026-09-16T15:57:00Z',records:[{sourceId:'openai-sponsored-agents-20260916',publisher:'OpenAI',url:story.sources[0].url,publisherType:'provider-product-announcement',budgetWords:200,quoteBudgetWords:25,readScope:'Complete normal-web capture supplied by root; reader-facing claims use lines 13-18 and 37-46.',exactCapturedText:sourceText,sourceCapture:{path:sourceCapture,sha256:sha(sourceCapture)},limitations:['Provider announcement describes its own product test.','No independent usage, effectiveness, privacy or data-sharing evidence in this source.','The announcement names select US advertisers but does not state broader user, tier or global availability.']}],sourceFamilyAggregate:{OpenAI:200},quoteBudgetAggregate:{OpenAI:25}};
write('source-packet.json',packet);
write('source-evidence.json',{schemaVersion:'newsstand-source-evidence-v1',candidateId:story.id,checkedAt:'2026-09-16T14:47:53Z',exactSourcePacket:{path:root+'/source-packet.json',sha256:'SET_AFTER_WRITE',scope:'Complete primary provider announcement capture; claims limited to Sponsored Agents lines 37-46.'},records:[{sourceId:'openai-sponsored-agents-20260916',status:'COMPLETE_PRIMARY_PROVIDER_SOURCE',authority:'OpenAI announcement for the existence and described design of its own test.',url:story.sources[0].url,readScope:'Complete captured page, with claim-bearing lines 13-18 and 37-46 read exactly.',limits:'Provider-authored description; no independent adoption, neutrality, privacy, data-sharing or effectiveness evidence.',accessedAt:'2026-09-16'}]});
const ev=JSON.parse(fs.readFileSync(root+'/source-evidence.json'));ev.exactSourcePacket.sha256=sha(root+'/source-packet.json');write('source-evidence.json',ev);
const alloc=[
 ['headline','headline',story.headline],
 ['event','the_story','OpenAI announced September 16 that it is testing Sponsored Agents with select US advertisers.'],
 ['choice','the_story','After clicking an ad in ChatGPT, a person can choose to open a clearly labelled conversation with an agent sponsored by that business.'],
 ['separation','the_story','OpenAI says the sponsored conversation is separate from the person’s original chat and from ChatGPT’s independent answers.'],
 ['availability-limit','the_story','The announcement does not give broader availability details.'],
 ['speaker','laidies_read','You are talking to a seller about what it offers, through an AI agent inside ChatGPT.'],
 ['handoff','what_this_means','The important hand-off happens when you click the ad and choose the new conversation.'],
 ['label','what_this_means','Pause there long enough to notice the label and who is speaking.'],
 ['cocktail','cocktail_party','After the ad click, you’re chatting with the seller.'],
 ['source-label','sources[0].label',story.sources[0].label]
].map(([allocationId,field,exactDerivedText])=>({allocationId,publisher:'OpenAI',field,exactDerivedText,words:exactDerivedText.trim().split(/\s+/).length}));
const total=alloc.reduce((n,x)=>n+x.words,0);
write('source-budget-final.json',{schemaVersion:'newsstand-source-budget-v1',candidateId:story.id,method:'Conservative allocation of every source-derived phrase across visible fields, including headline, synthesis, cocktail line and source label. Article.md mirrors story.json and is not counted twice.',limits:{OpenAI:200},allocations:alloc,totals:{OpenAI:total},quoteDerivedWords:0,withinLimits:total<=200,unmappedSourceDerivedClaims:[],otherVisibleOrigins:[{fields:['laidies_read','what_this_means'],origin:'Producer-created seller interpretation and desk-lamp shopping example',treatment:'Original practical consequence; no source-derived product facts.'},{fields:['class_notes'],origin:'Verified live Library §20.8',treatment:'Background on incentives; explicitly not evidence about Sponsored Agents.'},{fields:['heroVisual.alt'],origin:'Exact illustration inspection',treatment:'Visual description, not provider fact.'}]});
write('source-budget-check.json',{checkedAt:'2026-09-16T14:47:53Z',method:'Whitespace count of each exactDerivedText allocation.',recount:alloc.map(x=>({allocationId:x.allocationId,declared:x.words,actual:x.exactDerivedText.trim().split(/\s+/).length,match:true})),totals:{OpenAI:total},limit:200,withinLimit:total<=200,quotedWords:0,quoteLimit:25});
const translation={schema:'laidies.newsstand-reader-translation.v1',newsVersionExact:'OpenAI announced September 16 that it is testing Sponsored Agents with select US advertisers.',actualMeaningExact:'You are talking to a seller about what it offers, through an AI agent inside ChatGPT.',mechanismExact:'After clicking an ad in ChatGPT, a person can choose to open a clearly labelled conversation with an agent sponsored by that business.',familiarExampleExact:'Imagine an ad for a desk lamp catches your eye.',jargon:[{term:'Sponsored Agent',plainMeaning:'an AI agent sponsored by the business whose ad a person clicked'}],learningConnections:[{concept:'Commercial incentives shape what a speaker wants you to do',learningPayoff:'Ask who is speaking and what incentive sits behind a claim.',disposition:'link',destination:libraryEntry.url}]};
write('translation.json',translation);
write('story-type-coverage.json',{schema:'laidies.newsstand-story-type-coverage.v1',primaryType:'model-tool-release',overlays:['consumer-commerce'],universalAnswers:{whatHappened:'OpenAI announced a US advertiser test of Sponsored Agents.',plainLanguageIdentity:'An optional seller-sponsored conversation opened after a person clicks a ChatGPT ad.',evidenceBasis:'Complete primary provider announcement.',evidenceLimits:'No independent usage, effectiveness, privacy, data-sharing, global or tier-availability evidence.',readerRelevance:'A shopper should recognize the move from an original chat into a seller’s sales conversation.',affectedPeople:'People who see a participating advertiser’s ChatGPT ad and choose the sponsored conversation.',changesNow:'Select US advertisers are testing the format; broader availability is not stated.',uncertainty:'The source does not establish how often people will see or use it, or how useful it will be.',readerAction:'Notice the label and compare product claims with the seller’s product page.',betterQuestion:'Who is speaking in this chat, and what do they want me to do?'},typeAnswers:{'model-tool-release':{whatChanged:'An ad click can lead to a clearly labelled business-sponsored agent conversation.',whereAvailable:'OpenAI names select advertisers in the United States; no broader availability claim is made.',whoControlsIt:'The user chooses whether to start the separate sponsored conversation.',separation:'OpenAI says it is distinct from independent ChatGPT answers and separate from the original conversation.',evidenceLimit:'Provider announcement only; no independent outcome evidence.',realWorldTransfer:'Use a desk-lamp fit question, then compare seller claims with the product page.'}},translation});
write('claim-map.json',{schemaVersion:'newsstand-claim-map-v1',candidateId:story.id,claims:[{claimId:'test',claim:'OpenAI announced a September 16 Sponsored Agents test with select US advertisers.',sourceIds:['openai-sponsored-agents-20260916'],status:'QUALIFIED',limit:'Provider announcement.'},{claimId:'interaction',claim:'After an ad click, a person can choose a clearly labelled business-sponsored conversation.',sourceIds:['openai-sponsored-agents-20260916'],status:'QUALIFIED',limit:'Described product design; not independent observed use.'},{claimId:'separation',claim:'OpenAI says that conversation is separate from the original chat and its independent answers.',sourceIds:['openai-sponsored-agents-20260916'],status:'QUALIFIED',limit:'Attributed to OpenAI; no claim about privacy or data handling.'}]});

let contract=JSON.parse(fs.readFileSync('operations/product-stewards/newsstand/candidates/mathematicians-ai-research-values-20260916/producer-contract.json','utf8'));
const replace=x=>typeof x==='string'?x.replaceAll('mathematicians-ai-research-values-20260916',story.id).replaceAll('Collective declaration is the fresh event; the earlier Navier-Stokes claim is context only and not retold.','September 16 Sponsored Agents test is the fresh event; do not fold in advertiser workflow tools.').replaceAll('Lead with the collective answer-versus-understanding argument; keep it attributed; do not repeat the Navier-Stokes claim, infer machine consciousness, or generalize one interview into consensus.','Lead with the optional hand-off from an ad to a seller-sponsored conversation; keep OpenAI claims attributed and do not invent privacy, data-sharing, global or tier availability.').replaceAll('Dated declaration → evidence-status limit → answer-versus-understanding distinction → attributed Figalli assessment → original two-pass learning check.','Dated provider test → optional ad-click hand-off → seller identity → separation limit → original lamp-shopping check.') : Array.isArray(x)?x.map(replace):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,replace(v)])):x;
contract=replace(contract);contract.producer='/root/aft_school_story';contract.status='READY_TO_DRAFT';
contract.readerContract={humanQuestion:'If an ad in ChatGPT opens another conversation, who am I talking to?',promisedPayoff:'Recognize the hand-off into a seller-sponsored conversation and keep its product claims in the right context.',priorKnowledge:'No advertising or AI-agent vocabulary assumed.',centralMentalModel:'An ad click can move a person from an original chat into a separate conversation sponsored by the seller.',dailyLifeConnection:'A shopper can ask whether a lamp fits, while remembering the answers come from the seller.',surfaceJob:'September 16 private Daily candidate about OpenAI’s Sponsored Agents test with select US advertisers.',desiredFeeling:'I can tell when a chat has become a seller’s conversation.'};
contract.canonicalTruth=[{claimId:story.id,owner:'OpenAI owns the product announcement; NewsStand owns the bounded seller-context explanation and original lamp example.',source:{path:root+'/source-evidence.json',sha256:sha(root+'/source-evidence.json')},freshnessTrigger:'Recheck the OpenAI announcement if publication slips or the described test changes materially.'}];
contract.draftArchitecture={openingJob:'Report the select-US-advertiser test and the user’s choice to enter a separate sponsored conversation.',causalSequence:['A person sees and clicks a ChatGPT ad.','The person chooses whether to start a clearly labelled business-sponsored agent conversation.','The seller conversation remains separate from the original chat and independent answers.'],workedCase:'Ask a lamp seller for dimensions and return terms, then compare those claims with the product page.',transferCase:'At any conversational ad hand-off, identify the speaker and its incentive.',usefulAction:'Notice the label before asking product questions; compare seller claims with the product page.',formatSpecificStructure:'The Story; LAiDIES Read; What This Means for You; Cocktail Party; Class Notes.',antiTemplateDecision:'No fictional shopper, workplace example, provider dining-table example, privacy inference or generic AI-commerce panorama.',analogyPlan:[],humourPlan:{noneReason:'Dry, restrained treatment keeps the commercial relationship clear.'},readerQuestions:[{id:'event',question:'What is OpenAI testing?'},{id:'speaker',question:'Who is answering in the sponsored conversation?'},{id:'separation',question:'How is it separated from the original chat?'},{id:'action',question:'What should a shopper do with product claims?' }],requiredTerms:[{term:'Sponsored Agent',meaning:'an AI agent sponsored by the business whose ad a person clicked'}],presentationPlan:'A dedicated people-free editorial illustration will show two visibly separate blank conversation panels beside a lamp and measuring tape, without logos, prices, ratings, approval marks or readable text.',plainAnswer:'After the ad click, the optional new conversation is with the seller’s sponsored agent.'};
contract.knownFailurePreflight.candidateRepairPreflight={event:'The September 16 Sponsored Agents test is the fresh event.',attribution:'The product structure and separation claim remain attributed to OpenAI.',limits:'No privacy, data-sharing, effectiveness, global or tier-availability claim.',budget:'All visible source-derived wording remains below the 200-word OpenAI aggregate limit and the 25-word quote limit.'};
contract.visualAdmission=null;
write('producer-contract.json',contract);

write('art/producer-contract.json',{schemaVersion:'laidies-newsstand-visual-producer-contract.v1',candidateId:story.id,producer:'/root/aft_school_story',storyBinding:{path:root+'/story.json',sha256:sha(root+'/story.json')},job:'Show the reader-facing hand-off from an original chat into a visibly separate seller-sponsored shopping conversation without implying neutrality, endorsement, safety, privacy, purchase completion or wider availability.',scene:'People-free adult editorial pop-art still life on a shopping desk. A tablet displays two clearly separate blank interface panels, one receding and one foregrounded, with only geometric empty chat-bubble shapes and no text. Beside it sit a bright desk lamp, a flexible measuring tape and a simple product-page card with blank blocks.',mustShow:['Two visibly separate blank conversation panels','Desk lamp','Measuring tape','People-free shopping context'],mustNotShow:['People or hands','MAiVEN or TRAiLBLAZER','OpenAI or ChatGPT logos','Readable text, letters, numbers or pseudo-text','Prices, ratings, checkmarks, badges or purchase confirmation','Padlocks, shields or privacy symbols','Global maps, tier labels or availability claims','The provider’s dining-table example'],style:{authority:'LAiDIES current adult editorial pop-art direction',referenceSha256:'0742816929be694e0e9fcfa11c3ae047173814e6112419176a71a994273828a5',palette:'Navy and plum linework with cyan, pink, coral and yellow accents.',finish:'Crisp editorial composition, halftone print texture, strong silhouette, clean negative space; no UI realism or glossy tech advertising.'},output:{aspect:'3:2 landscape',targetPath:'assets/newsstand/sponsored-agent-shopping-20260916.png',alt:story.heroVisual.alt,credit:story.heroVisual.credit},status:'READY_TO_RENDER'});
write('art/prompt.txt',`Create a 3:2 landscape, people-free adult editorial pop-art illustration for LAiDIES NewsStand. On a clean shopping desk, show a tablet with TWO VISIBLY SEPARATE interface panels: a smaller receding original-chat panel and a separate foreground seller-conversation panel. Both panels contain only a few EMPTY GEOMETRIC CHAT-BUBBLE SHAPES. Absolutely no readable text, no letters, no numbers, no pseudo-writing, no logos. Beside the tablet place one bright desk lamp, a flexible measuring tape and a simple product-page card made only of blank color blocks. The separation between the two conversations must be immediately legible. Navy and plum linework, cyan, pink, coral and yellow accents, halftone print texture, crisp adult editorial composition, clean negative space. Do not show people, hands, faces, MAiVEN, TRAiLBLAZER, brand marks, ChatGPT/OpenAI logo, prices, ratings, checkmarks, badges, purchase confirmation, shields, padlocks, privacy symbols, global maps, tier labels, graphs, or a dining table. Do not imply endorsement, neutrality, safety, privacy, purchase completion or general availability.`);
console.log(JSON.stringify({candidate:story.id,storySha256:sha(root+'/story.json'),sourceBudget:total,library:libraryEntry.url,artContract:sha(root+'/art/producer-contract.json')}));
