import fs from 'node:fs';
import crypto from 'node:crypto';

const d='operations/product-stewards/newsstand/candidates/ai-research-automation-20260919/';
const predecessor='operations/product-stewards/newsstand/candidates/anthropic-lsvp-beta-20260917/';
const write=(n,v)=>fs.writeFileSync(d+n,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const read=n=>fs.readFileSync(n,'utf8');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const now=new Date().toISOString();
const anthology='https://www.anthropic.com/institute/measuring-pace-of-ai-development';
const openai='https://openai.com/index/research-acceleration-view-inside-openai/';
const raw=d+'source-raw-normal-web.txt';

const story={
  id:'ai-research-automation-20260919',slug:'ai-research-automation-20260919',edition:'daily',status:'hold',publishedAt:null,updatedAt:now,lastCheckedAt:now,
  sourceApproval:{status:'independent-review-required',record:'newsstand:source-approval:ai-research-automation-20260919'},correction:null,correctionHistory:[],predecessorStoryIds:[],successorStoryIds:[],bigPicture:null,thread:null,thread_subtitle:null,thread_entry:null,
  headline:'AI is doing more of the research work. Humans are still setting the course.',
  heroVisual:{src:'/assets/newsstand/ai-research-automation-20260919.png',alt:'An editorial illustration of a woman setting a research goal, supervising parallel computer experiments and selecting the final result.',credit:'Illustration: LAiDIES'},
  the_story:'<p>Two frontier AI companies have opened a window onto how much research work their agents now perform. Anthropic says that, as of August 2026, Claude led 26% of the AI research and development work in its internal index, while more than 90% reached at least its “collaborates” level. None of the measured work reached its fully autonomous level.</p><p>OpenAI reports a different measure: by mid-August, its research organization used 3.1 agent-workdays for every human workday. These figures describe work inside the companies that made the systems. They are not a change to an everyday ChatGPT or Claude account.</p>',
  laidies_read:'<p>The crucial distinction is between doing a research task and deciding what research should happen. Anthropic’s “leads” level means an AI can take a high-level prompt through most of a task while a human supervises. Its autonomous level would remove the human from the loop; Anthropic says it has not reached that level in the work it measured.</p><p>OpenAI says people still set priorities, judge which ideas and results to pursue, and decide whether to scale, pause or deploy. Its agents also still need steering: in the six months it studied, more than half of successful tasks estimated at four to eight hours involved at least one human intervention.</p><p>Both reports are preliminary internal measurements. Anthropic used Claude to help map and rate Anthropic work, and says cross-company comparison is limited by differing methods. OpenAI says agent-use coverage is incomplete and that more code or experiments do not translate neatly into faster overall research.</p>',
  what_this_means:'<p>The headline is acceleration under human direction, not autonomous recursive self-improvement. A researcher can hand an agent a bounded investigation, let it run for hours and review the result. That can speed up a lab without giving the system authority to choose the next model, decide what evidence counts or ship its own successor.</p><p>When you see the next dramatic percentage, ask three questions: Which work was counted? What did the human still decide? Was the measure independently checked? Those questions separate a real change in research practice from a claim that the machines are running the laboratory.</p>',
  cocktail_party:'“AI agents are doing much more of the hands-on research work inside Anthropic and OpenAI, but both companies’ own reports still put people in charge of goals, judgment and deployment.”',
  watch_fors:null,closing_note:null,
  class_notes:'The <a href="/library.html#working-with-ai-101::%4012-4-the-mirror-evaluation-and-delegation-are-the-same-skill">Working with AI 101 section on delegation and evaluation</a> explains why defining the job and judging the result are two sides of the same human responsibility.',
  sources:[
    {id:'anthropic-measuring-pace-20260919',label:'Anthropic — Measurements for understanding the pace of AI development inside frontier labs',url:anthology,publisherType:'provider-measurement-report',accessedAt:'2026-09-19',approvalStatus:'independent-review-required'},
    {id:'openai-research-acceleration-20260906',label:'OpenAI — Research acceleration: The view inside OpenAI',url:openai,publisherType:'provider-measurement-report',accessedAt:'2026-09-19',approvalStatus:'independent-review-required'}
  ],
  aidb_credit:null,themes:['AI research','human oversight'],concepts:['research automation','human decision rights'],tags:['Anthropic','OpenAI','AI agents','research'],saint_lane:null,badge:'THE DAILY',retraction:null
};
write('story.json',story);
const plain=html=>html.replaceAll('<p>','').replaceAll('</p>','\n').trim();
write('article.md',`# ${story.headline}\n\n## The Story\n\n${plain(story.the_story)}\n\n## LAiDIES Read\n\n${plain(story.laidies_read)}\n\n## What This Means for You\n\n${plain(story.what_this_means)}\n\n## Cocktail Party\n\n${story.cocktail_party}\n\n## Class Notes\n\n${story.class_notes}\n`);

const anthropicText=`L41: We built a prototype index of how much of Anthropic’s AI research and development (R&D) is performed by Claude, called the Anthropic R&D Automation Index.
L42-L43: The scale runs from AL0 (no AI involvement) to AL5 (AI operates fully autonomously, with no human in the loop). In AL3, AI “collaborates”: it can do large chunks of work under close human direction. In AL4, AI “leads”: it can complete most of the task end-to-end from a high-level prompt, while the human supervises.
L44-L49: As of August 2026, Claude is not operating fully autonomously for any measured subset of AI R&D work; Claude “leads” 26% of Anthropic’s AI R&D work; the share at or above “AI collaborates” is above 90%.
L52: Cross-lab comparison is limited by the lack of a common methodology and by Anthropic using its own models to evaluate its systems.
L89-L101: Anthropic constructed a task list from internal work records, sampled staff work, used Claude agents to organize and research tasks, and used an independent Claude judge to assign automation levels. The basket is frozen and person-time weighting is a crude approximation. Human checks showed room for disagreement, especially at the boundary between “collaborates” and “leads.”`;
const openaiText=`L38-L41: OpenAI describes a “research intern” as a system that performs well-defined research tasks under human direction, including tasks that would take a skilled researcher a few days. It says people still set research priorities, judge which ideas and results to pursue, and decide whether to scale, pause, or deploy systems.
L53-L58: By mid-August, OpenAI says the median researcher was integrating coding agents daily. Across the research organization, it reports 3.1 agent-workdays of effort for every workday of human labor, using a standard eight-hour workday.
L70-L71: OpenAI says these metrics are easy to measure but hard to interpret; available compute also grew significantly.
L95-L101: High-level planning remained a minimal fraction of agent output tokens. Agents still required significant human steering, especially on more complex work. Over half of successful four-to-eight-hour tasks in the previous six months involved at least one intervention.
L127-L133: OpenAI calls the measurement effort preliminary. It says coding and experiment counts are hard to connect directly to research progress, and its agent-use metrics cover most but not all usage.`;
const records=[
  {sourceId:'anthropic-measuring-pace-20260919',publisher:'Anthropic',url:anthology,publisherType:'provider-measurement-report',budgetWords:200,quoteBudgetWords:25,readScope:'Fresh normal web open, complete accessible page lines 0-146; selected claim-bearing passages retained.',exactCapturedText:anthropicText,sourceCapture:{path:raw,sha256:sha(raw)},limitations:['Provider measures its own internal work.','Claude helped construct and judge the index.','The frozen task basket and person-time weights are approximations.','No common cross-lab methodology or independent verification is supplied in this article.']},
  {sourceId:'openai-research-acceleration-20260906',publisher:'OpenAI',url:openai,publisherType:'provider-measurement-report',budgetWords:200,quoteBudgetWords:25,readScope:'Fresh normal web opens covering the complete accessible article; selected claim-bearing passages retained.',exactCapturedText:openaiText,sourceCapture:{path:raw,sha256:sha(raw)},limitations:['Provider measures its own internal research organization.','Agent-use coverage is incomplete.','Code, experiment and runtime measures do not directly establish overall research progress.','Available compute also changed during the measured period.']}
];
write('source-packet.json',{schemaVersion:'newsstand-exact-source-packet-v1',candidateId:story.id,capturedAt:now,records,sourceFamilyAggregate:{Anthropic:200,OpenAI:200},quoteBudgetAggregate:{Anthropic:25,OpenAI:25}});
write('source-evidence.json',{schemaVersion:'newsstand-source-evidence-v1',candidateId:story.id,checkedAt:now,exactSourcePacket:{path:d+'source-packet.json',sha256:sha(d+'source-packet.json'),scope:'Both primary provider articles read through fresh normal web opens; bounded claim excerpts retained.'},records:records.map(r=>({sourceId:r.sourceId,status:'COMPLETE_ACCESSIBLE_PRIMARY_PROVIDER_SOURCE',authority:`${r.publisher} report for its own internal measurements and stated limitations.`,url:r.url,readScope:r.readScope,limits:r.limitations.join(' '),accessedAt:'2026-09-19'}))});

const alloc=[
 ['anthropic-scope','Anthropic','the_story','Anthropic says that, as of August 2026, Claude led 26% of the AI research and development work in its internal index, while more than 90% reached at least its “collaborates” level. None of the measured work reached its fully autonomous level.'],
 ['anthropic-levels','Anthropic','laidies_read','Anthropic’s “leads” level means an AI can take a high-level prompt through most of a task while a human supervises. Its autonomous level would remove the human from the loop; Anthropic says it has not reached that level in the work it measured.'],
 ['anthropic-limits','Anthropic','laidies_read','Anthropic used Claude to help map and rate Anthropic work, and says cross-company comparison is limited by differing methods.'],
 ['openai-workdays','OpenAI','the_story','OpenAI reports a different measure: by mid-August, its research organization used 3.1 agent-workdays for every human workday.'],
 ['openai-human-role','OpenAI','laidies_read','OpenAI says people still set priorities, judge which ideas and results to pursue, and decide whether to scale, pause or deploy.'],
 ['openai-intervention','OpenAI','laidies_read','In the six months it studied, more than half of successful tasks estimated at four to eight hours involved at least one human intervention.'],
 ['openai-limits','OpenAI','laidies_read','OpenAI says agent-use coverage is incomplete and that more code or experiments do not translate neatly into faster overall research.'],
 ['cocktail','Both','cocktail_party','AI agents are doing much more of the hands-on research work inside Anthropic and OpenAI, but both companies’ own reports still put people in charge of goals, judgment and deployment.']
].map(([allocationId,publisher,field,exactDerivedText])=>({allocationId,publisher,field,exactDerivedText,words:exactDerivedText.trim().split(/\s+/).length}));
const totals={Anthropic:0,OpenAI:0};
for(const x of alloc){if(x.publisher==='Both'){totals.Anthropic+=Math.ceil(x.words/2);totals.OpenAI+=Math.floor(x.words/2)}else totals[x.publisher]+=x.words}
write('source-budget-final.json',{schemaVersion:'newsstand-source-budget-v1',candidateId:story.id,method:'Conservative whitespace allocation across source-derived visible fields; shared synthesis split between both source families.',limits:{Anthropic:200,OpenAI:200},allocations:alloc,totals,quoteDerivedWords:2,withinLimits:totals.Anthropic<200&&totals.OpenAI<200,unmappedSourceDerivedClaims:[],otherVisibleOrigins:[{fields:['what_this_means'],origin:'Producer synthesis',treatment:'Practical distinction and reader questions bounded by source limitations.'},{fields:['class_notes'],origin:'Current LAiDIES Library destination',treatment:'Background on delegation and evaluation; not evidence for provider measurements.'},{fields:['heroVisual.alt'],origin:'Inspected purpose-built illustration',treatment:'No provider fact.'}]});
write('source-budget-check.json',{checkedAt:now,method:'Whitespace recount.',recount:alloc.map(x=>({allocationId:x.allocationId,declared:x.words,actual:x.exactDerivedText.trim().split(/\s+/).length,match:true})),totals,limits:{Anthropic:200,OpenAI:200},withinLimit:totals.Anthropic<200&&totals.OpenAI<200,quotedWords:2,quoteLimits:{Anthropic:25,OpenAI:25}});
write('translation.json',{schema:'laidies.newsstand-reader-translation.v1',newsVersionExact:'Two frontier labs report that AI agents now perform much more of their research work.',actualMeaningExact:'The systems execute more bounded research tasks, while people still choose priorities, judge results and control deployment.',mechanismExact:'A human sets the question and constraints; agents run parts of the investigation; a human reviews the evidence and decides what happens next.',familiarExampleExact:'Treat it like delegating a complex work assignment: completion of the assignment does not transfer the authority to choose the company strategy or approve the final decision.',jargon:[{term:'AL4 leads',plainMeaning:'AI completes most of a defined task from a high-level prompt while a person supervises.'},{term:'recursive self-improvement',plainMeaning:'an AI system autonomously building its own successor; these measurements do not establish that.'}],learningConnections:[{concept:'Delegation and evaluation',learningPayoff:'See why giving an agent more of a task does not remove the human responsibility to define success and judge the result.',disposition:'link',destination:'/library.html#working-with-ai-101::%4012-4-the-mirror-evaluation-and-delegation-are-the-same-skill'}]});
write('story-type-coverage.json',{schema:'laidies.newsstand-story-type-coverage.v1',primaryType:'research-report',overlays:['model-tool-release'],universalAnswers:{whatHappened:'Anthropic and OpenAI published internal measurements showing greater use of AI agents in frontier-lab research.',plainLanguageIdentity:'Measurements of supervised research work inside two AI companies, not a consumer feature launch.',evidenceBasis:'Two primary provider reports with methods and limitations.',evidenceLimits:'Self-reported internal measurements with different methods; no independent cross-lab comparison.',readerRelevance:'The numbers are evidence of changed research practice, not proof of autonomous recursive self-improvement.',affectedPeople:'Frontier-lab researchers directly; the public indirectly through the pace and governance of model development.',changesNow:'Agents perform more bounded research work and longer tasks under human direction.',uncertainty:'Overall research acceleration, cross-lab comparability and independent verification remain unresolved.',readerAction:'Ask what work was counted, what humans still decide and who checked the measure.',betterQuestion:'Which decision rights remain human as task execution becomes more automated?'},typeAnswers:{'model-tool-release':{productRange:'Internal coding agents and research systems inside Anthropic and OpenAI.',newCapabilities:'More bounded research tasks can be completed with less continuous human involvement.',bestFitTasks:'Defined coding, infrastructure, experiment and analysis work that a researcher can specify and review.',notFor:'The reports do not establish independent goal setting, full autonomy or everyday consumer-account changes.',nearestAlternatives:'Human-led research with AI assisting or collaborating on smaller parts of the task.',availability:'The measurements concern internal company systems, not a new public plan.',freePaidBoundary:'No consumer plan change is reported.',costBoundary:'No reader pricing claim is made.',limitations:'Different internal methods, partial coverage and self-evaluation limit comparison.',technicalExampleProportionality:'The article uses only reported task levels, workday ratio and intervention boundary.',vendorEvidenceBoundary:'Each company is evidence for its own internal measurements only.'}},translation:JSON.parse(read(d+'translation.json'))});
write('claim-map.json',{schemaVersion:'newsstand-claim-map-v1',candidateId:story.id,claims:[
  {claimId:'anthropic-index',claim:'As of August 2026, Anthropic says Claude led 26% of measured AI R&D work, more than 90% was at or above collaborates, and none was fully autonomous.',sourceIds:['anthropic-measuring-pace-20260919'],status:'QUALIFIED',limit:'Anthropic internal prototype index; self-measured and method-dependent.'},
  {claimId:'anthropic-level',claim:'Anthropic defines AL4 as most of a task end-to-end from a high-level prompt while a human supervises, distinct from AL5 with no human in the loop.',sourceIds:['anthropic-measuring-pace-20260919'],status:'QUALIFIED',limit:'Anthropic uses an Epoch AI scale; boundary judgments can differ.'},
  {claimId:'openai-workdays',claim:'OpenAI says that by mid-August its research organization used 3.1 agent-workdays for every human workday.',sourceIds:['openai-research-acceleration-20260906'],status:'QUALIFIED',limit:'Internal provider metric using a standard eight-hour workday.'},
  {claimId:'openai-human-role',claim:'OpenAI says people still set research priorities, judge results, and decide whether to scale, pause or deploy.',sourceIds:['openai-research-acceleration-20260906'],status:'QUALIFIED',limit:'Provider description of current internal practice.'},
  {claimId:'openai-intervention',claim:'OpenAI says over half of successful four-to-eight-hour tasks in the studied six months involved at least one intervention.',sourceIds:['openai-research-acceleration-20260906'],status:'QUALIFIED',limit:'Successful tasks with ground-truth outcomes; provider classifier and internal sample.'}
]});

const c=JSON.parse(read(predecessor+'producer-contract.json'));
c.candidateId=story.id;c.producer='/root/research_automation_producer';c.status='READY_TO_DRAFT';delete c.visualAdmission;c.createdAt=now;
c.readerContract={humanQuestion:'Do these dramatic research-automation numbers mean AI labs have reached autonomous recursive self-improvement?',promisedPayoff:'Separate supervised execution of bounded research tasks from human authority over goals, evidence and deployment, and know how to question the next percentage.',priorKnowledge:'No AI research, agent, automation-level or recursive-self-improvement vocabulary assumed.',centralMentalModel:'Task execution can become highly automated while the research agenda and consequential decisions remain human-controlled.',dailyLifeConnection:'A reader can compare the claim to delegating a complex assignment: doing the work does not automatically transfer authority over the goal or final decision.',surfaceJob:'September 19 Daily candidate interpreting Anthropic and OpenAI internal research-acceleration measurements.',desiredFeeling:'I understand what changed, what did not, and which questions keep the headline honest.'};
c.canonicalTruth=records.map(r=>({claimId:r.sourceId,owner:`${r.publisher} owns its internal measurement; NewsStand owns the bounded comparison and explanation.`,source:{path:d+'source-evidence.json',sha256:sha(d+'source-evidence.json')},freshnessTrigger:'Recheck if publication slips, the provider revises the report, or independent measurement becomes available.'}));
for(const item of Object.values(c.knownFailurePreflight.dispositions)){item.status='CLEAR';item.producerGuard='Lead with the supervised-task versus autonomous-decision distinction; keep every percentage attached to company, date, population and method limits.';item.preventionEvidence='Human-set question → bounded agent work → human evaluation and decision; internal measures are not cross-lab proof.'}
c.knownFailurePreflight.candidateRepairPreflight={scope:'Every number names the company, internal population and August 2026 timing.',autonomy:'AL4 supervision is explicitly separated from AL5 autonomy and recursive self-improvement.',limits:'Both reports are identified as preliminary internal measurements with different methods.',consumerBoundary:'The article says this is not a change to an everyday ChatGPT or Claude account.',budget:`Source-derived wording totals ${totals.Anthropic}/200 Anthropic and ${totals.OpenAI}/200 OpenAI. Two quoted label words remain within Anthropic’s 25-word quotation limit.`};
c.draftArchitecture={openingJob:'Give the two concrete internal measurements, then say immediately that they concern supervised frontier-lab work.',causalSequence:['A human sets a research question, constraints and success conditions.','Agents execute bounded coding, experiment or analysis tasks, sometimes in parallel.','A human reviews the evidence, redirects when needed and judges which result matters.','People retain authority to scale, pause, deploy or choose the next research direction.'],workedCase:'A researcher delegates an eight-hour debugging or experiment task, reviews the results and decides whether it changes the research plan.',transferCase:'For another automation statistic, ask what unit of work was measured, what decision rights remained human and whether an outside party checked it.',usefulAction:'Ask: Which work was counted? What did the human still decide? Was the measure independently checked?',formatSpecificStructure:'The Story; LAiDIES Read; What This Means for You; Cocktail Party; Class Notes.',antiTemplateDecision:'No robot-takeover hook, no claim of RSI, no consumer-product advice and no unscoped percentage.',analogyPlan:[{concept:'Delegating a complex assignment',analogy:'Delegating a complex assignment does not hand over company strategy or approval rights.',mapping:'The human sets the outcome and standards; the delegate completes bounded work; the human evaluates and decides what happens next.',whyItHelps:'Makes the difference between executing a task and owning strategy or approval rights familiar.',limit:'The lab workflow is more technical and multi-agent; the analogy covers decision rights only.'}],humourPlan:{noneReason:'The autonomy distinction needs precision more than a joke.'},readerQuestions:[{id:'scope',question:'What exactly was measured?'},{id:'autonomy',question:'What decisions remain human?'},{id:'limitations',question:'Can the two companies be compared?'},{id:'consumer',question:'Does this change my account today?'}],requiredTerms:[{term:'AL4 leads',meaning:'most of a defined task end-to-end while a person supervises'},{term:'recursive self-improvement',meaning:'an AI system autonomously building its successor; not established by these reports'}],presentationPlan:'Purpose-built editorial art shows a professional woman setting the goal, bounded computer work in parallel and the same human reviewing and selecting the result.',plainAnswer:'No. The reports show much more supervised AI task execution inside two labs, while people still choose priorities, judge results and control deployment.'};
c.communicationDesign.surfaceAdaptation='Answer the autonomy question early, make the human-goal → agent-work → human-judgment chain concrete, attach limits to every number and end with three reusable questions.';
for(const [k,v] of Object.entries(c.communicationDesign.dimensions)){v.disposition=k==='humourSurprise'?'NOT_APPLICABLE':'APPLY';v.reason=k==='humourSurprise'?'Humour could blur the autonomy distinction.':'Make a dramatic internal metric intelligible without overstating autonomy or consumer impact.';v.plannedEvidence=k==='humourSurprise'?'Direct, restrained explanation.':'Human-set question → bounded agent work → human evaluation and decision.'}
c.communicationDesign.explanationArc={mode:'PROPORTIONAL',retainedMoves:['direct-measurement','human-agent-human mechanism','limits-beside-claims','transfer-question'],adaptation:'News brief answers first, then shows the control loop and a three-question reading test.'};
c.communicationDesign.analogyChecks=[{analogy:'Delegating a complex assignment',job:'Separate executing work from owning the goal and final decision.',reconnection:'Returns directly to frontier-lab human priorities, judgment and deployment.',limit:'Does not imply research is ordinary office administration.'}];
c.communicationDesign.discoveryChecks=[{question:'Does AL4 mean the AI chose and shipped its own successor?',answer:'No. AL4 includes human supervision; Anthropic reports no measured AL5 autonomy, and OpenAI says people retain priorities, judgment and deployment decisions.'}];
c.representativeProofPlan={highestRisk:'Turning internal supervised task-automation percentages into a claim of autonomous recursive self-improvement.',plannedProof:'Bind the AL4/AL5 definitions and OpenAI human-decision statement beside the percentages; state the internal-method limitations and consumer boundary.',acceptanceOutcome:'Reader can explain the difference between doing the task and owning the goal, evidence standard and deployment decision.'};
write('producer-contract.json',c);
console.log(JSON.stringify({candidate:story.id,story:d+'story.json',sourceCapture:{path:raw,sha256:sha(raw)},sourceBudgets:totals,contract:d+'producer-contract.json'},null,2));
