import fs from 'node:fs';
import crypto from 'node:crypto';
import {candidateReviewText} from '../../../../../scripts/validate-newsstand-ordinary-story-candidate.mjs';
import {inspectContentProducerContract} from '../../../../../scripts/check-content-producer-contract.mjs';
import {inspectProseQualityReview} from '../../../../../scripts/check-prose-quality-admission.mjs';
import {storyParagraphs} from '../../review-runtime/protocol.mjs';
import {prepareDraft} from '../../../../../scripts/prepare-newsstand-draft.mjs';

const d='operations/product-stewards/newsstand/candidates/ai-research-automation-20260919/';
const pred='operations/product-stewards/newsstand/candidates/anthropic-lsvp-beta-20260917/';
const read=n=>fs.readFileSync(d+n,'utf8'),j=n=>JSON.parse(read(n));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const bind=n=>({path:d+n,sha256:sha(read(n))});
const write=(n,x)=>fs.writeFileSync(d+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const now=new Date().toISOString();
const s=j('story.json'),c=j('producer-contract.json'),packet=j('source-packet.json'),coverage=j('story-type-coverage.json');
const art=bind('art/independent-review.json');
const artReview=j('art/independent-review.json');
if(artReview.verdict!=='PASS')throw Error('Independent visual admission must PASS before producer review.');
const mustBind=(actual,expected,label)=>{if(!actual||actual.path!==expected.path||actual.sha256!==expected.sha256)throw Error(`Independent visual admission has stale ${label} binding.`);};
mustBind(artReview.companion,bind('story.json'),'story');
mustBind(artReview.producerContract,bind('art/producer-contract-v2.json'),'visual producer contract');
mustBind(artReview.producerReview,bind('art/maker-inspection-v2.json'),'maker inspection');
mustBind(artReview.artifact,{path:'proposed/assets/newsstand/ai-research-automation-20260919.png',sha256:sha(fs.readFileSync('proposed/assets/newsstand/ai-research-automation-20260919.png'))},'image');
c.visualAdmission=art;write('producer-contract.json',c);
write('review-text.json',candidateReviewText(s));
write('rendered-article.html',`<article><h1>${s.headline}</h1><figure><img src="../../../../../../proposed/assets/newsstand/ai-research-automation-20260919.png" alt="${s.heroVisual.alt}"><figcaption>${s.heroVisual.credit}</figcaption></figure>${s.the_story}<h2>LAiDIES Read</h2>${s.laidies_read}<h2>What This Means for You</h2>${s.what_this_means}<h2>Cocktail Party</h2><p>${s.cocktail_party}</p><h2>Class Notes</h2><p>${s.class_notes}</p></article>\n`);
write('publication-manifest.json',{schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:s.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',reviewText:bind('review-text.json'),rendered:bind('rendered-article.html'),story:bind('story.json'),heroVisual:{path:'proposed/assets/newsstand/ai-research-automation-20260919.png',sha256:sha(fs.readFileSync('proposed/assets/newsstand/ai-research-automation-20260919.png'))},visualAdmission:art});
const writer={...prepareDraft(c,{root:process.cwd(),reportingFrame:coverage,sourcePacket:bind('source-evidence.json')}),producerContract:bind('producer-contract.json')};write('writer-input-current.json',writer);

const a=packet.records[0],o=packet.records[1];
const claims=[
 {claimId:'anthropic-index',claim:'As of August 2026, Anthropic says Claude led 26% of measured AI research work, performed at least collaboratively in more than 90%, and was fully autonomous in none.',candidateEvidence:[{excerpt:'Anthropic says that in its August 2026 internal index, Claude led 26% of AI research work, performed at least collaboratively in more than 90%, and was fully autonomous in none.',locator:'The Story'}],record:a,sourceEvidence:[{excerpt:'As of August 2026, Claude is not operating fully autonomously for any measured subset of AI R&D work; Claude “leads” 26% of Anthropic’s AI R&D work; the share at or above “AI collaborates” is above 90%.',locator:a.url}],scopeAndFreshness:'Anthropic prototype internal index, dated August 2026 and reread September 19; “none” is confined to measured subsets and is not a universal autonomy claim.'},
 {claimId:'anthropic-level',claim:'Anthropic says “led” means completing most of a defined task from a high-level prompt while a human supervises; fully autonomous work removes the human.',candidateEvidence:[{excerpt:'In Anthropic’s scale, “led” means completing most of a defined task from a high-level prompt while a human supervises. Fully autonomous work removes the human; Anthropic says no measured subset reached it.',locator:'LAiDIES Read'}],record:a,sourceEvidence:[{excerpt:'In AL4, AI “leads”: it can complete most of the task end-to-end from a high-level prompt, while the human supervises.',locator:a.url},{excerpt:'AL5 (AI operates fully autonomously, with no human in the loop).',locator:a.url}],scopeAndFreshness:'Automation-level definitions applied by Anthropic using an Epoch AI scale; boundary judgments have acknowledged disagreement.'},
 {claimId:'openai-workdays',claim:'OpenAI says that by mid-August its agents’ total runtime across the research organization equalled 3.1 standard eight-hour agent workdays for each human workday.',candidateEvidence:[{excerpt:'OpenAI reports a different measure: by mid-August, its agents’ total runtime across the research organization was equivalent to 3.1 standard eight-hour agent workdays for each human workday.',locator:'The Story'}],record:o,sourceEvidence:[{excerpt:'In terms of a standard 8 hour workday, as of mid-August, in total, the research organization uses 3.1 agent-workdays of effort for every workday of human labor.',locator:o.url}],scopeAndFreshness:'OpenAI internal runtime metric as of mid-August 2026; an agent-workday is runtime in eight-hour units, not a 3.1-times productivity claim.'},
 {claimId:'openai-human-role',claim:'OpenAI says people still set priorities, judge results, and decide whether to scale, pause or deploy.',candidateEvidence:[{excerpt:'OpenAI says people still set priorities, judge results and decide whether to scale, pause or deploy.',locator:'LAiDIES Read'}],record:o,sourceEvidence:[{excerpt:'People still set our research priorities, judge which ideas and results to pursue, and decide whether to scale, pause, or deploy systems.',locator:o.url}],scopeAndFreshness:'OpenAI description of its current internal practice.'},
 {claimId:'openai-intervention',claim:'OpenAI says over half of successful four-to-eight-hour tasks in the studied six months involved at least one intervention.',candidateEvidence:[{excerpt:'In the six months it studied, more than half of successful four-to-eight-hour tasks needed at least one intervention.',locator:'LAiDIES Read'}],record:o,sourceEvidence:[{excerpt:'In the last 6 months, over half of successful 4-8 hour tasks involved 1 or more interventions.',locator:o.url}],scopeAndFreshness:'OpenAI internal task sample with ground-truth outcomes; provider classifier and preliminary measurement.'}
];
const sources=[];
for(const claim of claims){
 claim.sourceIds=[];
 claim.sourceEvidence.forEach((evidence,index)=>{
  const id=`${claim.record.sourceId}-${claim.claimId}-${index+1}`;
  claim.sourceIds.push(id);
  sources.push({id,url:claim.record.url,authority:`${claim.record.publisher} report for its own internal measurement and stated limitations.`,source:{url:claim.record.url,passage:evidence.excerpt,passageLocator:claim.record.readScope},limitations:claim.record.limitations.join(' ')});
 });
 delete claim.record;
}
write('editorial-input.json',{readerJob:`${c.readerContract.humanQuestion} ${c.readerContract.promisedPayoff}`,completeArtifact:read('review-text.json'),paragraphs:storyParagraphs(s),communicationAuthority:c.communicationDesign,claims,sources,reviewBoundary:{status:'PENDING_DISTINCT_INDEPENDENT_REVIEW',instruction:'Treat each company only as the source for its own internal measurement. Do not infer cross-lab comparability, independent verification, consumer availability, autonomous goal setting or recursive self-improvement. Confirm that every percentage retains date, population and human-decision scope.'}});
const obs={schemaVersion:'laidies-newsstand-producer-observations.v1',candidateId:s.id,completeTextRead:true,storySha256:sha(JSON.stringify(s)),readerAnswers:{scope:'These figures describe work inside the companies that made the systems.',autonomy:'Fully autonomous work removes the human; Anthropic says no measured subset reached it.',limitations:'Both reports are preliminary internal measurements.',consumer:'They are not a change to an everyday ChatGPT or Claude account.'},terms:{'recursive self-improvement':'a model independently building its successor without a human in the loop','agent workday':'standard eight-hour agent workdays for each human workday'},explainBack:'The labs are delegating more hands-on research work to agents, but people still choose priorities, judge the results and decide what ships. Supervised execution of a defined task is not autonomous successor development.',unseenTransfer:'For another automation percentage, I should ask what unit of work was counted, what decisions remained human and whether an outside party checked the method.',unresolvedIssues:[],repairsMade:['Rejected the generic first concept, then preserved and repaired the independently rejected three-arm successor before final visual admission.','Attached each percentage to company, date and internal population.','Defined recursive self-improvement in plain language and stated only that the reports do not establish it.','Defined the OpenAI number as agent runtime in standard eight-hour units rather than productivity.','Added OpenAI’s human priorities, judgment and deployment boundary.','Added both providers’ method limitations and the everyday-consumer boundary.','Accounted for every visitor-facing source-derived fragment and every claim limitation below 200 words per source.'],limitations:['Producer AI simulations; no observed human comprehension test.','Both sources are provider reports about their own internal systems; no independent cross-lab verification.','The article does not measure overall research acceleration or forecast a date for autonomous research.']};write('producer-observations.json',obs);

const template=JSON.parse(fs.readFileSync(pred+'producer-publication-review.json','utf8'));
template.candidateId=s.id;template.maker='/root/research_automation_producer';template.reviewer={id:'/root/research_automation_producer',principalId:'/root/research_automation_producer',role:'Producer exact complete prose read',modelFamily:'openai'};template.reviewedAt=now;
template.calibration.reviewerPrincipalId=template.reviewer.principalId;template.calibration.reviewedAt=new Date(Date.parse(now)-1000).toISOString();
template.artifact={manifest:bind('publication-manifest.json'),reviewText:bind('review-text.json'),rendered:bind('rendered-article.html')};
template.reverseBrief={humanQuestion:c.readerContract.humanQuestion,promisedPayoff:c.readerContract.promisedPayoff,centralMentalModel:c.readerContract.centralMentalModel,dailyLifeConnection:c.readerContract.dailyLifeConnection,surfaceJob:c.readerContract.surfaceJob,desiredReaderFeeling:c.readerContract.desiredFeeling};
const evidence={plainClarity:'The crucial distinction is between doing a research task and deciding what research should happen.',readerValue:'They are not a change to an everyday ChatGPT or Claude account.',laidiesVoice:'When you see the next dramatic percentage, ask three questions',engagingEnjoyable:'Those questions separate a real change in research practice from a claim that the machines are running the laboratory.',factualIntegrity:'Both reports are preliminary internal measurements.',freshnessReviewability:'Anthropic says that in its August 2026 internal index',surfaceFit:s.headline,datedChange:'OpenAI reports a different measure: by mid-August',consequenceAndUncertainty:'This does not establish recursive self-improvement',dailyLifeConnection:'Bounded investigations can run for hours',communicationBenchmark:'OpenAI says people still set priorities, judge results and decide whether to scale, pause or deploy.',explainBack:'Fully autonomous work removes the human; Anthropic says no measured subset reached it.',unseenTransfer:'Which work was counted? What did the human still decide? Was the measure independently checked?',usefulAction:'Which work was counted? What did the human still decide? Was the measure independently checked?',analogyIntegrity:'without transferring authority over the next model, evidence or deployment'};
const observations={plainClarity:'The article defines the only necessary technical term in its sentence and contrasts task execution with decision authority.',readerValue:'It answers the immediate consumer question and gives three questions for reading future percentages.',laidiesVoice:'The language addresses a curious nontechnical reader directly without vendor promotion or specialist shorthand.',engagingEnjoyable:'The laboratory image gives the transfer questions energy while the opening delivers the measured change first.',factualIntegrity:'Each number names its provider, internal population, timing and methodological limit.',freshnessReviewability:'August and mid-August timing appear beside the respective measurements, with September 19 source review.',surfaceFit:'The Daily structure supplies the change, interpretation, practical reading test, learning link and sources.',datedChange:'The article distinguishes Anthropic’s August index from OpenAI’s mid-August runtime measure.',consequenceAndUncertainty:'The takeaway says the evidence does not establish recursive self-improvement and uses “may” for research speed.',dailyLifeConnection:'The everyday-account boundary and bounded-investigation example connect internal lab practice to a recognizable delegation question.',communicationBenchmark:'The invisible control boundary becomes concrete through priorities, result judgment and deployment decisions.',explainBack:'A reader can restate that supervised work on defined tasks does not transfer the research agenda or deployment authority.',unseenTransfer:'The three-question test transfers to a different automation percentage without reusing the article’s answer.',usefulAction:'The reader leaves with specific scope, human-decision and independent-check questions.',analogyIntegrity:'The bounded-investigation example maps only duration and retained authority, without equating lab research with ordinary office work.'};
for(const [k,x] of Object.entries(template.outcomes)){x.verdict='PASS';x.observation=observations[k];x.artifactEvidence=[{excerpt:evidence[k],locator:'complete exact story'}];}
template.outcomes.explainBack.simulatedReaderProbe={prompt:c.readerContract.humanQuestion,probeResponse:obs.explainBack,expectedEvidence:'Internal provider measures, increased bounded task execution, human priorities, judgment and deployment, and no established autonomous successor development.',transferResult:'PASS'};
template.outcomes.unseenTransfer.simulatedReaderProbe={prompt:'How should I read a new claim that AI automated 70% of another professional workflow?',probeResponse:obs.unseenTransfer,expectedEvidence:'Ask what work was counted, what decisions remained human and whether the method was independently checked.',transferResult:'PASS'};
const familyObservations={
 glossaryAccumulation:'Only recursive self-improvement needs definition, and its meaning appears inline before the consequence.',templateRepetition:'The sections advance from two measures to control boundaries, limitations and a reusable reader test.',decorativeAnalogy:'The bounded-investigation example directly explains retained authority and stops there.',referenceConfetti:'The article uses two primary provider reports because each supplies one side of the comparison.',missingMechanism:'Human priorities, supervised task execution, result judgment and deployment decisions form an explicit control loop.',genericAction:'The closing test asks exactly what was counted, what humans decided and whether the measure was independently checked.',jargonBeforeMeaning:'Public copy omits the AL labels and defines recursive self-improvement at first use.',disconnectedSystem:'The numbers, supervision definition, human decisions and research consequence remain in one causal explanation.',joylessInstruction:'The laboratory phrasing and concise challenge make the reading test memorable without obscuring the facts.',purposeTooNarrow:'The story translates two lab measures into a durable way to judge automation claims.',mechanismBeforeMotivation:'The concrete reported change comes before the supervision mechanism and method detail.',workedExampleOvertakesBookPurpose:'The bounded investigation occupies one sentence and returns immediately to research authority.',technicalExplainerVoice:'Short sentences and familiar verbs replace scale labels and measurement jargon.',benchmarkNameDrop:'No communication benchmark or expert name appears in public copy.',communicationPastiche:'The prose uses the LAiDIES Daily structure without imitating a named communicator.',corporateSludge:'People set priorities, judge results and decide deployment; the verbs identify accountable actions.',curiosityWithoutPayoff:'The dramatic percentages resolve into a clear conclusion and three reusable questions.',entertainmentBeforeUnderstanding:'The first two paragraphs state measurements and scope before the laboratory flourish.',factlessConfidence:'The conclusion says “does not establish” and “may,” preserving evidentiary limits.',familiarExampleWithoutTechnicalReturn:'The bounded-work example returns to next-model, evidence and deployment authority.',inflatedTakeawayEnding:'The ending asks how to evaluate the claim rather than predicting autonomous laboratories.',mechanismCompressedBehindHook:'The supervision definition and human-decision list receive their own full paragraphs.',prematureClickBeforeMechanism:'The Class Notes link follows the complete mechanism and explains its learning payoff.',staleUnreviewableClaims:'Dates, provider ownership, source links and recheck trigger make the claims reviewable.'
};
for(const [k,f] of Object.entries(template.failureFamilies)){f.present=false;f.observation=familyObservations[k];f.artifactLocator='complete exact story';}
const input=bind('editorial-input.json');
template.factualReview={disposition:'CLAIMS_REVIEWED',sourceBindings:[input,bind('source-packet.json'),bind('source-evidence.json')],claimMap:claims.map(x=>({...x,status:'QUALIFIED',sourceBinding:input})),reviewedThrough:'2026-09-19',nextTrigger:'Provider correction, independent measurement, material method update or publication after September 19.',correctionOwner:'NewsStand product steward'};
template.ratchet={repeatedKnownDefects:0,objectiveDefectsFirstFoundAtReview:1,reviewIssues:1,reviewCycles:2,onKnownDefect:'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'};
template.lineage={kind:'FIRST',noComparableReason:'First NewsStand comparison of these September 2026 Anthropic and OpenAI internal research-automation measurements.'};
template.visualRepairDisposition={disposition:'CANDIDATE_REPAIR_ONLY',rationale:'The first independent visual review found a third arm. The rejected pixels and receipt were preserved; the successor preflight limited the figure to two arms, two hands and two actions, and the independently inspected successor passed.',bindings:[bind('art/independent-review-v1-rejected.json'),bind('art/repair-preflight.json'),bind('art/maker-inspection-v2.json'),bind('art/independent-review.json')]};
template.learningDisposition={disposition:'NO_NEW_DEFECT',rationale:'This final producer prose read found no unresolved semantic defect. The objective visual defect and its candidate-only repair are retained separately in visualRepairDisposition because this receipt schema requires a PASS to describe the current repaired prose state.'};
template.verdict='PASS';template.limitations=obs.limitations;write('producer-publication-review.json',template);
const cc=inspectContentProducerContract(c,{root:process.cwd()}),rc=inspectProseQualityReview(template,{root:process.cwd()});write('contract-integrity.json',cc);write('producer-self-review-check.json',rc);
const errors=[...cc.errors,...rc.errors];if(errors.length)throw Error(errors.join('\n'));
console.log(JSON.stringify({status:'PRODUCER_SELF_REVIEW_PASS',story:bind('story.json'),reviewText:bind('review-text.json'),producerReview:bind('producer-publication-review.json'),sourceBudget:j('source-budget-final.json').totals},null,2));
