import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
const dir='/private/tmp/laidies-bright-shortcuts-20260911',origin=process.argv[2]||'https://laidies.ai',label=process.argv[3]||'pilot',strip=s=>s.replace(/<script type="module" src="https:\/\/static\.cloudflareinsights\.com\/[\s\S]*?<\/script>\s*/g,'');
const expected=fs.readFileSync(dir+'/candidate.html','utf8'),prior=fs.readFileSync(dir+'/before.html','utf8');
const b=await chromium.launch({channel:'chrome',headless:true}),rows=[];
try{
for(const width of label==='pilot'?[320,390,760,761,960,1100,1101,1440]:[390,960,1440]){
 let before;
 for(const state of label==='pilot'?['before','candidate']:[label]){
 const p=await b.newPage({viewport:{width,height:1050},reducedMotion:'reduce'});
 if(state==='candidate'){await p.route(origin+'/',r=>r.fulfill({status:200,contentType:'text/html',body:expected}));await p.route('**/assets/homepage/shortcuts/learn-illustration-20260911.png',r=>r.fulfill({status:200,contentType:'image/png',body:fs.readFileSync(dir+'/learn-final.png')}));}
 const r=await p.goto(origin+'/',{waitUntil:'domcontentloaded'});if(label!=='pilot')assert.equal(strip((await r.body()).toString()),expected);if(state==='before')assert.equal(strip((await r.body()).toString()),prior,'receiving production changed');
 await p.evaluate(()=>document.fonts.ready);await p.locator('.intent-grid-5 img').evaluateAll(async ns=>Promise.all(ns.map(n=>n.decode())));
 const data=await p.evaluate(()=>({cards:[...document.querySelectorAll('.intent-grid-5 a')].map(n=>{const i=n.querySelector('img'),s=getComputedStyle(i),d=n.querySelector('div');return{text:n.innerText,href:n.getAttribute('href'),src:i.getAttribute('src'),natural:[i.naturalWidth,i.naturalHeight],background:getComputedStyle(n).backgroundColor,copyBackground:getComputedStyle(d).backgroundColor,copyColor:getComputedStyle(d.querySelector('span')).color,card:{x:n.offsetLeft,y:n.offsetTop,w:n.offsetWidth,h:n.offsetHeight},image:{w:i.offsetWidth,h:i.offsetHeight,fit:s.objectFit,padding:s.padding},imageAbove:i.offsetTop<d.offsetTop}}),overflow:document.documentElement.scrollWidth>innerWidth+1,preview:!!document.querySelector('[data-daily-activity-preview]'),wallpaper:getComputedStyle(document.body).backgroundImage,banner:getComputedStyle(document.querySelector('[data-dyk]')).backgroundImage,pink:getComputedStyle(document.querySelector('#today')).backgroundImage}));
 const guard=()=>{assert.equal(data.cards.length,6);for(const c of data.cards){assert.equal(c.image.fit,'cover','image must fill panel');assert.equal(c.image.padding,'0px');assert(c.imageAbove);assert(c.natural[0]>0);assert(['rgb(125, 226, 194)','rgb(120, 199, 255)','rgb(242, 84, 169)'].includes(c.background),'dark card: '+c.background);assert.equal(c.copyBackground,'rgba(0, 0, 0, 0)');assert(Math.abs(c.image.w/(c.image.h-3)-1.5)<.035,'equal 3:2 panels');}assert(!data.overflow);assert(!data.preview);}
 if(state==='before'){before=data;if(width===960)assert.throws(guard,/image must fill panel/);}else{guard();assert(data.cards[0].src.includes('learn-illustration'));assert(data.cards[1].src.includes('miss-jeeves-question-desk-cutout'));if(before)for(let i=0;i<6;i++){assert.equal(data.cards[i].text,before.cards[i].text);assert.equal(data.cards[i].href,before.cards[i].href);}const grouped=Map.groupBy(data.cards,c=>c.card.y);for(const group of grouped.values()){assert(Math.max(...group.map(c=>c.card.h))-Math.min(...group.map(c=>c.card.h))<=1);assert(Math.max(...group.map(c=>c.image.h))-Math.min(...group.map(c=>c.image.h))<=1);}assert(data.wallpaper.includes('rewind-wallpaper-20260906.webp'));assert(data.banner.includes('25, 73, 195'));assert(data.pink.startsWith('linear-gradient(rgb(242, 84, 169)'));}
 if([390,960,1440].includes(width)){await p.evaluate(async()=>{await Promise.all(['/assets/homepage/rewind-wallpaper-20260906.webp','/assets/homepage/pattern-purple-computing.png'].map(async src=>{const i=new Image();i.src=src;await i.decode()}))});await p.locator('.intent-grid-5').evaluate(n=>scrollTo({top:n.getBoundingClientRect().top+scrollY-85,behavior:'instant'}));await p.waitForTimeout(250);await p.screenshot({path:`${dir}/${state}-${width}-top.png`});await p.locator('.intent-grid-5').evaluate(n=>scrollTo({top:n.getBoundingClientRect().bottom+scrollY-innerHeight*.85,behavior:'instant'}));await p.waitForTimeout(200);await p.screenshot({path:`${dir}/${state}-${width}-bottom.png`});}
 rows.push({width,state,...data});await p.close();
 }
}
fs.writeFileSync(`${dir}/${label}-checks.json`,JSON.stringify({origin,rows},null,2));console.log(label+': bright cards, equal filled panels, preserved copy/routes and no overflow verified');
}finally{await b.close()}
