import json,pathlib,hashlib,datetime
p=pathlib.Path('operations/product-stewards/newsstand/candidates/china-amodei-response-20260915');ms=p.parent/'microsoft-humanist-code-20260915';j=lambda f:json.loads((p/f).read_text());sha=lambda x:hashlib.sha256(x).hexdigest();bind=lambda f:{'path':str(p/f),'sha256':sha((p/f).read_bytes())};w=lambda f,x:(p/f).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');s=j('story.json');c=j('producer-contract.json');obs=j('producer-observations.json')
r=json.loads((ms/'producer-publication-review.json').read_text());r.update(candidateId=s['id'],reviewedAt=datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z'),artifact={'manifest':bind('publication-manifest.json'),'reviewText':bind('review-text.json'),'rendered':bind('rendered-article.html')});r['calibration']=json.loads((ms/'producer-calibration.json').read_text());r['reverseBrief']={k:c['readerContract'][v] for k,v in [('humanQuestion','humanQuestion'),('promisedPayoff','promisedPayoff'),('centralMentalModel','centralMentalModel'),('dailyLifeConnection','dailyLifeConnection'),('surfaceJob','surfaceJob'),('desiredReaderFeeling','desiredFeeling')]}
data={
'plainClarity':('how AI development is guided by rules and oversight','The only necessary governance term is explained at first use; no technical prerequisite.'),
'readerValue':('Keep three events separate','A reader can identify which actor spoke without promoting words into implemented rules.'),
'laidiesVoice':('what did it actually say?','A direct adult conversational question provides a useful route through a charged headline.'),
'engagingEnjoyable':('The disagreement includes who gets to set the pace.','A concrete authority question makes diplomatic disagreement readable without spectacle.'),
'factualIntegrity':('Guo’s quoted answer sets out China’s position on cooperation.','Exact relevant Q&A supports attribution; Global Times agenda claims deliberately excluded.'),
'freshnessReviewability':('China’s Foreign Ministry responded on September 14','Dated event is supported by current primary search Q&A and complete publisher capture, with full-page restriction stated.'),
'surfaceFit':('China answers the AI slowdown calls with a call for cooperation.','Short ordinary news fields carry one new diplomatic response, not a long geopolitical analysis.'),
'datedChange':('China’s Foreign Ministry responded on September 14','New event is this actor response, separate from prior company proposal or Trump response.'),
'consequenceAndUncertainty':('It is not evidence that China agreed to slow development or that a new rule took effect.','The limit concerns this quoted answer only; no claim that China has no other AI policy.'),
'dailyLifeConnection':('If someone says “China responded,”','A familiar conversational shorthand becomes a precise explainable statement.'),
'communicationBenchmark':('a company leader’s proposal, a government’s public position, and a rule being implemented','Visible statements are connected to the less visible implementation evidence, preserving the limit.'),
'explainBack':('Here, the ministry called for cooperation and criticized confrontation.','Reader simulation identifies the response and avoids agreed slowdown or implemented policy.'),
'unseenTransfer':('ask what requirement took effect, who it applies to and how it is enforced','The same evidence distinction applies to another government announcement without assuming Chinese facts.'),
'usefulAction':('what requirement took effect, who it applies to and how it is enforced','Precise evidence questions replace generic check-the-news instruction or unnecessary account advice.'),
'analogyIntegrity':('Keep three events separate','No analogy substitutes for diplomatic facts; the statement/proposal/rule categories are literal.')}
r['outcomes']={k:{'verdict':'PASS','observation':v[1],'artifactEvidence':[{'excerpt':v[0],'locator':'complete exact story'}]} for k,v in data.items()}
r['outcomes']['explainBack']['simulatedReaderProbe']={'prompt':'What did Guo say, and did this establish China agreed to a slowdown?','probeResponse':obs['explainBack'],'expectedEvidence':'Open inclusive AI and criticism of confrontation; no established agreement or requirement.'};r['outcomes']['unseenTransfer']['simulatedReaderProbe']={'prompt':'Another government states it favors safe AI. Has a new rule taken effect?','probeResponse':obs['unseenTransfer'],'expectedEvidence':'Seek exact requirement, affected parties and enforcement rather than infer implementation.'}
family={'glossaryAccumulation':'One inline governance definition; no detached glossary.','templateRepetition':'Story advances response, disputed access proposal and evidentiary effect.','decorativeAnalogy':'Literal proposal/position/rule distinction; no cultural analogy.','referenceConfetti':'One complete relevant Q&A and one complete publisher report; no unrelated namedrops.','missingMechanism':'Implementation requires an actual requirement, scope and enforcement; statement alone does not supply those.','genericAction':'Three concrete evidence questions identify what would substantiate a rule claim.','jargonBeforeMeaning':'Governance is defined immediately as rules and oversight.','disconnectedSystem':'Company proposal, ministry position and implementation are explicitly separate.','factlessConfidence':'The no-agreement conclusion is bounded to evidence in this response.','staleUnreviewableClaims':'September14 statement supported by September15 normal source surfaces and explicit access limits.','corporateSludge':'No promotional company or nationalist editorial rhetoric adopted.','joylessInstruction':'Who sets the pace and a conversational correction give a useful human point.','benchmarkNameDrop':'Public prose does not name the communication benchmark.','curiosityWithoutPayoff':'Who sets the pace is answered through attributed restrictions and ministry response.','familiarExampleWithoutTechnicalReturn':'China responded shorthand reconnects immediately to exact ministry words.','communicationPastiche':'Original direct news wording; no presenter persona copied.','entertainmentBeforeUnderstanding':'No geopolitical spectacle or joke replaces attribution.','mechanismCompressedBehindHook':'Meaning of governance and evidence needed for implementation appear in short connected paragraphs.','prematureClickBeforeMechanism':'Dated news answer comes first; rule distinction follows its factual basis.','inflatedTakeawayEnding':'Cocktail repeats only ministry position and limits, no grand prediction.','purposeTooNarrow':'International rule-making is civic context, not limited to workplace accounts.','mechanismBeforeMotivation':'Dated response and disagreement precede evidence questions.','workedExampleOvertakesBookPurpose':'One conversational sentence within a short news item.','technicalExplainerVoice':'Ordinary proposal, position and rule terms carry the explanation.'}
r['failureFamilies']={k:{'present':False,'observation':family[k],'artifactLocator':'complete exact story'} for k in r['failureFamilies']};sb=bind('editorial-input.json');r['factualReview']={'disposition':'CLAIMS_REVIEWED','sourceBindings':[sb],'claimMap':[{**cl,'sourceBinding':sb} for cl in j('claim-map.json')],'reviewedThrough':'2026-09-15','nextTrigger':'Actual official agreement, policy requirement or implementation evidence; any corrected transcript or publisher correction.','correctionOwner':'LAiDIES NewsStand product steward'};r['lineage']={'kind':'FIRST','noComparableReason':'First checksum-bound ordinary prose for this ministry response; earlier research HOLD had no completed prose candidate.'};r['ratchet']={'repeatedKnownDefects':0,'objectiveDefectsFirstFoundAtReview':0,'reviewIssues':0,'reviewCycles':1,'onKnownDefect':'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'}
art=not obs['unresolvedIssues'];r['verdict']='PASS' if art else 'HOLD';r['learningDisposition']={'disposition':'NO_NEW_DEFECT' if art else 'EVIDENCE_GAP','rationale':'No reusable prose defect found in actual full read. Root exact reuse-art admission remains an upstream dependency until bound.'};r['limits']=[] if art else ['ROOT_REUSE_ART_ADMISSION_REQUIRED'];r['limitations']=['Producer assessment only, not independent admission.','AI simulated comprehension; no observed human readers.','Complete relevant Q&A from actual search-display transcription, not full primary page.','No assembly, queue, canonical or public writes.'];w('producer-publication-review.json',r);w('producer-self-review.json',r)
