import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const baseline=await readFile(new URL('./live-ksvl-player.js',import.meta.url),'utf8');const candidate=await readFile(new URL('./player-candidate.js',import.meta.url),'utf8');const back=await readFile(new URL('./back-nav-candidate.js',import.meta.url),'utf8');
function get(src,name){const at=src.indexOf(`  function ${name}(`);assert.ok(at>=0,name);let i=src.indexOf('{',at),n=0;for(;i<src.length;i++){if(src[i]==='{')n++;if(src[i]==='}'&&!--n)return src.slice(at,i+1)}throw Error(name)}
function runner(src,{playing=true,remote=false,path='/radio'}={}){const handlers={window:{},document:{}};const session={};let hydrated=[],following=remote;const code=`const session=deps.session,NAV_KEY='laidies_ksvl_navigation_v2',IS_POPUP=false,TRANSFER_KEY='transfer',localStorage={getItem(){return null},removeItem(){}};const sessionStorage={getItem:k=>session[k]??null,setItem:(k,v)=>session[k]=String(v),removeItem:k=>delete session[k]};const location={pathname:deps.path,search:''};const state={audio:deps.playing?{}:null,paused:!deps.playing};let ownsAudio=deps.playing;const window={addEventListener:(n,f)=>deps.handlers.window[n]=f};const document={addEventListener:(n,f)=>deps.handlers.document[n]=f};const history={},setInterval=()=>{};const saveState=()=>true,reportStorageLimit=()=>{},stopExistingAudio=()=>{},releaseOwnership=()=>{},followOwner=()=>deps.following,hydrateFromStorage=x=>deps.hydrated.push(x);var pendingNavigationContinuationUntil=0; ${get(src,'normalPath')} ${get(src,'consumeContinuation')} ${get(src,'takePendingNavigationContinuation')} ${get(src,'cancelPendingNavigationContinuation')} ${get(src,'beginNavigationHandoff')} ${get(src,'bindPersistenceHooks')} bindPersistenceHooks();return {session,beginNavigationHandoff,takePendingNavigationContinuation};`;const api=new Function('deps',code)({playing,path,handlers,hydrated,session,get following(){return following}});return{handlers,session,hydrated,setRemote:v=>following=v,api}}
test('baseline bfcache return always restores paused even when a valid continuation exists',()=>{const x=runner(baseline);x.session.laidies_ksvl_navigation_v2=JSON.stringify({at:Date.now(),to:'/radio',playing:true});x.handlers.window.pageshow({persisted:true});assert.deepEqual(x.hydrated,[false]);});
test('candidate bridge records only active owned playing and pageshow consumes it once',()=>{const x=runner(candidate,{playing:true});x.handlers.window['laidies:ksvl-history-return']({detail:{pathname:'/radio'}});assert.match(x.session.laidies_ksvl_navigation_v2,/"playing":true/);x.handlers.window.pageshow({persisted:true});assert.deepEqual(x.hydrated,[true]);assert.equal(x.session.laidies_ksvl_navigation_v2,undefined);});
test('candidate preserves deliberate pause, wrong destination, and a current remote owner',()=>{const paused=runner(candidate,{playing:false});paused.handlers.window['laidies:ksvl-history-return']({detail:{pathname:'/radio'}});paused.handlers.window.pageshow({persisted:true});assert.deepEqual(paused.hydrated,[false]);const wrong=runner(candidate);wrong.handlers.window['laidies:ksvl-history-return']({detail:{pathname:'/library'}});wrong.handlers.window.pageshow({persisted:true});assert.deepEqual(wrong.hydrated,[false]);const remote=runner(candidate);remote.handlers.window['laidies:ksvl-history-return']({detail:{pathname:'/radio'}});remote.setRemote(true);remote.handlers.window.pageshow({persisted:true});assert.deepEqual(remote.hydrated,[]);});
test('back-nav candidate dispatches the bounded history-return event before history.back',()=>{assert.match(back,/dispatchEvent\(new CustomEvent\('laidies:ksvl-history-return', \{detail: \{pathname: refURL\.pathname\}\}\)\)/);const dispatch=back.indexOf("dispatchEvent(new CustomEvent('laidies:ksvl-history-return'");const historyBack=back.indexOf('history.back()',dispatch);assert.ok(dispatch>=0&&historyBack>dispatch);});

test('candidate pageshow retains the original valid handoff while an owner is present and consumes it once after release',()=>{const x=runner(candidate);x.handlers.window['laidies:ksvl-history-return']({detail:{pathname:'/radio'}});const original=JSON.parse(x.session.laidies_ksvl_navigation_v2).at;x.setRemote(true);x.handlers.window.pageshow({persisted:true});assert.deepEqual(x.hydrated,[]);assert.equal(x.session.laidies_ksvl_navigation_v2,undefined,'pageshow consumed storage into the existing pending handoff');x.setRemote(false);assert.equal(x.api.takePendingNavigationContinuation(),true,'the original expiry remains pending after owner release');assert.equal(x.api.takePendingNavigationContinuation(),false,'pending continuation is one-shot');assert.ok(original<=Date.now());});

test('candidate actual consume path rejects missing, expired, future, malformed, and wrong-destination records',()=>{for(const record of [null,{at:Date.now()-15001,to:'/radio',playing:true},{at:Date.now()+60000,to:'/radio',playing:true},{at:Date.now(),to:'/library',playing:true},'bad-json']){const x=runner(candidate);if(record!==null)x.session.laidies_ksvl_navigation_v2=typeof record==='string'?record:JSON.stringify(record);x.handlers.window.pageshow({persisted:true});assert.deepEqual(x.hydrated,[false]);}});
test('back-nav actual mount listener dispatches destination before history.back',()=>{const mount=get(back,'mount');let link,backed=false,events=[];const fn=new Function('deps',`const target='/radio',refURL={pathname:'/radio'},hasInternalReturn=true,label='KSVL RAiDIO',history={length:2,back:()=>deps.back()},window={dispatchEvent:e=>deps.events.push(e)},CustomEvent=function(type,init){this.type=type;this.detail=init.detail},document={querySelector:()=>null,createElement:()=>({dataset:{},setAttribute(){},addEventListener(_n,f){this.click=f}})},ensureRail=()=>({container:{firstChild:null,insertBefore:a=>deps.setLink(a)}});${mount};mount();`);fn({events,back:()=>backed=true,setLink:a=>link=a});let prevented=false;link.click({metaKey:false,ctrlKey:false,shiftKey:false,altKey:false,button:0,preventDefault:()=>prevented=true});assert.equal(prevented,true);assert.equal(events.length,1);assert.equal(events[0].type,'laidies:ksvl-history-return');assert.equal(events[0].detail.pathname,'/radio');assert.equal(backed,true);});
