import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root='/Users/alisoneakin/Projects/laidies-homepage-corrections-20260905',packet=root+'/operations/product-stewards/town-entry-homepage/candidates/banner-green-burst-20260906',hosted=!!process.env.BANNER_ORIGIN,origin=process.env.BANNER_ORIGIN||'https://e82c0b5a.laidies-sunnyvaile.pages.dev';const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try{for(const width of [1440,390]){for(const kind of hosted?['hosted']:['parent','candidate']){const c=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted){await c.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':root+'/index.html'),contentType:'text/html'}));await c.route('**/did-you-know-question-mark-20260906.webp',r=>r.fulfill({path:root+'/assets/homepage/did-you-know-question-mark-20260906.webp',contentType:'image/webp'}));}const p=await c.newPage();await p.goto(origin+'/',{waitUntil:'domcontentloaded'});await p.evaluate(()=>document.fonts.ready);await p.locator('.dyk-slim').scrollIntoViewIfNeeded();await p.evaluate(()=>new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=reject;i.src='/assets/homepage/pattern-purple-computing.png';}));if(kind!=='parent')await p.evaluate(()=>new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=reject;i.src='/assets/homepage/did-you-know-question-mark-20260906.webp';}));
for(let i=0;i<8;i++){
 await p.evaluate(n=>{document.querySelectorAll('[data-dyk-slide]').forEach((el,j)=>{el.hidden=j!==n;el.classList.toggle('is-active',j===n);});},i);
 const active=p.locator('[data-dyk-slide]:not([hidden])');await active.locator('img').evaluate(img=>img.decode());
 const state=await active.evaluate(el=>{const copy=el.querySelector('.dyk-copy'),title=copy.querySelector('h3,.dyk-title'),cta=copy.querySelector('.dyk-cta'),head=document.querySelector('#dyk-title'),ps=getComputedStyle(head,'::before'),bs=getComputedStyle(head,'::after');return {burstMask:bs.maskImage,burstColour:bs.backgroundColor,burstWidth:bs.width,burstZ:bs.zIndex,burstPointerEvents:bs.pointerEvents,mediaBackground:getComputedStyle(el.querySelector(".dyk-media")).backgroundImage,mediaColour:getComputedStyle(el.querySelector(".dyk-media")).backgroundColor,text:copy.textContent,href:el.getAttribute('href'),radio:el.hasAttribute('data-ksvl-start-live'),image:el.querySelector('img').getAttribute('src'),colour:getComputedStyle(title).color,ctaColour:getComputedStyle(cta).color,headColour:getComputedStyle(head).color,stroke:getComputedStyle(title).webkitTextStroke,graphic:ps.backgroundImage,graphicWidth:ps.width,graphicPointerEvents:ps.pointerEvents,height:document.querySelector('.dyk-slim').getBoundingClientRect().height,overflow:document.documentElement.scrollWidth>innerWidth};});
 assert(!state.overflow);if(kind!=='parent'){assert.equal(state.burstColour,state.ctaColour);assert(state.burstMask.includes('preface-burst-v1.png'));assert.equal(state.burstZ,'-2');assert.equal(state.burstPointerEvents,'none');if(i===1)assert.equal(state.mediaBackground,'linear-gradient(135deg, rgb(255, 115, 102), rgb(242, 84, 169))');assert.equal(state.colour,'rgb(255, 155, 61)');assert.equal(state.ctaColour,'rgb(183, 228, 43)');assert.equal(state.stroke,'2px rgb(17, 24, 59)');assert(state.graphic.includes('did-you-know-question-mark-20260906.webp'));assert.equal(state.graphicPointerEvents,'none');}
 if([0,7].includes(i))await p.locator('.dyk-slim').screenshot({path:packet+'/'+kind+'-'+width+'-'+i+'.png',animations:'disabled'});
 rows.push({width,kind,slide:i,...state});
}await c.close();}}}finally{await b.close();}
if(!hosted)for(const width of [1440,390]){const a=rows.filter(r=>r.width===width&&r.kind==='parent'),c=rows.filter(r=>r.width===width&&r.kind==='candidate');for(let i=0;i<8;i++)for(const key of ['text','href','radio','image','height','mediaBackground','mediaColour'])assert.equal(a[i][key],c[i][key]);}
const result={status:'PASS',sourceSha256:hash(root+'/index.html'),assetSha256:hash(root+'/assets/homepage/did-you-know-question-mark-20260906.webp'),parentSha256:hash(packet+'/parent.html'),missingBurstDetected:hosted?undefined:rows.some(r=>r.kind==='parent'&&r.burstMask==='none'),rows};fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,sourceSha256:result.sourceSha256,rows:rows.length}));
