import fs from 'node:fs';import crypto from 'node:crypto';
import {prepareDraft,inspectPreparedDraft} from '../../../../../scripts/prepare-newsstand-draft.mjs';import {storyParagraphs} from '../../review-runtime/protocol.mjs';import {inspectContentProducerContract} from '../../../../../scripts/check-content-producer-contract.mjs';import {validateStoryTypeCoverage} from '../../../../../scripts/validate-newsstand-story-type-coverage.mjs';import {validateOrdinaryDailyLength} from '../../../../../scripts/validate-newsstand-ordinary-story-candidate.mjs';
const d='operations/product-stewards/newsstand/candidates/gates-ai-access-pledge-20260915/',read=n=>fs.readFileSync(d+n,'utf8'),json=n=>JSON.parse(read(n)),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),bind=n=>({path:d+n,sha256:sha(read(n))}),write=(n,x)=>fs.writeFileSync(d+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const stable=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(stable).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';
const s=json('story.json'),contract=json('producer-contract.json'),coverage=json('story-type-coverage.json'),claims=json('claim-map.json'),sources=json('sources-for-package.json');
write('review-text.json',stable(s)+'\n');write('rendered-article.html','<article><h1>'+s.headline+'</h1>'+s.the_story+s.laidies_read+s.what_this_means+'<p>'+s.cocktail_party+'</p><p>'+s.class_notes+'</p></article>\n');write('publication-manifest.json',{schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:s.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',reviewText:bind('review-text.json'),rendered:bind('rendered-article.html')});
const writer={...prepareDraft(contract,{root:process.cwd(),reportingFrame:coverage,sourcePacket:bind('source-evidence.json')}),producerContract:bind('producer-contract.json')};write('writer-input-current.json',writer);
write('editorial-input.json',{readerJob:contract.readerContract.humanQuestion+' '+contract.readerContract.promisedPayoff,completeArtifact:read('review-text.json'),paragraphs:storyParagraphs(s),communicationAuthority:writer.packet.communication,claims:claims.map(c=>({claimId:c.claimId,claim:c.candidateEvidence.map(e=>e.excerpt).join(' '),sourceIds:c.sourceIds})),sources,sourcePacket:{binding:bind('source-evidence.json'),rawCaptures:json('source-collection.json').records.map(x=>x.raw)},reviewBoundary:{instruction:'Read exact Gates article and complete captured AP body and report context. AP-derived maximum100 words, report-derived maximum200. Funding pledge is not delivered effectiveness; foundation rationale is not independent outcome proof. Do not resolve original announcement day or recommend medical action.'}});
const obs=json('producer-observations.json');obs.storySha256=sha(JSON.stringify(s));write('producer-observations.json',obs);write('package-integrity.json',{checkedAt:new Date().toISOString(),producerContract:inspectContentProducerContract(contract,{root:process.cwd()}),coverageErrors:validateStoryTypeCoverage(coverage,s.themes,undefined,{story:s,root:process.cwd()}),lengthErrors:validateOrdinaryDailyLength(s),preparedDraft:inspectPreparedDraft(s,writer,obs),qualityAuthority:'NONE'});console.log(read('package-integrity.json'));
