const fs=require('node:fs');
const {chromium}=require('/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const originArg=process.argv[2];if(!originArg)throw Error('Pass immutable origin');
const root=process.cwd(),d=root+'/operations/product-stewards/newsstand/evidence/lesson-link-20260905/';
const manifest=JSON.parse(fs.readFileSync(d+'artifact-manifest.json','utf8')),scope=JSON.parse(fs.readFileSync(d+'release-scope.json','utf8'));
const cases=[['/library.html#working-with-ai-101::%4010-6-trusting-the-output-and-checking-it','chapter-10-your-first-ai-agent-10-6-trusting-the-output-and-checking-it'],['/library.html#working-with-ai-101::%40chapter-4-the-art-of-iteration-4-3-how-to-give-feedback-that-works','chapter-4-the-art-of-iteration-4-3-how-to-give-feedback-that-works'],['/library.html#ai-fundamentals-101::%40ch-4-4-2-what-a-token-actually-is','ch-4-4-2-what-a-token-actually-is'],['/library.html#ai-fundamentals-101::%40ch-11-11-6-hallucination-why-it-makes-things-up','ch-11-11-6-hallucination-why-it-makes-things-up']];
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const observations=[],journeys=[];
for(const origin of [originArg,'https://laidies.ai']){const page=await browser.newPage();await page.goto(origin+'/newsstand',{waitUntil:'domcontentloaded'});const hashes=await page.evaluate(async paths=>Promise.all(paths.map(async path=>{const r=await fetch('/'+path,{cache:'no-store'});const a=await r.arrayBuffer();const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',a))].map(b=>b.toString(16).padStart(2,'0')).join('');return{path,url:r.url,status:r.status,sha256}})),scope.verificationPaths);for(const x of hashes){const expected=manifest.files.find(f=>f.path===x.path).sha256;observations.push({...x,expected,pass:x.status===200&&x.sha256===expected});if(x.status!==200||x.sha256!==expected)throw Error('Public parity differs: '+JSON.stringify(x));}await page.close();
for(const width of [1280,390])for(const [url,id]of cases){const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.goto(origin+url,{waitUntil:'domcontentloaded'});await p.waitForFunction(id=>document.activeElement?.id===id,id);const v=await p.evaluate(()=>{const e=document.activeElement,r=e.getBoundingClientRect();return{id:e.id,title:e.textContent,top:r.top,visible:r.top>=0&&r.bottom<innerHeight,overflow:document.documentElement.scrollWidth>innerWidth}});journeys.push({origin,width,url,...v});if(!v.visible||v.overflow)throw Error('Reader target failed '+JSON.stringify(v));await p.close();}}
const result={checkedAt:new Date().toISOString(),artifactIdentitySha256:manifest.identitySha256,scope:'Exact release response parity and actual focused lesson navigation; no new prose/content admission.',observations,journeys};fs.writeFileSync(d+'public-parity.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({byteChecks:observations.length,readerJourneys:journeys.length,origins:[originArg,'https://laidies.ai'],allPassed:true}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
