const fs=require('node:fs'),crypto=require('node:crypto');
const {chromium}=require('/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.cwd(),live='/var/folders/bj/tk6944ns7gn13syvg4d93cp00000gn/T/laidies-newsstand-theme-euych0dk/public/library.html';
const local=fs.readFileSync(root+'/library.html','utf8');
const extract=s=>s.slice(s.indexOf('function findBookHeading('),s.indexOf('function scrollBookTo('));
const incumbent=fs.readFileSync(live,'utf8');const candidate=incumbent.replace(extract(incumbent),extract(local));
fs.writeFileSync('/tmp/newsstand-library-link-candidate.html',candidate);
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const results=[];
 for(const width of [1280,390]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.route('https://laidies.ai/library.html*',r=>r.fulfill({status:200,contentType:'text/html',body:candidate}));await p.goto('https://laidies.ai/library.html#working-with-ai-101::%4010-6-trusting-the-output-and-checking-it',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.activeElement?.id==='chapter-10-your-first-ai-agent-10-6-trusting-the-output-and-checking-it');
 const result=await p.evaluate(resolver=>{const findBookHeading=Function('return ('+resolver+');')(); const e=document.activeElement,rect=e.getBoundingClientRect();const fixture=document.createElement('div');fixture.innerHTML='<h3 id="chapter-one-1-2-same">First</h3><h3 id="chapter-two-1-2-same">Second</h3><h3 id="chapter-10-book-10-6-checking-it">Check</h3><h3 id="exact">Exact</h3>';return {heading:e.textContent,top:rect.top,visible:rect.top>=0&&rect.bottom<innerHeight,exact:findBookHeading(fixture,'@exact')?.id==='exact',ambiguousRejected:findBookHeading(fixture,'@1-2-same')===null,missingRejected:findBookHeading(fixture,'@absent')===null,arbitrarySuffixRejected:findBookHeading(fixture,'@checking-it')===null&&findBookHeading(fixture,'@6')===null}},extract(local));results.push({width,...result});if(!result.visible||!result.exact||!result.ambiguousRejected||!result.missingRejected||!result.arbitrarySuffixRejected)throw new Error(JSON.stringify(result));await p.close();}
 const p=await b.newPage({reducedMotion:'reduce'});await p.route('https://laidies.ai/library.html*',r=>r.fulfill({status:200,contentType:'text/html',body:candidate}));const bank=JSON.parse(fs.readFileSync(root+'/operations/product-stewards/newsstand/candidates/service-bank.json','utf8'));for(const id of ['paige-02-fix-one-thing','concept-02-token','jeeves-02-citation']){const item=bank.items.find(x=>x.id===id);await p.goto('about:blank');await p.goto('https://laidies.ai'+item.destination,{waitUntil:'domcontentloaded'});await p.waitForFunction(expected=>document.activeElement?.id===expected,decodeURIComponent(item.destination.split('::')[1]).slice(1));results.push({service:id,destination:item.destination,focus:await p.evaluate(()=>({id:document.activeElement?.id,text:document.activeElement?.textContent.slice(0,100),top:document.activeElement?.getBoundingClientRect().top}))});}
 const result={candidateSha256:crypto.createHash('sha256').update(candidate).digest('hex'),scope:'Live public dependencies; exact predecessor library with only heading resolver patched. Not deployed.',results};fs.writeFileSync('/tmp/newsstand-library-link-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
