import test from 'node:test'; import assert from 'node:assert/strict'; import {readFile} from 'node:fs/promises';
const current=await readFile(new URL('./baseline.js',import.meta.url),'utf8'); const candidate=await readFile(new URL('./candidate.js',import.meta.url),'utf8');
function fn(src,name){const at=src.indexOf(`  function ${name}(`);assert.ok(at>=0,name);let i=src.indexOf('{',at),n=0;for(;i<src.length;i++){if(src[i]==='{')n++;if(src[i]==='}'&&!--n)return src.slice(at,i+1)}throw Error(name)}
function lease(src){const a=src.indexOf('  var IS_POPUP ='),b=src.indexOf('  function playOwnedPart',a);return src.slice(a,b)}
function make(src,shared,id){let state={queue:[],index:0,mixId:null,paused:false,finished:false,volume:.8,muted:false,audio:null,restoring:false};let notices=[],controls=[];const storage={getItem:k=>shared.data.get(k)||null,setItem:(k,v)=>shared.data.set(k,String(v)),removeItem:k=>shared.data.delete(k)};const code=`const window=deps.window,document=deps.document,navigator=deps.navigator,localStorage=deps.storage,crypto=deps.crypto,state=deps.state,setInterval=deps.noop;const validateSavedState=x=>x,restoreQueue=x=>{state.queue=[{id:'welcome',title:'Welcome',src:'/welcome.mp3'}];state.index=0;state.mixId='live';state.paused=x.paused;},updateNowPlaying=deps.update,announce=deps.announce,syncSoundControls=deps.sync;nextTrack=deps.noop,prevTrack=deps.noop,stopPlayer=deps.noop,toggleShuffle=deps.noop,cycleRepeat=deps.noop,retryCurrent=deps.noop,startLive=deps.noop,startMix=deps.noop,startAlbum=deps.noop,setVolumeFromControl=deps.noop,npVolume={value:'0.8'};let np={classList:{remove:deps.noop}};const readSavedState=()=>deps.saved,saveState=deps.noop;const currentPart=()=>state.queue[state.index];const isAdmittedSource=()=>true;const playOwnedPart=()=>{};${lease(src)} ${fn(src,'hydrateFromStorage')} ${fn(src,'togglePlay')} ${fn(src,'toggleMute')} return {followOwner,hydrateFromStorage,togglePlay,toggleMute,state};`;
 const api=new Function('deps',code)({window:{location:{pathname:'/library',search:''},addEventListener(){}},document:{addEventListener(){},querySelectorAll:()=>[]},navigator:{locks:{request:async(_n,_o,cb)=>{if(shared.owner)return cb(null);shared.owner=id;cb({name:_n});return undefined}}},storage,crypto:{randomUUID:()=>id},state,update(){},announce:(m)=>notices.push(m),sync:()=>controls.push(state.restoring?.time??0),noop(){},saved:{v:1,paused:false,finished:false,currentTime:37,ctx:'live'}});return{api,state,notices,controls}}
function owner(id){return JSON.stringify({id,at:Date.now(),popup:false,duration:218,playback:{v:1,paused:false,currentTime:6},upNextTitle:'Next'})}
async function tick(){await new Promise(r=>setImmediate(r))}
test('actual current functions let passive follower acquire released Web Lock before successor',async()=>{const shared={data:new Map([['laidies_ksvl_owner_v2',owner('predecessor')]]),owner:'predecessor'};const follower=make(current,shared,'follower'),successor=make(current,shared,'successor');follower.api.followOwner();successor.api.followOwner();shared.owner=null;shared.data.delete('laidies_ksvl_owner_v2');follower.api.followOwner();await tick();assert.equal(shared.owner,'follower');successor.api.hydrateFromStorage(true);await tick();assert.equal(shared.owner,'follower');});
test('candidate actual functions keep passive follower lock-free and successor acquires',async()=>{const shared={data:new Map([['laidies_ksvl_owner_v2',owner('predecessor')]]),owner:'predecessor'};const follower=make(candidate,shared,'follower'),successor=make(candidate,shared,'successor');follower.api.followOwner();successor.api.followOwner();shared.owner=null;shared.data.delete('laidies_ksvl_owner_v2');follower.api.followOwner();await tick();assert.equal(shared.owner,null);assert.match(follower.notices.at(-1),/Pick up where you left off/);assert.equal(follower.controls.at(-1),37);successor.api.hydrateFromStorage(true);await tick();assert.equal(shared.owner,'successor');});
test('candidate explicit Resume keeps saved time and then requests the lock',async()=>{const shared={data:new Map(),owner:null};const p=make(candidate,shared,'resume');p.api.hydrateFromStorage(false);assert.equal(shared.owner,null);p.api.togglePlay();await tick();assert.equal(shared.owner,'resume');assert.deepEqual(p.state.restoring,{time:37,play:true},'the actual toggle branch retains saved time until owned playback consumes it');});

test('candidate actual toggleMute works while passively restored without audio or a lock request',()=>{const shared={data:new Map(),owner:null};const p=make(candidate,shared,'mute');p.api.hydrateFromStorage(false);assert.equal(p.state.muted,false);p.api.toggleMute();assert.equal(p.state.muted,true);p.api.toggleMute();assert.equal(p.state.muted,false);assert.equal(shared.owner,null);assert.deepEqual(p.notices.slice(-2),['KSVL is muted.','KSVL sound is on.']);});
