import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const packet='operations/product-stewards/town-entry-homepage/candidates/activity-spacing-20260906',hosted=!!process.env.ACTIVITY_ORIGIN,origin=process.env.ACTIVITY_ORIGIN||'https://5ae26b3c.laidies-sunnyvaile.pages.dev',stage=fs.readFileSync('/tmp/laidies-current-cards-stage.txt','utf8').trim();
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceSha256=sha(fs.readFileSync('index.html')),rows=[];const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const settle=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const measure=page=>page.evaluate(()=>{const box=e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y+scrollY,w:b.width,h:b.height};};return{overflow:document.documentElement.scrollWidth>innerWidth,columns:getComputedStyle(document.querySelector('.activity-grid')).gridTemplateColumns.split(' ').length,grid:box(document.querySelector('.activity-grid')),cards:[...document.querySelectorAll('.activity-grid>article')].filter(a=>!a.hidden).map(a=>{const paragraphs=[...a.querySelectorAll('p')],last=paragraphs.at(-1),button=a.querySelector('button'),b=button.getBoundingClientRect(),r=last.getBoundingClientRect(),im=a.querySelector('img');return {name:a.querySelector('h3').innerText,box:box(a),paragraphMin:paragraphs.map(p=>p.style.minHeight),gap:b.top-r.bottom,button:box(button),bodyFont:getComputedStyle(last).fontFamily,bodySize:getComputedStyle(last).fontSize,headingFont:getComputedStyle(a.querySelector('h3')).fontFamily,headingWeight:getComputedStyle(a.querySelector('h3')).fontWeight,colour:getComputedStyle(last).color,background:getComputedStyle(a).backgroundImage,image:im.getAttribute('src'),imageBox:box(im),decoded:im.complete&&im.naturalWidth>0,text:a.textContent.replace(/\s+/g,' ').trim(),action:button.getAttribute('onclick'),headingY:box(a.querySelector('h3')).y};})};});
const check=s=>{assert(!s.overflow);for(const c of s.cards){assert(c.paragraphMin.every(h=>h===''));assert(Math.abs(c.gap-14)<1,'description-to-button gap');assert(c.decoded);assert(c.button.x>=c.box.x&&c.button.x+c.button.w<=c.box.x+c.box.w+.1);assert(c.button.y+c.button.h<c.box.y+c.box.h);}};
try{for(const width of hosted?[1440,1074,390]:[1440,1074,390,320])for(const kind of hosted?['hosted']:['parent','candidate']){const ctx=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});
if(!hosted)await ctx.route(origin+'/**',r=>{const u=new URL(r.request().url()).pathname;const f=u==='/'?(kind==='parent'?packet+'/parent.html':'index.html'):stage+u;return fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.continue();});
const page=await ctx.newPage();const res=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});if(kind!=='parent')assert.equal(sha(await res.body()),sourceSha256);await page.evaluate(()=>document.fonts.ready);await page.locator('.activity-grid>article>img').evaluateAll(is=>Promise.all(is.map(i=>{i.loading='eager';return i.decode();})));await settle(page);let state=await measure(page);if(kind==='parent'&&width>560)assert.throws(()=>check(state));else if(kind!=='parent')check(state);
const capture=async(suffix,selector)=>{await page.screenshot({path:packet+'/'+kind+'-'+width+'-'+suffix+'.png',fullPage:true,clip:await page.locator(selector).first().evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,width:r.width,height:r.height};}),animations:'disabled'});};if(width>=1074)await capture('grid','.activity-grid');else if(width===390){await capture('fairy','#help');await capture('dream','.activity-grid>article:nth-child(4)');}
const filterChecks=[];if(kind!=='parent'){for(const [name,count] of [['help',3],['decide',1],['fun',4],['quick',4],['all',6]]){await page.locator('[data-filter="'+name+'"]').click();await settle(page);const m=await measure(page);check(m);assert.equal(m.cards.length,count);filterChecks.push({name,count,gaps:m.cards.map(c=>c.gap),noOverflow:!m.overflow});}if(width===1074){for(const resized of[760,390,1074]){await page.setViewportSize({width:resized,height:1000});await settle(page);const m=await measure(page);check(m);filterChecks.push({resized,gaps:m.cards.map(c=>c.gap),noOverflow:!m.overflow});}}}
rows.push({kind,width,...state,filterChecks});await ctx.close();}}
finally{await browser.close();}
if(!hosted)for(const width of[1440,1074,390,320]){const a=rows.find(r=>r.width===width&&r.kind==='parent'),b=rows.find(r=>r.width===width&&r.kind==='candidate');assert.equal(a.cards.length,b.cards.length);for(let i=0;i<a.cards.length;i++){for(const key of['text','action','image','bodyFont','bodySize','headingFont','headingWeight','colour','background'])assert.deepEqual(a.cards[i][key],b.cards[i][key],key+' preserved');assert.equal(a.cards[i].imageBox.w,b.cards[i].imageBox.w);assert.equal(a.cards[i].imageBox.h,b.cards[i].imageBox.h);}assert(b.grid.h<a.grid.h);}
fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify({status:'PASS',sourceSha256,oldStretchRejected:!hosted,rows},null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha256,rows:rows.map(r=>({kind:r.kind,width:r.width,gridHeight:r.grid.h,heights:r.cards.map(c=>c.box.h),gaps:r.cards.map(c=>c.gap),filterChecks:r.filterChecks.length}))}));
