import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const p='operations/product-stewards/town-entry-homepage/candidates/newsstand-description-20260906',stage=fs.readFileSync('/tmp/laidies-activity-spacing-stage.txt','utf8').trim(),hosted=!!process.env.NEWS_COPY_ORIGIN,origin=process.env.NEWS_COPY_ORIGIN||'https://838a6dc4.laidies-sunnyvaile.pages.dev',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceSha=hash(fs.readFileSync('index.html'));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try{for(const width of[1440,1074,390]){const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted)await ctx.route(origin+'/**',r=>{const path=new URL(r.request().url()).pathname,f=path==='/'?'index.html':stage+path;return fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.continue();});const page=await ctx.newPage();const res=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});assert.equal(hash(await res.body()),sourceSha);await page.evaluate(()=>document.fonts.ready);await page.locator('.activity-grid>article>img').evaluateAll(is=>Promise.all(is.map(i=>{i.loading='eager';return i.decode();})));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const state=await page.evaluate(()=>{const cards=[...document.querySelectorAll('.activity-grid>article')].map(a=>{const box=a.getBoundingClientRect(),b=a.querySelector('.activity-card-actions>button:last-child').getBoundingClientRect(),im=a.querySelector('img');return{height:box.height,buttonY:b.top-box.top,image:im.getAttribute('src'),decoded:im.naturalWidth>0,summary:a.querySelector('.activity-summary').textContent};});return{overflow:document.documentElement.scrollWidth>innerWidth,cards};});assert(!state.overflow);assert(state.cards.every(c=>c.decoded));if(width>560)assert(state.cards.every(c=>Math.abs(c.height-state.cards[0].height)<1&&Math.abs(c.buttonY-state.cards[0].buttonY)<1));assert(state.cards[5].summary.includes('work and life')&&state.cards[5].summary.includes('The Big Picture'));
const name=hosted?'hosted':'candidate';await page.screenshot({path:p+'/'+name+'-'+width+'.png',fullPage:true,clip:await page.locator(width===390?'.activity-grid>article:last-child':'.activity-grid').evaluate(e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y+scrollY,width:b.width,height:b.height};}),animations:'disabled'});
const more=page.locator('.activity-grid>article:last-child .activity-more');await more.click();const dialog=page.locator('#activity-detail');assert(await dialog.isVisible());const full=await dialog.locator('.activity-detail-copy').innerText();assert(full.includes('What This Means For You')&&full.includes('PAiGE')&&full.includes('sources'));assert.equal(await dialog.locator('a').getAttribute('href'),'/newsstand.html');await dialog.screenshot({path:p+'/'+name+'-'+width+'-detail.png'});await page.keyboard.press('Escape');assert(!(await dialog.isVisible()));assert(await more.evaluate(e=>e===document.activeElement));rows.push({width,...state,full,route:'/newsstand.html',escapeAndFocus:true});await ctx.close();}}finally{await browser.close();}
fs.writeFileSync(p+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify({status:'PASS',sourceSha,rows},null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha,rows:rows.map(r=>({width:r.width,heights:r.cards.map(c=>c.height),escapeAndFocus:r.escapeAndFocus}))}));
