import fs from 'node:fs';
import crypto from 'node:crypto';
import {candidateReviewText} from '../../../../../scripts/validate-newsstand-ordinary-story-candidate.mjs';
import {inspectContentProducerContract} from '../../../../../scripts/check-content-producer-contract.mjs';
import {inspectProseQualityReview} from '../../../../../scripts/check-prose-quality-admission.mjs';
import {storyParagraphs} from '../../review-runtime/protocol.mjs';
import {prepareDraft} from '../../../../../scripts/prepare-newsstand-draft.mjs';

const d='operations/product-stewards/newsstand/candidates/anthropic-lsvp-beta-20260917/';
const read=n=>fs.readFileSync(d+n,'utf8'),j=n=>JSON.parse(read(n));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const bind=n=>({path:d+n,sha256:sha(read(n))});
const write=(n,x)=>fs.writeFileSync(d+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const s=j('story.json'),c=j('producer-contract.json'),packet=j('source-packet.json'),coverage=j('story-type-coverage.json'),now=new Date().toISOString();
const art=bind('art/independent-review-v2.json');
c.visualAdmission=art;write('producer-contract.json',c);
write('review-text.json',candidateReviewText(s));
write('rendered-article.html',`<article><h1>${s.headline}</h1><figure><img src="art/generated-v1.png" alt="${s.heroVisual.alt}"><figcaption>${s.heroVisual.credit}</figcaption></figure>${s.the_story}<h2>LAiDIES Read</h2>${s.laidies_read}<h2>What This Means for You</h2>${s.what_this_means}<h2>Cocktail Party</h2><p>${s.cocktail_party}</p><h2>Class Notes</h2><p>${s.class_notes}</p></article>\n`);
write('publication-manifest.json',{schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:s.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',reviewText:bind('review-text.json'),rendered:bind('rendered-article.html'),story:bind('story.json'),heroVisual:bind('art/generated-v1.png'),visualAdmission:art});
const writer={...prepareDraft(c,{root:process.cwd(),reportingFrame:coverage,sourcePacket:bind('source-evidence.json')}),producerContract:bind('producer-contract.json')};write('writer-input-current.json',writer);
const url=s.sources[0].url,rec=packet.records[0];
const claims=[
 {claimId:'event',claim:'Anthropic announced LSVP September 17 as a beta with more permissive biology access for verified research teams.',candidateEvidence:[{excerpt:'Anthropic announced its Life Sciences Verification Program on September 17. The beta gives verified life-science teams versions of Claude that allow more biology requests than general Claude.',locator:'The Story'}],sourceIds:[rec.sourceId],sourceEvidence:[{excerpt:'Today, we are introducing the Life Sciences Verification Program (LSVP), which gives life science professionals access to our Mythos, Opus, and Sonnet models with a refined set of safeguards more permissive for biology-related work.',locator:url},{excerpt:'The program is launching in beta, initially for teams and institutions.',locator:url}],scopeAndFreshness:'Official September 17 announcement reread September 19; provider description only.'},
 {claimId:'purpose',claim:'Anthropic says LSVP is designed for life-science tasks that generally available Claude models block.',candidateEvidence:[{excerpt:'Anthropic says the program is designed for life-science work that general Claude blocks. The closest alternative is general Claude with stricter biology restrictions; special access is unnecessary when an ordinary request already works there.',locator:'LAiDIES Read'}],sourceIds:[rec.sourceId],sourceEvidence:[{excerpt:'The LSVP is designed to enable life science professionals to use our models across a wide range of tasks that are currently blocked in our generally available Fable models',locator:url}],scopeAndFreshness:'Provider purpose statement; the ordinary-use alternative is a bounded editorial consequence.'},
 {claimId:'access',claim:'Standard Use is team-wide and renewed yearly; High-risk Use is a project-specific six-month add-on that removes life-science request blocks while other safeguards remain.',candidateEvidence:[{excerpt:'Standard Use covers a team and renews yearly. High-risk Use is an extra six-month grant for one project that removes life-science request blocks. Anthropic says other safeguards remain.',locator:'LAiDIES Read'}],sourceIds:[rec.sourceId],sourceEvidence:[{excerpt:'These grants can be extended to entire teams and are renewed once a year.',locator:url},{excerpt:'High-risk Use is an add-on grant for teams working in areas blocked under Standard Use. It removes all safeguards that block life sciences requests. This grant applies to a single research project and must be renewed every six months.',locator:url},{excerpt:'All other safeguards, such as cyber classifiers, will remain in place under LSVP grants.',locator:url}],scopeAndFreshness:'Access structure as described by Anthropic; no independent safety evidence.'},
 {claimId:'monitoring',claim:'Anthropic says LSVP moves from request-time biology blocking toward monitoring patterns after activity, ties access to approved use cases and retains LSVP traffic for 30 days.',candidateEvidence:[{excerpt:'Anthropic says LSVP replaces immediate refusals with looking for patterns after activity runs. Access is tied to an approved use case. The company says it keeps LSVP traffic for 30 days so monitoring can happen.',locator:'LAiDIES Read'}],sourceIds:[rec.sourceId],sourceEvidence:[{excerpt:'Each entity’s access is tied to the use cases it has specified in its grant applications',locator:url},{excerpt:'LSVP shifts safeguards from real-time blocking to offline monitoring.',locator:url},{excerpt:'this requires 30-day retention for LSVP traffic',locator:url}],scopeAndFreshness:'Provider-stated design; effectiveness is not established.'},
 {claimId:'availability',claim:'The beta begins with teams and institutions; individual Pro and Max access is planned later.',candidateEvidence:[{excerpt:'Teams and institutions come first; individual Pro and Max access is planned later.',locator:'The Story'}],sourceIds:[rec.sourceId],sourceEvidence:[{excerpt:'The program is launching in beta, initially for teams and institutions.',locator:url},{excerpt:'We will continue to improve the program and expand access to individual Pro and Max plans over time.',locator:url}],scopeAndFreshness:'Launch availability as of September 19; may change.'}
];
const sources=[];
for(const claim of claims){
  claim.sourceIds=[];
  claim.sourceEvidence.forEach((evidence,index)=>{
    const id=`${rec.sourceId}-${claim.claimId}-${index+1}`;
    claim.sourceIds.push(id);
    sources.push({id,url,authority:'Official Anthropic announcement for the existence and described rules of its own program.',source:{url,passage:evidence.excerpt,passageLocator:rec.readScope},limitations:rec.limitations.join(' ')});
  });
}
write('editorial-input.json',{readerJob:`${c.readerContract.humanQuestion} ${c.readerContract.promisedPayoff}`,completeArtifact:read('review-text.json'),paragraphs:storyParagraphs(s),communicationAuthority:c.communicationDesign,claims,sources,reviewBoundary:{status:'PENDING_DISTINCT_INDEPENDENT_REVIEW',instruction:'Treat Anthropic as the source for its own program. Do not infer safety effectiveness, research quality, clinical value or public availability. Confirm that the prose distinguishes request-time blocking from monitoring after activity and does not describe dangerous biology.'}});
const obs={schemaVersion:'laidies-newsstand-producer-observations.v1',candidateId:s.id,completeTextRead:true,storySha256:sha(JSON.stringify(s)),readerAnswers:{event:'Anthropic announced its Life Sciences Verification Program on September 17.',eligibility:'This changes access for vetted research institutions, not your personal Claude account.',controls:'Vetting happens before access; monitoring happens after requests run.',evidence:'It does not prove that the controls have prevented misuse.'},terms:{'vetted access':'Applicants are reviewed for research credentials, security and ethical oversight.',monitoring:'looking for patterns after activity runs'},explainBack:'This is an institutional beta, not a change to my personal Claude account. Anthropic verifies access first, then monitors activity afterward; its announcement does not prove that this stopped misuse.',unseenTransfer:'For another safety headline, I should ask who gets access, whether the control blocks before action or reviews later, and what outcome evidence shows it worked.',unresolvedIssues:[],repairsMade:['Replaced specialist eligibility headline with the dated restrictions change.','Removed BAA and cyber-classifier jargon from the reader-facing prose.','Reframed the consequence for an adult beginner hearing AI-and-bioweapons news, rather than a lab administrator.','Explained 30-day retention as the time Anthropic says it keeps LSVP traffic so monitoring can happen.','Added the model-release best-fit, unnecessary-use and nearest-alternative boundary before provider review.','Bound the current Library guardrails section and conservatively mapped the source-derived wording below 200 words.'],limitations:['Producer AI simulations; no observed human comprehension test.','The only factual source is Anthropic’s own announcement; no independent safety, research or program-outcome evidence.','Independent art admission and independent editorial review remain separate gates.']};write('producer-observations.json',obs);
const template=JSON.parse(fs.readFileSync('operations/product-stewards/newsstand/candidates/claude-cowork-merge-20260916/producer-publication-review.json','utf8'));
template.candidateId=s.id;template.maker='/root/aft_school_story';template.reviewer={id:'/root/aft_school_story',principalId:'/root/aft_school_story',role:'Producer exact complete prose read',modelFamily:'openai'};template.reviewedAt=now;
template.artifact={manifest:bind('publication-manifest.json'),reviewText:bind('review-text.json'),rendered:bind('rendered-article.html')};template.reverseBrief={humanQuestion:c.readerContract.humanQuestion,promisedPayoff:c.readerContract.promisedPayoff,centralMentalModel:c.readerContract.centralMentalModel,dailyLifeConnection:c.readerContract.dailyLifeConnection,surfaceJob:c.readerContract.surfaceJob,desiredReaderFeeling:c.readerContract.desiredFeeling};
const evidence={plainClarity:'Vetting happens before access; monitoring happens after requests run.',readerValue:'This changes access for vetted research institutions, not your personal Claude account.',laidiesVoice:'Less blocking does not mean no monitoring.',engagingEnjoyable:'who gets access',factualIntegrity:'It does not prove that the controls have prevented misuse.',freshnessReviewability:'Anthropic announced its Life Sciences Verification Program on September 17.',surfaceFit:s.headline,datedChange:'Anthropic announced its Life Sciences Verification Program on September 17.',consequenceAndUncertainty:'The announcement explains how Anthropic intends the system to work. It does not prove that the controls have prevented misuse.',dailyLifeConnection:'For the next headline, ask whether it concerns a public account or a verified program',communicationBenchmark:'Vetting happens before access; monitoring happens after requests run.',explainBack:obs.explainBack,unseenTransfer:obs.unseenTransfer,usefulAction:'ask whether a safeguard blocks a request before it runs or reviews activity later',analogyIntegrity:'No analogy is used; the actual before-access and after-request sequence is explained.'};
for(const [k,o] of Object.entries(template.outcomes)){o.verdict='PASS';o.observation='The complete producer read keeps institutional eligibility, changed request blocking, later monitoring and the missing outcome evidence connected without describing dangerous biology or addressing the reader as a lab worker.';o.artifactEvidence=[{excerpt:evidence[k]||s.headline,locator:'complete exact story'}];}
template.outcomes.explainBack.simulatedReaderProbe={prompt:c.readerContract.humanQuestion,probeResponse:obs.explainBack,expectedEvidence:'Institutional beta, personal account unchanged, before-access vetting, after-request monitoring, no proven outcome.',transferResult:'PASS'};
template.outcomes.unseenTransfer.simulatedReaderProbe={prompt:'How should I read a different claim that an AI safety control changed?',probeResponse:obs.unseenTransfer,expectedEvidence:'Ask who gets access, when the control acts and what evidence shows it worked.',transferResult:'PASS'};
template.outcomes.explainBack.artifactEvidence=[{excerpt:'This changes access for vetted research institutions, not your personal Claude account. Vetting happens before access; monitoring happens after requests run.',locator:'What This Means'}];
template.outcomes.unseenTransfer.artifactEvidence=[{excerpt:'For the next headline, ask whether it concerns a public account or a verified program, whether a safeguard blocks a request before it runs or reviews activity later, and what evidence shows the control worked.',locator:'What This Means'}];
template.outcomes.usefulAction.artifactEvidence=[{excerpt:'For the next headline, ask whether it concerns a public account or a verified program, whether a safeguard blocks a request before it runs or reviews activity later, and what evidence shows the control worked.',locator:'What This Means'}];
template.outcomes.analogyIntegrity.artifactEvidence=[{excerpt:'Vetting happens before access; monitoring happens after requests run.',locator:'What This Means'}];
for(const [k,f] of Object.entries(template.failureFamilies)){f.present=false;f.observation=`Actual read avoids ${k}: the dated program change, institutional boundary, safeguard mechanism and evidence limit stay connected in plain language.`;f.artifactLocator='complete exact story';}
const input=bind('editorial-input.json');template.factualReview={disposition:'CLAIMS_REVIEWED',sourceBindings:[input,bind('source-packet.json'),bind('source-evidence.json')],claimMap:claims.map(x=>({...x,status:'QUALIFIED',sourceBinding:input})),reviewedThrough:'2026-09-19',nextTrigger:'Material eligibility, grant, monitoring, retention or availability change; or publication after September 19.',correctionOwner:'NewsStand product steward'};
template.ratchet={repeatedKnownDefects:0,objectiveDefectsFirstFoundAtReview:0,reviewIssues:0,reviewCycles:1,onKnownDefect:'REPAIR_PRODUCER_BEFORE_ANOTHER_REVIEW'};template.lineage={kind:'FIRST',noComparableReason:'First NewsStand story on Anthropic’s September 17 Life Sciences Verification Program; the prior threat report concerns misuse incidents, not this access program.'};template.learningDisposition={disposition:'NO_NEW_DEFECT',rationale:'Specialist framing and unexplained contract jargon were repaired before independent editorial review.'};template.verdict='PASS';template.limitations=obs.limitations;write('producer-publication-review.json',template);
const cc=inspectContentProducerContract(c,{root:process.cwd()}),rc=inspectProseQualityReview(template,{root:process.cwd()});write('contract-integrity.json',cc);write('producer-self-review-check.json',rc);const errors=[...cc.errors,...rc.errors];if(errors.length)throw Error(errors.join('\n'));
console.log(JSON.stringify({status:'PRODUCER_SELF_REVIEW_PASS',story:bind('story.json'),reviewText:bind('review-text.json'),producerReview:bind('producer-publication-review.json'),sourceBudget:j('source-budget-final.json').totals},null,2));
