import fs from 'node:fs';
import crypto from 'node:crypto';
const id='microsoft-aft-school-privacy-20260915',dir=`operations/product-stewards/newsstand/candidates/${id}`,base='operations/product-stewards/newsstand/evidence/recovery-1300-20260915';
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const read=p=>fs.readFileSync(p,'utf8'),write=(n,v)=>fs.writeFileSync(`${dir}/${n}`,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n'),bind=n=>({path:`${dir}/${n}`,sha256:hash(read(`${dir}/${n}`))});
const raw=n=>JSON.parse(read(`${base}/${n}`)).raw;
const ap=raw('independent-capture-originals.json').split('\n').filter(l=>{const m=l.match(/^L(\d+)/);return m&&Number(m[1])>=1752&&Number(m[1])<=1847}).join('\n');
const all=raw('independent-capture-final-originals.json'),ms=all.slice(all.indexOf('AFT, UFT and Microsoft announce')+'AFT, UFT and Microsoft announce'.length).split('--------------------------------------------------------------------------------')[0];
const moa=all.slice(all.lastIndexOf('--------------------------------------------------------------------------------')+80)+'\n'+raw('independent-capture-final-details.json');
write('source-ap.txt',ap);write('source-microsoft.txt','AFT, UFT and Microsoft announce'+ms);write('source-signed-agreement.txt',moa);
const research=JSON.parse(read(`${base}/independent-microsoft-aft-school-privacy-research-candidate.json`));
write('source-evidence.json',{schemaVersion:'SOURCE_BOUND_NEWS_EVIDENCE',checkedAt:research.recordedAt,records:research.sources.map((r,i)=>({...r,id:['ap-report','microsoft-announcement','signed-moa'][i],exactCapture:{path:`${base}/${r.capture}`,sha256:hash(read(`${base}/${r.capture}`))},localText:bind(['source-ap.txt','source-microsoft.txt','source-signed-agreement.txt'][i]),limitation:i===2?'Collected complete supplied passages, not all 31 pages.':null})),nextTrigger:'Reopen sources if publishing after September15 or if implementation terms change.',omittedClaim:'November1 implementation is omitted: linked fact sheet has not been captured.'});
const c=JSON.parse(read('operations/product-stewards/newsstand/candidates/nyc-school-ai-20260911/producer-contract-v2.json'));
c.candidateId=id;c.producer='/root/aft_school_story';
c.readerContract={humanQuestion:research.readerQuestion,promisedPayoff:'Know what a US school must request, which education AI is covered, and why privacy promises do not prove learning value or correct answers.',priorKnowledge:'No procurement, training or telemetry vocabulary assumed.',centralMentalModel:'The protection follows the specific product and school agreement; it does not follow the company name everywhere.',dailyLifeConnection:'A parent or teacher may be asked to trust an AI school assignment without knowing where the conversation goes.',surfaceJob:'September15 independent-report-led bounded Daily report on September9 announcement and September7 signed agreement.',desiredFeeling:'I can ask which product and terms cover this school assignment.'};
c.canonicalTruth=[{claimId:id,owner:'AFT and Microsoft own the signed commitment; Microsoft owns its announcement; AP owns independent reactions; NewsStand owns bounded synthesis.',source:bind('source-evidence.json'),freshnessTrigger:'Reopen exact sources if publication slips after September15 or implementation changes.'}];
for(const d of Object.values(c.knownFailurePreflight.dispositions)){d.producerGuard='Lead with requestable school-agreement scope; define generated content, training and anonymous operations data where needed. Preserve opt-in, education-designed restriction, narrow safety exception and incorrect-answer limit. No automatic all-schools rollout, all-products claim or legal-compliance advice.';d.preventionEvidence='The planned explanation follows school request → covered product → data-use limits → retained accuracy/learning uncertainty → exact question about the assignment.';}
c.knownFailurePreflight.candidateRepairPreflight={scope:'US opt-in education-designed AI only.',data:'Anonymous telemetry differs from covered identifiable data; no generative training permitted for telemetry.',limits:'No accuracy guarantee, certification-completion claim or all-company signature claim.',distinct:'School agreement is distinct from public MAI consultation.'};
c.draftArchitecture={openingJob:'School agreement scope first; dates separate.',causalSequence:['A US school requests applicable terms.','Only primarily education-designed AI is covered.','Covered identifiable data cannot feed general model training; safety processing has narrow limits.','Anonymous operational telemetry has separate permitted uses.','Privacy commitment does not establish accurate answers or teaching value.'],workedCase:'An AI tutoring assignment needs its own product-and-agreement check; a general work assistant used by a teacher is not covered simply because Microsoft supplies it.',transferCase:'A school subscription does not extend these terms to every app with the same vendor name.',usefulAction:'Ask which exact product is being assigned and whether the school incorporated these standards into its agreement.',formatSpecificStructure:'The Story; LAiDIES Read; What This Means for You; Cocktail Party; Class Notes.',antiTemplateDecision:'No legal checklist, product list, sweeping AI-in-school moral or decorative nostalgia.',analogyPlan:[],humourPlan:{noneReason:'An exact assignment example is clearer than a joke about student privacy.'},readerQuestions:[{id:'scope',question:'What must the school do and which products are covered?'},{id:'data',question:'What happens to student and educator information?'},{id:'limit',question:'Does the agreement make the tool accurate or educationally worthwhile?'},{id:'action',question:'What can a family or teacher ask about a specific assignment?'}],requiredTerms:[{term:'generative AI',meaning:'creates text or other content from instructions'},{term:'training',meaning:'changing an AI model for future use'},{term:'telemetry',meaning:'anonymous technical records about how a service operates'}],presentationPlan:'Potential reuse latest-checking is a people-free evidence-check illustration. Exact prior admission not yet located; no image admitted in this lane and no review call until binding resolved.'};
c.draftArchitecture.plainAnswer='US schools may request these protections in their agreements for primarily education-designed AI; they do not automatically cover every school or general-purpose product.';
c.communicationDesign.surfaceAdaptation='Answer scope first, show a tutoring assignment versus a general work assistant, and retain data/accuracy limits beside promises.';
for(const [k,d] of Object.entries(c.communicationDesign.dimensions)){d.reason='Help a family distinguish a product-and-school-agreement protection from a company-wide promise.';d.plannedEvidence='Request → covered education product → data boundaries → assignment question. No joke.';}
c.communicationDesign.explanationArc={mode:'PROPORTIONAL',retainedMoves:['school assignment','requestable scope','data-use boundary','accuracy limit','exact product question'],adaptation:'Direct policy answer first, small assignment example makes procurement scope tangible.'};c.communicationDesign.discoveryChecks=[{question:'Does a school Microsoft subscription cover every Microsoft app?',answer:'No. The signed definition excludes general-purpose products even when schools license them.'},{question:'Does privacy compliance prove correct answers?',answer:'No. The agreement requires notices that AI outputs can be incorrect.'}];
c.representativeProofPlan={highestRisk:'Automatic all-schools/all-products interpretation and safety as accuracy guarantee.',plannedProof:'Exact scope sentence and incorrect-answer limit beside the protections.',acceptanceOutcome:'Reader asks which product and incorporated school terms apply.'};
write('producer-contract.json',c);
