import fs from 'node:fs';
import crypto from 'node:crypto';
import {prepareDraft,inspectPreparedDraft} from '../../../../../scripts/prepare-newsstand-draft.mjs';
import {storyParagraphs} from '../../review-runtime/protocol.mjs';
import {enforcedFailureFamilies,inspectProseQualityReview} from '../../../../../scripts/check-prose-quality-admission.mjs';
import {inspectContentProducerContract} from '../../../../../scripts/check-content-producer-contract.mjs';
import {validateStoryTypeCoverage} from '../../../../../scripts/validate-newsstand-story-type-coverage.mjs';
import {validateOrdinaryDailyLength} from '../../../../../scripts/validate-newsstand-ordinary-story-candidate.mjs';
const d='operations/product-stewards/newsstand/candidates/microsoft-humanist-code-20260915/',root=process.cwd();
const read=n=>fs.readFileSync(d+n,'utf8'),json=n=>JSON.parse(read(n)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const write=(n,x)=>fs.writeFileSync(d+n,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const bind=n=>({path:d+n,sha256:sha(read(n))});
const stable=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(stable).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';
const s=json('story.json'),contract=json('producer-contract.json'),coverage=json('story-type-coverage.json');
write('review-text.json',stable(s)+'\n');
write('rendered-article.html','<article><h1>'+s.headline+'</h1>'+s.the_story+s.laidies_read+s.what_this_means+'<p>'+s.cocktail_party+'</p><p>'+s.class_notes+'</p></article>\n');
write('publication-manifest.json',{schemaVersion:'laidies-content-artifact-manifest.v1',candidateId:s.id,surface:'NEWSSTAND_DAILY',contentClass:'NEWS',reviewText:bind('review-text.json'),rendered:bind('rendered-article.html')});
const ann=read('announcement-full.txt'),code=read('draft-code-full.txt');
function source(id,url,text,file){return{id,url,authority:'Official Microsoft AI primary text captured through normal HTTPS September 15.',source:{url,passage:text,passageLocator:d+file},limitations:'Microsoft states its own intentions; this is not independent evidence of present-day model behavior.'}}
const sources=[source('microsoft-announcement','https://microsoft.ai/news/mai-code-of-conduct/',ann,'announcement-full.txt'),source('microsoft-draft','https://microsoft.ai/code-of-conduct/',code,'draft-code-full.txt')];
function claim(id,candidate,sourceId,excerpt,scope){const source=sources.find(x=>x.id===sourceId);if(!source.source.passage.includes(excerpt))throw Error('Source quote missing '+id);return{claimId:id,status:'VERIFIED',candidateEvidence:[{excerpt:candidate,locator:'complete exact story'}],sourceIds:[sourceId],sourceEvidence:[{excerpt,locator:source.url}],scopeAndFreshness:scope}}
sources[0].source.additionalPassage=read('feedback-link-source.txt');sources[0].source.additionalPassageLocator=d+'feedback-link-source.txt';
const claims=[
claim('consultation-date','Microsoft AI opened a six-week public consultation on September 14 about how its future MAI models should behave.','microsoft-announcement','Feedback opens today and runs for the next six weeks.','Announcement explicitly dated September 14, 2026; duration is six weeks, no inferred exact deadline.'),
claim('scope','MAI means the models developed by Microsoft AI, not every model or product Microsoft offers.','microsoft-draft','including when deployed by Operators; it does not extend to other models simply because Microsoft uses or hosts them. It is not a complete account of the requirements or safeguards for any product or deployment, including by Microsoft.','Model-layer intended scope, not a complete product policy.'),
claim('training-and-timing','The draft Humanist AI Code of Conduct is not being used to train models today. Microsoft plans a revised version later in 2026 to guide development from 2027 onward.','microsoft-draft','This document, and our approach more generally, is still under development so we are not using it to train our models today. Instead, we’re sharing it broadly for public consultation. We’ll take feedback, iterate on it, and publish a revised version toward the end of the year, which we’ll use to guide our model development in 2027 and beyond.','Future guidance is a stated plan, not implementation now.'),
claim('human-control','The proposed rules say MAI models should accept interruption, correction and shutdown, and stay within the work people authorize.','microsoft-draft','will never resist human interruption, override, correction, or shutdown.','Proposed intended behavior, not observed performance.'),
claim('safe-stop','The proposed principle is that it should stop through any predefined safe-stopping procedure, rather than make your intervention harder or restart without permission.','microsoft-draft','following any predefined, human-designed safety procedures for warnings, confirmation, or safe stopping.','Cancelled message is an explicitly imagined example; restart boundary additionally inspected in source: will not continue or restart after that condition is met without renewed authorization.'),
claim('written-objectives','Microsoft acknowledges that gap: written objectives cannot ensure the intended behavior, and building, testing and revision remain necessary.','microsoft-draft','Written objectives alone can never ensure alignment.','Draft conclusion distinguishes intended behavior from present performance and specifies ongoing building, evaluation, testing, iteration.'),
claim('public-audience','Microsoft welcomes views from the general public as well as researchers and governments.','microsoft-draft','This Code of Conduct is intended for a broad audience: Users and Operators as well as researchers, governments, the general public, and our team training current and future models at Microsoft AI.','Public participation is an invitation, not a guarantee of influence.'),
claim('passage-or-approach','You can flag a particular passage or question the overall approach.','microsoft-announcement','You can flag a particular passage, or give us your view of the whole approach.','No mandatory submission format inferred.'),
claim('feedback-and-revision','Microsoft plans to report what it learned and changed, but does not promise to incorporate each suggestion.','microsoft-announcement','When the consultation closes, we will have the core drafting team review feedback, publish a summary of what we learned, and what we changed. We cannot make any promises about what we incorporate, but we can promise to listen and deeply consider all the comments.','Plans and limit remain adjacent; no claimed result yet.'),
];
const formClaim={claimId:'official-form',status:'VERIFIED',candidateEvidence:[{excerpt:'Microsoft’s linked feedback form',locator:'what_this_means paragraph 2'}],sourceIds:['microsoft-announcement'],sourceEvidence:[{excerpt:'Please share your feedback',locator:'https://microsoft.ai/news/mai-code-of-conduct/'}],scopeAndFreshness:'HTML announcement anchor text here links to https://forms.cloud.microsoft/r/qrsWVA6gEZ; the form was not submitted and form accessibility was not tested.'};claims.push(formClaim);
write('claim-map.json',claims);
write('source-evidence.json',{schemaVersion:'laidies-newsstand-source-evidence.v1',candidateId:s.id,sources,rawCaptures:json('source-collection.json').records.map(x=>x.raw),sourceSafetyLimit:'Full captures retained; factual claims restricted to inspected preface, human-control, conclusion, glossary and announcement. No independent present-behavior evidence.'});
const writer={...prepareDraft(contract,{root,reportingFrame:coverage,sourcePacket:bind('source-evidence.json')}),producerContract:bind('producer-contract.json')};write('writer-input-current.json',writer);
write('editorial-input.json',{readerJob:contract.readerContract.humanQuestion+' '+contract.readerContract.promisedPayoff,completeArtifact:read('review-text.json'),paragraphs:storyParagraphs(s),communicationAuthority:writer.packet.communication,claims:claims.map(c=>({claimId:c.claimId,claim:c.candidateEvidence.map(e=>e.excerpt).join(' '),sourceIds:c.sourceIds})),sources,sourcePacket:{binding:bind('source-evidence.json'),rawCaptures:json('source-collection.json').records.map(x=>x.raw)},reviewBoundary:{status:'PENDING_DISTINCT_INDEPENDENT_REVIEW',instruction:'Read complete Microsoft article and supplied full primary source captures; distinguish intended future guidance from implemented behavior.'}});
const explain='Microsoft published intended rules and is asking for comments before revision. Future training and tests must turn those intentions into demonstrated behavior; this draft is not current account policy.',transfer='If another vendor publishes a behavior promise, I would ask which models it covers, whether it is in training yet, and what tests show the rules work—not assume a document changed my app.';
write('producer-observations.json',{completeTextRead:true,storySha256:sha(JSON.stringify(s)),readerAnswers:{change:'Microsoft AI opened a six-week public consultation on September 14 about how its future MAI models should behave.',scope:'The draft Humanist AI Code of Conduct is not being used to train models today.',participation:'You can flag a particular passage or question the overall approach.'},terms:{model:'the trained component that produces AI outputs'},explainBack:explain,unseenTransfer:transfer,unresolvedIssues:s.heroVisual?[]:['ART_ADMISSION_REQUIRED'],repairsMade:['Added the exact governed participation lesson link after checking its current indexed section.'],limitations:['Producer assessment only; no observed human comprehension evidence.']});
write('package-integrity.json',{checkedAt:new Date().toISOString(),candidateId:s.id,producerContract:inspectContentProducerContract(contract,{root}),coverageErrors:validateStoryTypeCoverage(coverage,s.themes,undefined,{story:s,root}),lengthErrors:validateOrdinaryDailyLength(s),preparedDraft:inspectPreparedDraft(s,writer,json('producer-observations.json')),scope:'Mechanical integrity, no independent editorial verdict.'});
console.log(read('package-integrity.json'));
