import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root=process.cwd(),packet=root+'/operations/product-stewards/town-entry-homepage/candidates/book-link-spacing-20260906',hosted=!!process.env.BOOK_ORIGIN,origin=process.env.BOOK_ORIGIN||'https://0081455c.laidies-sunnyvaile.pages.dev',stage='/var/folders/bj/tk6944ns7gn13syvg4d93cp00000gn/T/laidies-retro-background-rg1hwjcg/public',cover='assets/library-101/bright-family-v2/textbook-ai-fundamentals-101.png';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try{for(const width of [1440,390])for(const kind of hosted?['hosted']:['parent','candidate']){const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted){await ctx.route(origin+'/assets/**',r=>{const f=stage+new URL(r.request().url()).pathname;return fs.existsSync(f)?r.fulfill({path:f}):r.continue();});await ctx.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':root+'/index.html'),contentType:'text/html'}));}
const page=await ctx.newPage();const resp=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});const sourceSha256=hash(await resp.body());await page.evaluate(()=>document.fonts.ready);await page.locator('#why').scrollIntoViewIfNeeded();await page.locator('#why img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return Promise.race([i.decode(),new Promise(ok=>setTimeout(ok,4000))]).catch(()=>null);})));await page.evaluate(()=>document.fonts.ready);
const state=await page.evaluate(()=>{const link=document.querySelector('.why-full-link'),r=link.getBoundingClientRect(),next=document.querySelector('.women-heading').getBoundingClientRect(),copy=document.querySelector('.why-women-copy'),cs=getComputedStyle(copy),s=getComputedStyle(link),im=link.querySelector('img'),sec=document.querySelector('#why'),sr=sec.getBoundingClientRect();return {gap:next.top-r.bottom,linkWidth:r.width,contentWidth:copy.clientWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight),linkHeight:r.height,alignment:s.textAlign,justification:s.justifyContent,colour:s.color,bookTitleColour:link.querySelector('strong')?getComputedStyle(link.querySelector('strong')).color:null,linkText:link.textContent.replace(/\s+/g,' ').trim(),href:link.getAttribute('href'),cover:im?.getAttribute('src'),coverDecoded:!!im&&im.complete&&im.naturalWidth>0,overflow:document.documentElement.scrollWidth>innerWidth,bodyBackground:getComputedStyle(document.body).backgroundImage,content:document.querySelector('main').textContent.replace(/\s+/g,' ').trim(),links:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),images:[...document.querySelectorAll('main img:not(.why-full-link>img)')].map(i=>i.getAttribute('src')),otherPanels:[...document.querySelectorAll('main>section:not(#why),main>.postcard-band')].map(el=>{const c=getComputedStyle(el),r=el.getBoundingClientRect();return [el.id,r.width,r.height,c.backgroundImage,c.backgroundColor];}),whyBackground:getComputedStyle(sec).backgroundImage,sectionBox:{x:sr.x,y:sr.y+scrollY,width:sr.width,height:sr.height},transitionBox:{x:Math.max(0,sr.x-12),y:Math.max(0,r.top+scrollY-44),width:Math.min(innerWidth,sr.width+24),height:next.bottom-r.top+120}};});
assert(!state.overflow);if(kind!=='parent'){assert.equal(state.gap,width===390?32:40);assert(Math.abs(state.linkWidth-state.contentWidth)<1);assert.equal(state.alignment,'left');assert.equal(state.justification,'space-between');assert.equal(state.colour,'rgb(255, 155, 61)');assert.equal(state.bookTitleColour,'rgb(183, 228, 43)');assert.equal(state.cover,'/'+cover);assert(state.coverDecoded);assert.equal(sourceSha256,hash(fs.readFileSync(root+'/index.html')));}
await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:packet+'/'+kind+'-'+width+'-section.png',fullPage:true,clip:state.sectionBox,animations:'disabled'});await page.screenshot({path:packet+'/'+kind+'-'+width+'-transition.png',fullPage:true,clip:state.transitionBox,animations:'disabled'});rows.push({width,kind,sourceSha256,...state});await ctx.close();}
}finally{await browser.close();}
if(!hosted)for(const width of [1440,390]){const a=rows.find(r=>r.width===width&&r.kind==='parent'),b=rows.find(r=>r.width===width&&r.kind==='candidate');for(const k of ['bodyBackground','content','links','images','otherPanels','whyBackground','href','linkText'])assert.deepEqual(a[k],b[k],k+' preserved');assert(a.gap>b.gap && a.colour!==b.colour,'negative parent must fail spacing/colour requirement');}
const result={status:'PASS',sourceSha256:hash(fs.readFileSync(root+'/index.html')),coverSha256:hash(fs.readFileSync(stage+'/'+cover)),parentSha256:hash(fs.readFileSync(packet+'/parent.html')),oldSpacingAndColourRejected:hosted?undefined:true,rows};fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha256:result.sourceSha256,rows:rows.map(r=>({kind:r.kind,width:r.width,gap:r.gap,linkWidth:r.linkWidth,contentWidth:r.contentWidth}))}));
