-- Private, explicit Episode 01–04 binder; separate from auto-synchronised continuation.
-- Bounded: 2 MiB document; 16 pack/exercise versions, 24 cards and 25 quiz
-- attempts/version per episode; typed fields and pasted provider responses <=16 KiB.
-- Idempotency receipts retain only SHA-256 request digests/revisions for 30 days.
create table if not exists public.resident_episode_binders (
 owner_id uuid primary key references auth.users(id) on delete cascade, schema_version integer not null default 1 check(schema_version=1), document jsonb not null, revision uuid not null default gen_random_uuid(), updated_at timestamptz not null default now());
create table if not exists public.resident_episode_binder_mutations (
 owner_id uuid not null references auth.users(id) on delete cascade, idempotency_key uuid not null, request_sha256 text not null, expected_revision uuid, result_revision uuid not null, created_at timestamptz not null default now(), primary key(owner_id,idempotency_key));
alter table public.resident_episode_binders enable row level security;
alter table public.resident_episode_binder_mutations enable row level security;
revoke all on table public.resident_episode_binders from anon, authenticated;
revoke all on table public.resident_episode_binder_mutations from anon, authenticated;

create or replace function public.resident_episode_binder_v1_id(v jsonb, lim integer default 120) returns boolean language sql immutable set search_path='' as $$ select jsonb_typeof(v)='string' and char_length(v#>>'{}') between 1 and lim and v#>>'{}' ~ '^[A-Za-z0-9._:@-]+$' $$;
create or replace function public.resident_episode_binder_v1_text(v jsonb, lim integer default 16384) returns boolean language sql immutable set search_path='' as $$ select jsonb_typeof(v)='string' and char_length(v#>>'{}')<=lim $$;
create or replace function public.resident_episode_binder_v1_timestamp(v jsonb) returns boolean language plpgsql immutable set search_path='' as $$ begin if jsonb_typeof(v)<>'string' or v#>>'{}' !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$' then return false; end if; perform (v#>>'{}')::timestamptz; return true; exception when others then return false; end $$;
create or replace function public.resident_episode_binder_v1_placements(v jsonb) returns boolean language plpgsql immutable set search_path='' as $$ declare p jsonb; begin if jsonb_typeof(v)<>'array' or jsonb_array_length(v)>30 then return false; end if; for p in select value from jsonb_array_elements(v) loop if jsonb_typeof(p)<>'object' or (select count(*) from jsonb_object_keys(p))<>6 or not p ?& array['sticker_id','x','y','scale','rotation','z'] or not public.resident_episode_binder_v1_id(p->'sticker_id') or jsonb_typeof(p->'x')<>'number' or jsonb_typeof(p->'y')<>'number' or jsonb_typeof(p->'scale')<>'number' or jsonb_typeof(p->'rotation')<>'number' or jsonb_typeof(p->'z')<>'number' or (p->>'x')::numeric not between 0 and 1 or (p->>'y')::numeric not between 0 and 1 or (p->>'scale')::numeric not between .25 and 4 or (p->>'rotation')::numeric not between -360 and 360 or (p->>'z')::numeric<>trunc((p->>'z')::numeric) or (p->>'z')::numeric not between 0 and 99 then return false; end if; end loop; return true; exception when others then return false; end $$;

create or replace function public.resident_episode_binder_v1_is_valid(d jsonb) returns boolean language plpgsql immutable set search_path='' as $$
declare ek text; e jsonb; k text; i jsonb; f text; a jsonb;
begin
 if jsonb_typeof(d)<>'object' or (select count(*) from jsonb_object_keys(d))<>2 or not d ?& array['version','episodes'] or d->'version'<>'1'::jsonb or jsonb_typeof(d->'episodes')<>'object' or (select count(*) from jsonb_object_keys(d->'episodes'))>4 or pg_catalog.pg_column_size(d)>2097152 then return false; end if;
 for ek in select jsonb_object_keys(d->'episodes') loop
  if ek not in('01','02','03','04') then return false; end if; e:=d->'episodes'->ek;
  if jsonb_typeof(e)<>'object' or (select count(*) from jsonb_object_keys(e))<>4 or not e ?& array['packs','exercises','cards','quizzes'] or jsonb_typeof(e->'packs')<>'object' or jsonb_typeof(e->'exercises')<>'object' or jsonb_typeof(e->'cards')<>'object' or jsonb_typeof(e->'quizzes')<>'object' or (select count(*) from jsonb_object_keys(e->'packs'))>16 or (select count(*) from jsonb_object_keys(e->'exercises'))>16 or (select count(*) from jsonb_object_keys(e->'cards'))>24 or (select count(*) from jsonb_object_keys(e->'quizzes'))>8 then return false; end if;
  for k in select jsonb_object_keys(e->'packs') loop i:=e->'packs'->k; if not public.resident_episode_binder_v1_id(to_jsonb(k)) or jsonb_typeof(i)<>'object' or (select count(*) from jsonb_object_keys(i))<>4 or not i ?& array['content_id','content_version','saved_at','placements'] or not public.resident_episode_binder_v1_id(i->'content_id') or not public.resident_episode_binder_v1_id(i->'content_version') or not public.resident_episode_binder_v1_timestamp(i->'saved_at') or not public.resident_episode_binder_v1_placements(i->'placements') then return false; end if; end loop;
  for k in select jsonb_object_keys(e->'exercises') loop i:=e->'exercises'->k;
   if not public.resident_episode_binder_v1_id(to_jsonb(k)) or jsonb_typeof(i)<>'object' or (select count(*) from jsonb_object_keys(i))<>4 or not i ?& array['exercise_version','input_state','placements','updated_at'] or not public.resident_episode_binder_v1_id(i->'exercise_version') or not public.resident_episode_binder_v1_timestamp(i->'updated_at') or jsonb_typeof(i->'input_state')<>'object' or not public.resident_episode_binder_v1_placements(i->'placements') then return false; end if;
   if (select count(*) from jsonb_object_keys(i->'input_state'))=1 and i->'input_state' ? 'fields' then
    if jsonb_typeof(i->'input_state'->'fields')<>'object' or (select count(*) from jsonb_object_keys(i->'input_state'->'fields'))>64 then return false; end if;
    for f in select jsonb_object_keys(i->'input_state'->'fields') loop
     if f in('__proto__','constructor','prototype') or f !~ '^[A-Za-z0-9._:@-]{1,120}$' then return false; end if;
     if jsonb_typeof(i->'input_state'->'fields'->f)='string' then if char_length(i->'input_state'->'fields'->>f)>16384 then return false; end if;
     elsif jsonb_typeof(i->'input_state'->'fields'->f)='boolean' then null;
     elsif jsonb_typeof(i->'input_state'->'fields'->f)='number' then if (i->'input_state'->'fields'->>f)::numeric not between -1000000 and 1000000 then return false; end if;
     else return false; end if;
    end loop;
   elsif (select count(*) from jsonb_object_keys(i->'input_state'))=7 and i->'input_state' ?& array['task','responses','ratings','comparison_notes','chosen_result','final_edit','current_step'] then
    if not public.resident_episode_binder_v1_text(i->'input_state'->'task') or not public.resident_episode_binder_v1_text(i->'input_state'->'comparison_notes') or not public.resident_episode_binder_v1_text(i->'input_state'->'chosen_result') or not public.resident_episode_binder_v1_text(i->'input_state'->'final_edit') or not public.resident_episode_binder_v1_text(i->'input_state'->'current_step',120) or jsonb_typeof(i->'input_state'->'responses')<>'object' or (select count(*) from jsonb_object_keys(i->'input_state'->'responses'))<>3 or not i->'input_state'->'responses' ?& array['chatgpt','claude','gemini'] or jsonb_typeof(i->'input_state'->'ratings')<>'object' or (select count(*) from jsonb_object_keys(i->'input_state'->'ratings'))>12 then return false; end if;
    for f in select jsonb_object_keys(i->'input_state'->'responses') loop if not public.resident_episode_binder_v1_text(i->'input_state'->'responses'->f) then return false; end if; end loop;
    for f in select jsonb_object_keys(i->'input_state'->'ratings') loop if f !~ '^[A-Za-z0-9._:-]{1,80}$' or jsonb_typeof(i->'input_state'->'ratings'->f)<>'number' or (i->'input_state'->'ratings'->>f)::numeric not between 0 and 10 then return false; end if; end loop;
   else return false; end if;
  end loop;
  for k in select jsonb_object_keys(e->'cards') loop i:=e->'cards'->k; if not public.resident_episode_binder_v1_id(to_jsonb(k)) or jsonb_typeof(i)<>'object' or (select count(*) from jsonb_object_keys(i))<>3 or not i ?& array['card_version','saved_at','placements'] or not public.resident_episode_binder_v1_id(i->'card_version') or not public.resident_episode_binder_v1_timestamp(i->'saved_at') or not public.resident_episode_binder_v1_placements(i->'placements') then return false; end if; end loop;
  for k in select jsonb_object_keys(e->'quizzes') loop i:=e->'quizzes'->k; if not public.resident_episode_binder_v1_id(to_jsonb(k)) or jsonb_typeof(i)<>'object' or (select count(*) from jsonb_object_keys(i))<>2 or not i ?& array['quiz_version','attempts'] or not public.resident_episode_binder_v1_id(i->'quiz_version') or jsonb_typeof(i->'attempts')<>'array' or jsonb_array_length(i->'attempts')>25 then return false; end if;
   for a in select value from jsonb_array_elements(i->'attempts') loop if jsonb_typeof(a)<>'object' or (select count(*) from jsonb_object_keys(a))<>5 or not a ?& array['attempt_id','completed_at','score','max_score','answers'] or jsonb_typeof(a->'attempt_id')<>'string' or a->>'attempt_id' !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' or not public.resident_episode_binder_v1_timestamp(a->'completed_at') or jsonb_typeof(a->'score')<>'number' or jsonb_typeof(a->'max_score')<>'number' or (a->>'score')::numeric<0 or (a->>'max_score')::numeric<=0 or (a->>'score')::numeric>(a->>'max_score')::numeric or (a->>'max_score')::numeric>1000 or jsonb_typeof(a->'answers')<>'object' or (select count(*) from jsonb_object_keys(a->'answers'))>20 then return false; end if; for f in select jsonb_object_keys(a->'answers') loop if f !~ '^[A-Za-z0-9._:@-]{1,120}$' or jsonb_typeof(a->'answers'->f)<>'number' or (a->'answers'->>f)::numeric<>trunc((a->'answers'->>f)::numeric) or (a->'answers'->>f)::numeric not between 0 and 20 then return false; end if; end loop; end loop;
  end loop;
 end loop; return true;
exception when others then return false; end $$;

create or replace function public.get_my_resident_episode_binder_v1() returns jsonb language plpgsql security definer set search_path='' as $$ declare o uuid:=auth.uid(); r public.resident_episode_binders%rowtype; begin if o is null then raise exception using errcode='42501',message='authentication-required'; end if; select * into r from public.resident_episode_binders where owner_id=o; if r.owner_id is null then return jsonb_build_object('state','empty','binder','null'::jsonb); end if; return jsonb_build_object('state','saved','binder',jsonb_build_object('schema_version',r.schema_version,'document',r.document,'revision',r.revision,'updated_at',r.updated_at)); end $$;
create or replace function public.put_my_resident_episode_binder_v1(d jsonb,key uuid,expected uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare o uuid:=auth.uid(); digest text; receipt public.resident_episode_binder_mutations%rowtype; current_row public.resident_episode_binders%rowtype; rev uuid:=gen_random_uuid(); begin if o is null then raise exception using errcode='42501',message='authentication-required'; end if; if key is null then raise exception using errcode='22023',message='idempotency-key-required'; end if; if not public.resident_episode_binder_v1_is_valid(d) then raise exception using errcode='22023',message='invalid-resident-episode-binder-v1'; end if; if not pg_catalog.pg_try_advisory_xact_lock(pg_catalog.hashtextextended('episode-binder:'||o::text,0)) then raise exception using errcode='55P03',message='episode-binder-mutation-busy'; end if; digest:=pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(jsonb_build_object('document',d,'expected_revision',expected)::text,'UTF8')),'hex'); delete from public.resident_episode_binder_mutations where owner_id=o and created_at<now()-interval '30 days'; select * into receipt from public.resident_episode_binder_mutations where owner_id=o and idempotency_key=key; if receipt.owner_id is not null then if receipt.request_sha256<>digest then raise exception using errcode='23505',message='idempotency-conflict'; end if; return jsonb_build_object('state','saved','revision',receipt.result_revision); end if; select * into current_row from public.resident_episode_binders where owner_id=o for update; if current_row.owner_id is null then if expected is not null then raise exception using errcode='PT409',message='revision-conflict'; end if; insert into public.resident_episode_binders(owner_id,document,revision) values(o,d,rev); else if expected is null or expected<>current_row.revision then raise exception using errcode='PT409',message='revision-conflict'; end if; update public.resident_episode_binders set document=d,revision=rev,updated_at=now() where owner_id=o; end if; insert into public.resident_episode_binder_mutations(owner_id,idempotency_key,request_sha256,expected_revision,result_revision) values(o,key,digest,expected,rev); return jsonb_build_object('state','saved','revision',rev); end $$;
-- The browser client uses these public argument names. Keep the private legacy
-- implementation signature out of the RPC surface rather than relying on positional calls.
alter function public.put_my_resident_episode_binder_v1(jsonb,uuid,uuid) rename to put_my_resident_episode_binder_v1_legacy;
create function public.put_my_resident_episode_binder_v1(p_document jsonb,p_idempotency_key uuid,p_expected_revision uuid default null) returns jsonb language sql security definer set search_path='' as $$ select public.put_my_resident_episode_binder_v1_legacy(p_document,p_idempotency_key,p_expected_revision) $$;
revoke execute on function public.put_my_resident_episode_binder_v1_legacy(jsonb,uuid,uuid) from public,anon,authenticated;
revoke execute on function public.resident_episode_binder_v1_is_valid(jsonb) from public,anon,authenticated;
revoke execute on function public.get_my_resident_episode_binder_v1() from public,anon;
revoke execute on function public.put_my_resident_episode_binder_v1(jsonb,uuid,uuid) from public,anon;
grant execute on function public.get_my_resident_episode_binder_v1() to authenticated;
grant execute on function public.put_my_resident_episode_binder_v1(jsonb,uuid,uuid) to authenticated;
