import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{chromium}from'/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root='/Users/alisoneakin/Projects/laidies-homepage-corrections-20260905';const packet=root+'/operations/product-stewards/town-entry-homepage/candidates/radio-bottom-player-20260906';const origin=process.env.RADIO_ORIGIN||'https://a3e89267.laidies-sunnyvaile.pages.dev',hosted=!!process.env.RADIO_ORIGIN;
const files=['index.html','content/site/homepage.js','content/site/sv-global-header.js','learn.html','fun-connect.html','resident-referrals.html','grimoire/verification-rulebook.html'];const hashes=files.map(file=>({path:file,sha256:crypto.createHash('sha256').update(fs.readFileSync(root+'/'+file)).digest('hex')}));
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const rows=[];
async function setup(width){const c=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted)await c.route('**/*',r=>{const u=new URL(r.request().url());let file=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!file.includes('.')&&files.includes(file+'.html'))file+='.html';if(u.origin===origin&&files.includes(file))return r.fulfill({body:fs.readFileSync(root+'/'+file),contentType:file.endsWith('.js')?'text/javascript':'text/html'});return r.continue();});return c;}
async function state(p){return await p.evaluate(()=>window.KSVL_getPublicState?.());}
async function playing(p){await p.waitForFunction(()=>{const s=window.KSVL_getPublicState?.();return s&&!s.paused&&s.currentTime>0.2;},null,{timeout:20000});}
async function visibleDeck(p){await p.locator('.ksvl-now-playing.is-visible').waitFor();assert.equal(await p.locator('.ksvl-now-playing').count(),1);assert.equal(await p.locator('.ksvl-now-playing').evaluate(el=>getComputedStyle(el).position),'fixed');const box=await p.locator('.ksvl-now-playing').boundingBox();assert(box.y+box.height<=1001);assert.equal(await p.locator('script[src*="/ksvl-player.js"]').count(),1);}
try {for(const width of [1440,390]){const c=await setup(width),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/',{waitUntil:'domcontentloaded'});await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>typeof window.KSVL_startLive==='function');await p.evaluate(()=>window.KSVL_whenReady());assert.equal(await state(p),null);
await p.locator('[data-dyk-next]').click();await p.locator('[data-dyk-next]').click();const radio=p.locator('[data-dyk-slide]:visible');assert.equal(await radio.evaluate(e=>e.tagName),'BUTTON');assert.equal(await radio.getAttribute('target'),null);await radio.screenshot({path:packet+`/${hosted?'hosted-':''}radio-slide-${width}.png`});await radio.click();await playing(p);assert.equal(c.pages().length,1);assert.equal(new URL(p.url()).pathname,'/');await visibleDeck(p);const started=await state(p);
await p.locator('.ksvl-np-btn--play').click();await p.waitForFunction(()=>window.KSVL_getPublicState().paused);await p.locator('.ksvl-np-btn--play').click();await playing(p);
await p.locator('.ksvl-now-playing [aria-label="Next track"]').click();await playing(p);assert.notEqual((await state(p)).trackId,started.trackId);await p.locator('.ksvl-now-playing [aria-label="Previous track"]').click();await playing(p);assert.equal((await state(p)).trackId,started.trackId);
await p.locator('.ksvl-np-seek').focus();await p.keyboard.press('Home');for(let i=0;i<12;i++)await p.keyboard.press('ArrowRight');await p.keyboard.press('Tab');await p.waitForFunction(()=>window.KSVL_getPublicState().currentTime>1);
const departing=await state(p);await p.locator('.intent-grid a[href="/learn.html"]').click();await p.waitForURL(u=>u.pathname==='/learn'||u.pathname==='/learn.html');await visibleDeck(p);let continued=await state(p);assert.equal(continued.trackId,departing.trackId);assert(continued.currentTime>=departing.currentTime-1);const autoResumed=!continued.paused;if(continued.paused)await p.locator('.ksvl-np-btn--play').click();await playing(p);await p.screenshot({path:packet+`/${hosted?'hosted-':''}learn-controls-${width}.png`});
await p.locator('.resource-card[href="/library.html"]').click();await p.waitForURL(u=>/^\/library(?:\.html)?$/.test(u.pathname));await visibleDeck(p);assert.equal((await state(p)).trackId,departing.trackId);await p.locator('.ksvl-np-btn--play').click();const libraryControlled=await state(p);await p.screenshot({path:packet+`/${hosted?'hosted-':''}library-controls-${width}.png`});
await p.locator('.ksvl-np-btn--stop').click();await p.waitForFunction(()=>!document.querySelector('.ksvl-now-playing.is-visible'));assert.equal(await state(p),null);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);
rows.push({width,started:started.trackId,noNewTab:true,fixedControls:true,singlePlayer:true,pauseResumeNextPrevious:true,learnPositionRetained:true,learnAutoResumed:autoResumed,libraryControls:true,stopped:true,errors});await c.close();}
// Receive saved state on remaining browsing routes and verify a fresh route is silent.
const c=await setup(1440),p=await c.newPage();await p.goto(origin+'/');await p.evaluate(()=>window.KSVL_whenReady());await p.locator('.directory-disclosure>summary').click();await p.locator('.homepage-radio-pill').click();await playing(p);await p.locator('.ksvl-np-btn--play').click();const track=(await state(p)).trackId;
for(const route of ['/newsstand','/fun-connect','/games/dream-phone','/games/fairy-godmother','/resident-referrals','/grimoire/verification-rulebook']){await p.goto(origin+route,{waitUntil:'domcontentloaded'});await visibleDeck(p);const s=await state(p);assert.equal(s.trackId,track);assert(s.paused);await p.screenshot({path:packet+`/${hosted?'hosted-':''}${route.replaceAll('/','-').slice(1)}-controls.png`});rows.push({route,savedTrack:true,pausedRestore:true,singleFixedPlayer:true});}
await c.close();const fresh=await setup(390);const f=await fresh.newPage();await f.goto(origin+'/library',{waitUntil:'domcontentloaded'});await f.waitForFunction(()=>typeof window.KSVL_whenReady==='function');await f.evaluate(()=>window.KSVL_whenReady());assert.equal(await state(f),null);assert.equal(await f.locator('.ksvl-now-playing.is-visible').count(),0);await fresh.close();
}finally{await b.close();}
const result={status:'PASS',hosted,origin,source:hashes,rows,freshVisitorSilent:true};fs.writeFileSync(packet+'/'+(hosted?'hosted':'browser')+'-checks.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
