import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { chromium } from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const packet='operations/product-stewards/town-entry-homepage/candidates/jeeves-warm-panel-20260906',hosted=!!process.env.JEEVES_ORIGIN,origin=process.env.JEEVES_ORIGIN||'https://9ed7c517.laidies-sunnyvaile.pages.dev',stage=fs.readFileSync('/tmp/laidies-women-footer-stage.txt','utf8');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceSha256=sha(fs.readFileSync('index.html'));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try { for(const width of [1440,390]) for(const kind of hosted?['hosted']:['parent','candidate']) {
  const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});let mode='results',calls=[];
  if(!hosted){await ctx.route(origin+'/assets/**',r=>{const f=stage+new URL(r.request().url()).pathname;return fs.existsSync(f)?r.fulfill({path:f}):r.continue();});await ctx.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':'index.html'),contentType:'text/html'}));}
  await ctx.route('**/api/miss-jeeves',async r=>{calls.push(r.request().postDataJSON());if(mode==='error')return r.fulfill({status:503,json:{error:'unavailable'}});return r.fulfill({json:{status:'search_results',mode:'site-search',results:mode==='empty'?[]:[{title:'AI Fundamentals 101',summary:'An excerpt from the LAiDIES collection appears here.',url:'/library.html#ai-fundamentals-101'}]}});});
  const page=await ctx.newPage();const response=await page.goto(origin+'/',{waitUntil:'domcontentloaded'});if(kind!=='parent')assert.equal(sha(await response.body()),sourceSha256);
  await page.evaluate(()=>document.fonts.ready);
  const typography=await page.evaluate(()=>{const font=el=>{const s=getComputedStyle(el);return {family:s.fontFamily,weight:s.fontWeight,style:s.fontStyle,size:s.fontSize,lineHeight:s.lineHeight,colour:s.color,stroke:s.webkitTextStroke};};return {reference:font(document.querySelector('#feature-directory-title')),title:font(document.querySelector('#dyk-title')),slides:[...document.querySelectorAll('[data-dyk-slide]')].map(el=>({text:el.textContent.replace(/\s+/g,' ').trim(),href:el.getAttribute('href'),message:font(el.querySelector('h3,.dyk-title')),cta:font(el.querySelector('.dyk-cta'))}))};});
  if(kind!=='parent'){assert.equal(typography.reference.weight,'700');for(const f of [typography.title,...typography.slides.flatMap(s=>[s.message,s.cta])]){assert.equal(f.family,typography.reference.family);assert.equal(f.weight,'700');assert.equal(f.style,'normal');}}
  await page.locator('[data-dyk-next]').click();for(let n=0;n<7;n++)await page.locator('[data-dyk-next]').click();assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));const dykClip=await page.locator('[data-dyk]').evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,width:r.width,height:r.height};});await page.screenshot({path:packet+'/'+kind+'-'+width+'-banner.png',fullPage:true,clip:dykClip,animations:'disabled'});
  await page.locator('#reference').scrollIntoViewIfNeeded();await page.locator('#reference img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));
  const state=await page.evaluate(()=>{const ref=document.querySelector('#reference'),style=getComputedStyle(ref),box=el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,width:r.width,height:r.height};},colour=sel=>getComputedStyle(ref.querySelector(sel)).color;return {background:style.backgroundImage,texture:getComputedStyle(ref,'::before').backgroundImage,bodyColour:colour('p:not(.eyebrow)'),headingColour:colour('h2'),labelColour:colour('label'),inputBackground:getComputedStyle(ref.querySelector('input')).backgroundColor,exampleBackgrounds:[...ref.querySelectorAll('[data-jeeves-example]')].map(b=>getComputedStyle(b).backgroundColor),portrait:ref.querySelector('img').getAttribute('src'),portraitDecoded:ref.querySelector('img').naturalWidth>0,box:box(ref),geometry:[...ref.querySelectorAll('.jeeves-desk-copy>*,img')].map(box),allContent:document.querySelector('main').textContent.replace(/\s+/g,' ').trim(),allLinks:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href')),allImages:[...document.querySelectorAll('main img')].map(i=>i.getAttribute('src')),bodyBackground:getComputedStyle(document.body).backgroundImage,otherPanels:[...document.querySelectorAll('main>section:not(#activities),#activities>.section-heading,#activities>.activity-grid,#why')].map(el=>[el.id,box(el).width,getComputedStyle(el).backgroundImage]),overflow:document.documentElement.scrollWidth>innerWidth};});
  assert(!state.overflow&&state.portraitDecoded);if(kind!=='parent'){assert(state.background.includes('rgb(242, 84, 169)')&&state.background.includes('rgb(255, 155, 61)'));assert(state.texture.includes('pattern-retro-print-v2.png'));assert.equal(state.bodyColour,'rgb(17, 24, 59)');assert.equal(state.labelColour,state.bodyColour);assert.equal(state.inputBackground,'rgb(255, 155, 61)');assert.deepEqual(state.exampleBackgrounds,['rgb(255, 155, 61)','rgb(255, 115, 102)','rgb(242, 84, 169)']);}
  const capture=async name=>{await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));const clip=await page.locator('#reference').evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,width:r.width,height:r.height};});await page.screenshot({path:packet+'/'+kind+'-'+width+'-'+name+'.png',fullPage:true,clip,animations:'disabled'});};
  await capture('panel');
  await page.locator('[data-jeeves-example]').first().click();assert.equal(await page.locator('#lookup').inputValue(),'Why does AI make things up?');assert.equal(calls.length,0);assert(await page.locator('#homepage-jeeves-answer').isHidden());
  await page.locator('#homepage-jeeves-form button').click();await page.locator('#homepage-jeeves-answer h3').waitFor();assert.equal(calls[0].intent,'search');assert.equal(calls[0].placement,'homepage');assert.equal(await page.locator('#homepage-jeeves-answer a').getAttribute('href'),'/library.html#ai-fundamentals-101');
  const resultColour=await page.locator('#homepage-jeeves-answer h3').evaluate(el=>getComputedStyle(el).color);if(kind!=='parent')assert.equal(resultColour,'rgb(17, 24, 59)');await capture('answer');
  mode='empty';await page.locator('#homepage-jeeves-form button').click();await page.getByRole('heading',{name:'I couldn’t find a close match.'}).waitFor();
  mode='error';await page.locator('#homepage-jeeves-form button').click();await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert(await page.getByRole('button',{name:'Try again',exact:true}).isEnabled());
  const errorColour=await page.locator('#homepage-jeeves-answer p').evaluate(el=>getComputedStyle(el).color);if(kind!=='parent')assert.equal(errorColour,'rgb(17, 24, 59)');assert(calls.every(c=>c.intent==='search'));assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
  rows.push({width,kind,typography,...state,resultColour,errorColour,examplePrefillsWithoutSubmit:true,resultsEmptyErrorStates:true,fixtureRequests:calls});await ctx.close();
}} finally {await browser.close();}
if(!hosted)for(const width of [1440,390]){const a=rows.find(r=>r.width===width&&r.kind==='parent'),b=rows.find(r=>r.width===width&&r.kind==='candidate');for(const k of ['box','geometry','portrait','allContent','allLinks','allImages','bodyBackground','otherPanels'])assert.deepEqual(a[k],b[k],k+' preserved');assert.equal(a.typography.reference.weight,b.typography.reference.weight);for(let n=0;n<8;n++){assert.equal(a.typography.slides[n].text,b.typography.slides[n].text);assert.equal(a.typography.slides[n].href,b.typography.slides[n].href);for(const role of ['message','cta'])for(const k of ['size','lineHeight','colour','stroke'])assert.equal(a.typography.slides[n][role][k],b.typography.slides[n][role][k]);}assert.notEqual(a.typography.title.weight,b.typography.title.weight);assert(a.background!==b.background&&a.bodyColour!==b.bodyColour,'old navy palette must fail');}
fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify({status:'PASS',sourceSha256,oldNavyPaletteRejected:!hosted,network:'Search responses are explicit fixtures; no API spending or real query submitted.',rows},null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceSha256,rows:rows.map(r=>({kind:r.kind,width:r.width,background:r.background,overflow:r.overflow,examples:r.examplePrefillsWithoutSubmit,answerStates:r.resultsEmptyErrorStates}))}));
