import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium} from '/Users/alisoneakin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
const root='/Users/alisoneakin/Projects/laidies-homepage-corrections-20260905',packet=root+'/operations/product-stewards/town-entry-homepage/candidates/banner-polish-20260906',hosted=!!process.env.BANNER_ORIGIN,origin=process.env.BANNER_ORIGIN||'https://c48d8896.laidies-sunnyvaile.pages.dev';const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),rows=[];
try{for(const width of [1440,390]){for(const kind of hosted?['hosted']:['parent','candidate']){const c=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});if(!hosted)await c.route(origin+'/',r=>r.fulfill({body:fs.readFileSync(kind==='parent'?packet+'/parent.html':root+'/index.html'),contentType:'text/html'}));const p=await c.newPage();await p.goto(origin+'/');await p.evaluate(()=>document.fonts.ready);await p.locator('.dyk-slim').scrollIntoViewIfNeeded();
for(let i=0;i<8;i++){
 await p.evaluate(n=>{document.querySelectorAll('[data-dyk-slide]').forEach((el,j)=>{el.hidden=j!==n;el.classList.toggle('is-active',j===n);});},i);
 const active=p.locator('[data-dyk-slide]:not([hidden])');await active.locator('img').evaluate(img=>img.decode());
 const state=await active.evaluate(el=>{const copy=el.querySelector('.dyk-copy'),title=copy.querySelector('h3,.dyk-title'),cta=copy.querySelector('.dyk-cta'),media=el.querySelector('.dyk-media'),a=title.getBoundingClientRect(),z=cta.getBoundingClientRect(),m=media.getBoundingClientRect();return {text:copy.textContent,href:el.getAttribute('href'),radio:el.hasAttribute('data-ksvl-start-live'),image:el.querySelector('img').getAttribute('src'),imageDecoded:el.querySelector('img').naturalWidth>0,colour:getComputedStyle(title).color,ctaMinHeight:getComputedStyle(cta).minHeight,mediaBackground:getComputedStyle(media).backgroundColor,centreOffset:(a.top+z.bottom)/2-(m.top+m.height/2),height:document.querySelector('.dyk-slim').getBoundingClientRect().height,overflow:document.documentElement.scrollWidth>innerWidth};});
 assert(!state.overflow&&state.imageDecoded);if(kind!=='parent'){assert.equal(state.colour,'rgb(59, 20, 95)');assert.equal(state.ctaMinHeight,'0px');if(width>700)assert(Math.abs(state.centreOffset)<1,JSON.stringify(state));if(i===1)assert.equal(state.mediaBackground,'rgb(255, 253, 251)');}
 if([0,1,3].includes(i))await p.locator('.dyk-slim').screenshot({path:packet+'/'+kind+'-'+width+'-'+i+'.png',animations:'disabled'});
 rows.push({width,kind,slide:i,...state});
}
 await c.close();}}}finally{await b.close();}
if(!hosted)for(const width of [1440,390]){const a=rows.filter(r=>r.width===width&&r.kind==='parent'),c=rows.filter(r=>r.width===width&&r.kind==='candidate');for(let i=0;i<8;i++)for(const key of ['text','href','radio'])assert.equal(a[i][key],c[i][key]);assert(Math.max(...c.map(x=>x.height))-Math.min(...c.map(x=>x.height))<1);}
const linear=v=>(v/=255)<=.04045?v/12.92:((v+.055)/1.055)**2.4;const lum=rgb=>rgb.map(linear).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);const foreground=lum([59,20,95]);const contrast=Math.min(...[[125,226,194],[21,188,224]].map(rgb=>(lum(rgb.map(v=>v*.86))+.05)/(foreground+.05)));assert(contrast>=4.5);
const result={status:'PASS',sourceSha256:hash(root+'/index.html'),parentSha256:hash(packet+'/parent.html'),knownRaisedTextRejected:hosted?undefined:rows.some(r=>r.kind==='parent'&&r.width===1440&&r.ctaMinHeight !== '0px'),minimumContrast:contrast,rows};fs.writeFileSync(packet+'/'+(hosted?'hosted-checks':'checks')+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,sourceSha256:result.sourceSha256,knownRaisedTextRejected:result.knownRaisedTextRejected,minimumContrast:contrast,rows:rows.length}));
